package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * AirbagdeploymentstypeItemtype generated by hbm2java
 */
public class AirbagdeploymentstypeItemtype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private Long airbagDeployment;
	private Long airbagDeploymentsTypeItemHjid;
	private Integer airbagDeploymentsTypeItemHjindex;

	public AirbagdeploymentstypeItemtype() {
	}

	public AirbagdeploymentstypeItemtype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public AirbagdeploymentstypeItemtype(long hjid, String hjtype, long hjversion, Long airbagDeployment,
			Long airbagDeploymentsTypeItemHjid, Integer airbagDeploymentsTypeItemHjindex) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.airbagDeployment = airbagDeployment;
		this.airbagDeploymentsTypeItemHjid = airbagDeploymentsTypeItemHjid;
		this.airbagDeploymentsTypeItemHjindex = airbagDeploymentsTypeItemHjindex;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public Long getAirbagDeployment() {
		return this.airbagDeployment;
	}

	public void setAirbagDeployment(Long airbagDeployment) {
		this.airbagDeployment = airbagDeployment;
	}

	public Long getAirbagDeploymentsTypeItemHjid() {
		return this.airbagDeploymentsTypeItemHjid;
	}

	public void setAirbagDeploymentsTypeItemHjid(Long airbagDeploymentsTypeItemHjid) {
		this.airbagDeploymentsTypeItemHjid = airbagDeploymentsTypeItemHjid;
	}

	public Integer getAirbagDeploymentsTypeItemHjindex() {
		return this.airbagDeploymentsTypeItemHjindex;
	}

	public void setAirbagDeploymentsTypeItemHjindex(Integer airbagDeploymentsTypeItemHjindex) {
		this.airbagDeploymentsTypeItemHjindex = airbagDeploymentsTypeItemHjindex;
	}

}
