package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * ComorbidconditionstypeItemtype generated by hbm2java
 */
public class ComorbidconditionstypeItemtype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private Long comorbidCondition;
	private Long comorbidConditionsTypeItemHjid;
	private Integer comorbidConditionsTypeItemHjindex;

	public ComorbidconditionstypeItemtype() {
	}

	public ComorbidconditionstypeItemtype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public ComorbidconditionstypeItemtype(long hjid, String hjtype, long hjversion, Long comorbidCondition,
			Long comorbidConditionsTypeItemHjid, Integer comorbidConditionsTypeItemHjindex) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.comorbidCondition = comorbidCondition;
		this.comorbidConditionsTypeItemHjid = comorbidConditionsTypeItemHjid;
		this.comorbidConditionsTypeItemHjindex = comorbidConditionsTypeItemHjindex;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public Long getComorbidCondition() {
		return this.comorbidCondition;
	}

	public void setComorbidCondition(Long comorbidCondition) {
		this.comorbidCondition = comorbidCondition;
	}

	public Long getComorbidConditionsTypeItemHjid() {
		return this.comorbidConditionsTypeItemHjid;
	}

	public void setComorbidConditionsTypeItemHjid(Long comorbidConditionsTypeItemHjid) {
		this.comorbidConditionsTypeItemHjid = comorbidConditionsTypeItemHjid;
	}

	public Integer getComorbidConditionsTypeItemHjindex() {
		return this.comorbidConditionsTypeItemHjindex;
	}

	public void setComorbidConditionsTypeItemHjindex(Integer comorbidConditionsTypeItemHjindex) {
		this.comorbidConditionsTypeItemHjindex = comorbidConditionsTypeItemHjindex;
	}

}
