package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * Diagnosesicd10typeItemtype generated by hbm2java
 */
public class Diagnosesicd10typeItemtype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private Long diagnosisIcd10;
	private Long diagnosesIcd10typeItemHjid;
	private Integer diagnosesIcd10typeItemHjindex;

	public Diagnosesicd10typeItemtype() {
	}

	public Diagnosesicd10typeItemtype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public Diagnosesicd10typeItemtype(long hjid, String hjtype, long hjversion, Long diagnosisIcd10,
			Long diagnosesIcd10typeItemHjid, Integer diagnosesIcd10typeItemHjindex) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.diagnosisIcd10 = diagnosisIcd10;
		this.diagnosesIcd10typeItemHjid = diagnosesIcd10typeItemHjid;
		this.diagnosesIcd10typeItemHjindex = diagnosesIcd10typeItemHjindex;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public Long getDiagnosisIcd10() {
		return this.diagnosisIcd10;
	}

	public void setDiagnosisIcd10(Long diagnosisIcd10) {
		this.diagnosisIcd10 = diagnosisIcd10;
	}

	public Long getDiagnosesIcd10typeItemHjid() {
		return this.diagnosesIcd10typeItemHjid;
	}

	public void setDiagnosesIcd10typeItemHjid(Long diagnosesIcd10typeItemHjid) {
		this.diagnosesIcd10typeItemHjid = diagnosesIcd10typeItemHjid;
	}

	public Integer getDiagnosesIcd10typeItemHjindex() {
		return this.diagnosesIcd10typeItemHjindex;
	}

	public void setDiagnosesIcd10typeItemHjindex(Integer diagnosesIcd10typeItemHjindex) {
		this.diagnosesIcd10typeItemHjindex = diagnosesIcd10typeItemHjindex;
	}

}
