package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * DrugscreenstypeItemtype generated by hbm2java
 */
public class DrugscreenstypeItemtype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private Long drugScreen;
	private Long drugScreensTypeItemHjid;
	private Integer drugScreensTypeItemHjindex;

	public DrugscreenstypeItemtype() {
	}

	public DrugscreenstypeItemtype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public DrugscreenstypeItemtype(long hjid, String hjtype, long hjversion, Long drugScreen,
			Long drugScreensTypeItemHjid, Integer drugScreensTypeItemHjindex) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.drugScreen = drugScreen;
		this.drugScreensTypeItemHjid = drugScreensTypeItemHjid;
		this.drugScreensTypeItemHjindex = drugScreensTypeItemHjindex;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public Long getDrugScreen() {
		return this.drugScreen;
	}

	public void setDrugScreen(Long drugScreen) {
		this.drugScreen = drugScreen;
	}

	public Long getDrugScreensTypeItemHjid() {
		return this.drugScreensTypeItemHjid;
	}

	public void setDrugScreensTypeItemHjid(Long drugScreensTypeItemHjid) {
		this.drugScreensTypeItemHjid = drugScreensTypeItemHjid;
	}

	public Integer getDrugScreensTypeItemHjindex() {
		return this.drugScreensTypeItemHjindex;
	}

	public void setDrugScreensTypeItemHjindex(Integer drugScreensTypeItemHjindex) {
		this.drugScreensTypeItemHjindex = drugScreensTypeItemHjindex;
	}

}
