package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * Homestatetype generated by hbm2java
 */
public class Homestatetype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private String value;
	private String biu;

	public Homestatetype() {
	}

	public Homestatetype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public Homestatetype(long hjid, String hjtype, long hjversion, String value, String biu) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.value = value;
		this.biu = biu;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getBiu() {
		return this.biu;
	}

	public void setBiu(String biu) {
		this.biu = biu;
	}

}
