package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * Hospitaldischargedatetype generated by hbm2java
 */
public class Hospitaldischargedatetype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private String valueHjclass;
	private Long valueHjid;
	private String biu;

	public Hospitaldischargedatetype() {
	}

	public Hospitaldischargedatetype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public Hospitaldischargedatetype(long hjid, String hjtype, long hjversion, String valueHjclass, Long valueHjid,
			String biu) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.valueHjclass = valueHjclass;
		this.valueHjid = valueHjid;
		this.biu = biu;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public String getValueHjclass() {
		return this.valueHjclass;
	}

	public void setValueHjclass(String valueHjclass) {
		this.valueHjclass = valueHjclass;
	}

	public Long getValueHjid() {
		return this.valueHjid;
	}

	public void setValueHjid(Long valueHjid) {
		this.valueHjid = valueHjid;
	}

	public String getBiu() {
		return this.biu;
	}

	public void setBiu(String biu) {
		this.biu = biu;
	}

}
