package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * HospitalcomplicationstypeItemtype generated by hbm2java
 */
public class HospitalcomplicationstypeItemtype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private Long hospitalComplication;
	private Long hospitalComplicationsTypeItemHjid;
	private Integer hospitalComplicationsTypeItemHjindex;

	public HospitalcomplicationstypeItemtype() {
	}

	public HospitalcomplicationstypeItemtype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public HospitalcomplicationstypeItemtype(long hjid, String hjtype, long hjversion, Long hospitalComplication,
			Long hospitalComplicationsTypeItemHjid, Integer hospitalComplicationsTypeItemHjindex) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.hospitalComplication = hospitalComplication;
		this.hospitalComplicationsTypeItemHjid = hospitalComplicationsTypeItemHjid;
		this.hospitalComplicationsTypeItemHjindex = hospitalComplicationsTypeItemHjindex;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public Long getHospitalComplication() {
		return this.hospitalComplication;
	}

	public void setHospitalComplication(Long hospitalComplication) {
		this.hospitalComplication = hospitalComplication;
	}

	public Long getHospitalComplicationsTypeItemHjid() {
		return this.hospitalComplicationsTypeItemHjid;
	}

	public void setHospitalComplicationsTypeItemHjid(Long hospitalComplicationsTypeItemHjid) {
		this.hospitalComplicationsTypeItemHjid = hospitalComplicationsTypeItemHjid;
	}

	public Integer getHospitalComplicationsTypeItemHjindex() {
		return this.hospitalComplicationsTypeItemHjindex;
	}

	public void setHospitalComplicationsTypeItemHjindex(Integer hospitalComplicationsTypeItemHjindex) {
		this.hospitalComplicationsTypeItemHjindex = hospitalComplicationsTypeItemHjindex;
	}

}
