package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * HospitalprocedurestypeItemtype generated by hbm2java
 */
public class HospitalprocedurestypeItemtype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private Long hospitalProcedureIcd10;
	private Long hospitalProcedureStartTime;
	private Long hospitalProcedureStartDate;
	private Long hospitalProceduresTypeItemHjid;
	private Integer hospitalProceduresTypeItemHjindex;

	public HospitalprocedurestypeItemtype() {
	}

	public HospitalprocedurestypeItemtype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public HospitalprocedurestypeItemtype(long hjid, String hjtype, long hjversion, Long hospitalProcedureIcd10,
			Long hospitalProcedureStartTime, Long hospitalProcedureStartDate, Long hospitalProceduresTypeItemHjid,
			Integer hospitalProceduresTypeItemHjindex) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.hospitalProcedureIcd10 = hospitalProcedureIcd10;
		this.hospitalProcedureStartTime = hospitalProcedureStartTime;
		this.hospitalProcedureStartDate = hospitalProcedureStartDate;
		this.hospitalProceduresTypeItemHjid = hospitalProceduresTypeItemHjid;
		this.hospitalProceduresTypeItemHjindex = hospitalProceduresTypeItemHjindex;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public Long getHospitalProcedureIcd10() {
		return this.hospitalProcedureIcd10;
	}

	public void setHospitalProcedureIcd10(Long hospitalProcedureIcd10) {
		this.hospitalProcedureIcd10 = hospitalProcedureIcd10;
	}

	public Long getHospitalProcedureStartTime() {
		return this.hospitalProcedureStartTime;
	}

	public void setHospitalProcedureStartTime(Long hospitalProcedureStartTime) {
		this.hospitalProcedureStartTime = hospitalProcedureStartTime;
	}

	public Long getHospitalProcedureStartDate() {
		return this.hospitalProcedureStartDate;
	}

	public void setHospitalProcedureStartDate(Long hospitalProcedureStartDate) {
		this.hospitalProcedureStartDate = hospitalProcedureStartDate;
	}

	public Long getHospitalProceduresTypeItemHjid() {
		return this.hospitalProceduresTypeItemHjid;
	}

	public void setHospitalProceduresTypeItemHjid(Long hospitalProceduresTypeItemHjid) {
		this.hospitalProceduresTypeItemHjid = hospitalProceduresTypeItemHjid;
	}

	public Integer getHospitalProceduresTypeItemHjindex() {
		return this.hospitalProceduresTypeItemHjindex;
	}

	public void setHospitalProceduresTypeItemHjindex(Integer hospitalProceduresTypeItemHjindex) {
		this.hospitalProceduresTypeItemHjindex = hospitalProceduresTypeItemHjindex;
	}

}
