package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * HostSummaryByStatementLatency generated by hbm2java
 */
public class HostSummaryByStatementLatency implements java.io.Serializable {

	private HostSummaryByStatementLatencyId id;

	public HostSummaryByStatementLatency() {
	}

	public HostSummaryByStatementLatency(HostSummaryByStatementLatencyId id) {
		this.id = id;
	}

	public HostSummaryByStatementLatencyId getId() {
		return this.id;
	}

	public void setId(HostSummaryByStatementLatencyId id) {
		this.id = id;
	}

}
