package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * HostSummary generated by hbm2java
 */
public class HostSummary implements java.io.Serializable {

	private HostSummaryId id;

	public HostSummary() {
	}

	public HostSummary(HostSummaryId id) {
		this.id = id;
	}

	public HostSummaryId getId() {
		return this.id;
	}

	public void setId(HostSummaryId id) {
		this.id = id;
	}

}
