package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

import java.math.BigInteger;

/**
 * HostSummaryByFileIoId generated by hbm2java
 */
public class HostSummaryByFileIoId implements java.io.Serializable {

	private String host;
	private String ioLatency;
	private BigInteger ios;

	public HostSummaryByFileIoId() {
	}

	public HostSummaryByFileIoId(String host, String ioLatency, BigInteger ios) {
		this.host = host;
		this.ioLatency = ioLatency;
		this.ios = ios;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public String getIoLatency() {
		return this.ioLatency;
	}

	public void setIoLatency(String ioLatency) {
		this.ioLatency = ioLatency;
	}

	public BigInteger getIos() {
		return this.ios;
	}

	public void setIos(BigInteger ios) {
		this.ios = ios;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HostSummaryByFileIoId))
			return false;
		HostSummaryByFileIoId castOther = (HostSummaryByFileIoId) other;

		return ((this.getHost() == castOther.getHost()) || (this.getHost() != null && castOther.getHost() != null
				&& this.getHost().equals(castOther.getHost())))
				&& ((this.getIoLatency() == castOther.getIoLatency()) || (this.getIoLatency() != null
						&& castOther.getIoLatency() != null && this.getIoLatency().equals(castOther.getIoLatency())))
				&& ((this.getIos() == castOther.getIos()) || (this.getIos() != null && castOther.getIos() != null
						&& this.getIos().equals(castOther.getIos())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHost() == null ? 0 : this.getHost().hashCode());
		result = 37 * result + (getIoLatency() == null ? 0 : this.getIoLatency().hashCode());
		result = 37 * result + (getIos() == null ? 0 : this.getIos().hashCode());
		return result;
	}

}
