package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * HostSummaryByFileIoType generated by hbm2java
 */
public class HostSummaryByFileIoType implements java.io.Serializable {

	private HostSummaryByFileIoTypeId id;

	public HostSummaryByFileIoType() {
	}

	public HostSummaryByFileIoType(HostSummaryByFileIoTypeId id) {
		this.id = id;
	}

	public HostSummaryByFileIoTypeId getId() {
		return this.id;
	}

	public void setId(HostSummaryByFileIoTypeId id) {
		this.id = id;
	}

}
