package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * HostSummaryByFileIo generated by hbm2java
 */
public class HostSummaryByFileIo implements java.io.Serializable {

	private HostSummaryByFileIoId id;

	public HostSummaryByFileIo() {
	}

	public HostSummaryByFileIo(HostSummaryByFileIoId id) {
		this.id = id;
	}

	public HostSummaryByFileIoId getId() {
		return this.id;
	}

	public void setId(HostSummaryByFileIoId id) {
		this.id = id;
	}

}
