package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * HostSummaryByStatementTypeId generated by hbm2java
 */
public class HostSummaryByStatementTypeId implements java.io.Serializable {

	private String cpuLatency;
	private long fullScans;
	private String host;
	private String lockLatency;
	private String maxLatency;
	private long rowsAffected;
	private long rowsExamined;
	private long rowsSent;
	private String statement;
	private long total;
	private String totalLatency;

	public HostSummaryByStatementTypeId() {
	}

	public HostSummaryByStatementTypeId(long fullScans, long rowsAffected, long rowsExamined, long rowsSent,
			long total) {
		this.fullScans = fullScans;
		this.rowsAffected = rowsAffected;
		this.rowsExamined = rowsExamined;
		this.rowsSent = rowsSent;
		this.total = total;
	}

	public HostSummaryByStatementTypeId(String cpuLatency, long fullScans, String host, String lockLatency,
			String maxLatency, long rowsAffected, long rowsExamined, long rowsSent, String statement, long total,
			String totalLatency) {
		this.cpuLatency = cpuLatency;
		this.fullScans = fullScans;
		this.host = host;
		this.lockLatency = lockLatency;
		this.maxLatency = maxLatency;
		this.rowsAffected = rowsAffected;
		this.rowsExamined = rowsExamined;
		this.rowsSent = rowsSent;
		this.statement = statement;
		this.total = total;
		this.totalLatency = totalLatency;
	}

	public String getCpuLatency() {
		return this.cpuLatency;
	}

	public void setCpuLatency(String cpuLatency) {
		this.cpuLatency = cpuLatency;
	}

	public long getFullScans() {
		return this.fullScans;
	}

	public void setFullScans(long fullScans) {
		this.fullScans = fullScans;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public String getLockLatency() {
		return this.lockLatency;
	}

	public void setLockLatency(String lockLatency) {
		this.lockLatency = lockLatency;
	}

	public String getMaxLatency() {
		return this.maxLatency;
	}

	public void setMaxLatency(String maxLatency) {
		this.maxLatency = maxLatency;
	}

	public long getRowsAffected() {
		return this.rowsAffected;
	}

	public void setRowsAffected(long rowsAffected) {
		this.rowsAffected = rowsAffected;
	}

	public long getRowsExamined() {
		return this.rowsExamined;
	}

	public void setRowsExamined(long rowsExamined) {
		this.rowsExamined = rowsExamined;
	}

	public long getRowsSent() {
		return this.rowsSent;
	}

	public void setRowsSent(long rowsSent) {
		this.rowsSent = rowsSent;
	}

	public String getStatement() {
		return this.statement;
	}

	public void setStatement(String statement) {
		this.statement = statement;
	}

	public long getTotal() {
		return this.total;
	}

	public void setTotal(long total) {
		this.total = total;
	}

	public String getTotalLatency() {
		return this.totalLatency;
	}

	public void setTotalLatency(String totalLatency) {
		this.totalLatency = totalLatency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HostSummaryByStatementTypeId))
			return false;
		HostSummaryByStatementTypeId castOther = (HostSummaryByStatementTypeId) other;

		return ((this.getCpuLatency() == castOther.getCpuLatency()) || (this.getCpuLatency() != null
				&& castOther.getCpuLatency() != null && this.getCpuLatency().equals(castOther.getCpuLatency())))
				&& (this.getFullScans() == castOther.getFullScans())
				&& ((this.getHost() == castOther.getHost()) || (this.getHost() != null && castOther.getHost() != null
						&& this.getHost().equals(castOther.getHost())))
				&& ((this.getLockLatency() == castOther.getLockLatency())
						|| (this.getLockLatency() != null && castOther.getLockLatency() != null
								&& this.getLockLatency().equals(castOther.getLockLatency())))
				&& ((this.getMaxLatency() == castOther.getMaxLatency()) || (this.getMaxLatency() != null
						&& castOther.getMaxLatency() != null && this.getMaxLatency().equals(castOther.getMaxLatency())))
				&& (this.getRowsAffected() == castOther.getRowsAffected())
				&& (this.getRowsExamined() == castOther.getRowsExamined())
				&& (this.getRowsSent() == castOther.getRowsSent())
				&& ((this.getStatement() == castOther.getStatement()) || (this.getStatement() != null
						&& castOther.getStatement() != null && this.getStatement().equals(castOther.getStatement())))
				&& (this.getTotal() == castOther.getTotal())
				&& ((this.getTotalLatency() == castOther.getTotalLatency())
						|| (this.getTotalLatency() != null && castOther.getTotalLatency() != null
								&& this.getTotalLatency().equals(castOther.getTotalLatency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCpuLatency() == null ? 0 : this.getCpuLatency().hashCode());
		result = 37 * result + (int) this.getFullScans();
		result = 37 * result + (getHost() == null ? 0 : this.getHost().hashCode());
		result = 37 * result + (getLockLatency() == null ? 0 : this.getLockLatency().hashCode());
		result = 37 * result + (getMaxLatency() == null ? 0 : this.getMaxLatency().hashCode());
		result = 37 * result + (int) this.getRowsAffected();
		result = 37 * result + (int) this.getRowsExamined();
		result = 37 * result + (int) this.getRowsSent();
		result = 37 * result + (getStatement() == null ? 0 : this.getStatement().hashCode());
		result = 37 * result + (int) this.getTotal();
		result = 37 * result + (getTotalLatency() == null ? 0 : this.getTotalLatency().hashCode());
		return result;
	}

}
