package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * InnodbBufferStatsByTable generated by hbm2java
 */
public class InnodbBufferStatsByTable implements java.io.Serializable {

	private InnodbBufferStatsByTableId id;

	public InnodbBufferStatsByTable() {
	}

	public InnodbBufferStatsByTable(InnodbBufferStatsByTableId id) {
		this.id = id;
	}

	public InnodbBufferStatsByTableId getId() {
		return this.id;
	}

	public void setId(InnodbBufferStatsByTableId id) {
		this.id = id;
	}

}
