package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * InnodbBufferStatsBySchema generated by hbm2java
 */
public class InnodbBufferStatsBySchema implements java.io.Serializable {

	private InnodbBufferStatsBySchemaId id;

	public InnodbBufferStatsBySchema() {
	}

	public InnodbBufferStatsBySchema(InnodbBufferStatsBySchemaId id) {
		this.id = id;
	}

	public InnodbBufferStatsBySchemaId getId() {
		return this.id;
	}

	public void setId(InnodbBufferStatsBySchemaId id) {
		this.id = id;
	}

}
