package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * InnodbLockWaits generated by hbm2java
 */
public class InnodbLockWaits implements java.io.Serializable {

	private InnodbLockWaitsId id;

	public InnodbLockWaits() {
	}

	public InnodbLockWaits(InnodbLockWaitsId id) {
		this.id = id;
	}

	public InnodbLockWaitsId getId() {
		return this.id;
	}

	public void setId(InnodbLockWaitsId id) {
		this.id = id;
	}

}
