package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

import java.math.BigInteger;

/**
 * IoByThreadByLatencyId generated by hbm2java
 */
public class IoByThreadByLatencyId implements java.io.Serializable {

	private String avgLatency;
	private String maxLatency;
	private String minLatency;
	private Long processlistId;
	private long threadId;
	private BigInteger total;
	private String totalLatency;
	private String user;

	public IoByThreadByLatencyId() {
	}

	public IoByThreadByLatencyId(long threadId) {
		this.threadId = threadId;
	}

	public IoByThreadByLatencyId(String avgLatency, String maxLatency, String minLatency, Long processlistId,
			long threadId, BigInteger total, String totalLatency, String user) {
		this.avgLatency = avgLatency;
		this.maxLatency = maxLatency;
		this.minLatency = minLatency;
		this.processlistId = processlistId;
		this.threadId = threadId;
		this.total = total;
		this.totalLatency = totalLatency;
		this.user = user;
	}

	public String getAvgLatency() {
		return this.avgLatency;
	}

	public void setAvgLatency(String avgLatency) {
		this.avgLatency = avgLatency;
	}

	public String getMaxLatency() {
		return this.maxLatency;
	}

	public void setMaxLatency(String maxLatency) {
		this.maxLatency = maxLatency;
	}

	public String getMinLatency() {
		return this.minLatency;
	}

	public void setMinLatency(String minLatency) {
		this.minLatency = minLatency;
	}

	public Long getProcesslistId() {
		return this.processlistId;
	}

	public void setProcesslistId(Long processlistId) {
		this.processlistId = processlistId;
	}

	public long getThreadId() {
		return this.threadId;
	}

	public void setThreadId(long threadId) {
		this.threadId = threadId;
	}

	public BigInteger getTotal() {
		return this.total;
	}

	public void setTotal(BigInteger total) {
		this.total = total;
	}

	public String getTotalLatency() {
		return this.totalLatency;
	}

	public void setTotalLatency(String totalLatency) {
		this.totalLatency = totalLatency;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IoByThreadByLatencyId))
			return false;
		IoByThreadByLatencyId castOther = (IoByThreadByLatencyId) other;

		return ((this.getAvgLatency() == castOther.getAvgLatency()) || (this.getAvgLatency() != null
				&& castOther.getAvgLatency() != null && this.getAvgLatency().equals(castOther.getAvgLatency())))
				&& ((this.getMaxLatency() == castOther.getMaxLatency()) || (this.getMaxLatency() != null
						&& castOther.getMaxLatency() != null && this.getMaxLatency().equals(castOther.getMaxLatency())))
				&& ((this.getMinLatency() == castOther.getMinLatency()) || (this.getMinLatency() != null
						&& castOther.getMinLatency() != null && this.getMinLatency().equals(castOther.getMinLatency())))
				&& ((this.getProcesslistId() == castOther.getProcesslistId())
						|| (this.getProcesslistId() != null && castOther.getProcesslistId() != null
								&& this.getProcesslistId().equals(castOther.getProcesslistId())))
				&& (this.getThreadId() == castOther.getThreadId())
				&& ((this.getTotal() == castOther.getTotal()) || (this.getTotal() != null
						&& castOther.getTotal() != null && this.getTotal().equals(castOther.getTotal())))
				&& ((this.getTotalLatency() == castOther.getTotalLatency())
						|| (this.getTotalLatency() != null && castOther.getTotalLatency() != null
								&& this.getTotalLatency().equals(castOther.getTotalLatency())))
				&& ((this.getUser() == castOther.getUser()) || (this.getUser() != null && castOther.getUser() != null
						&& this.getUser().equals(castOther.getUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAvgLatency() == null ? 0 : this.getAvgLatency().hashCode());
		result = 37 * result + (getMaxLatency() == null ? 0 : this.getMaxLatency().hashCode());
		result = 37 * result + (getMinLatency() == null ? 0 : this.getMinLatency().hashCode());
		result = 37 * result + (getProcesslistId() == null ? 0 : this.getProcesslistId().hashCode());
		result = 37 * result + (int) this.getThreadId();
		result = 37 * result + (getTotal() == null ? 0 : this.getTotal().hashCode());
		result = 37 * result + (getTotalLatency() == null ? 0 : this.getTotalLatency().hashCode());
		result = 37 * result + (getUser() == null ? 0 : this.getUser().hashCode());
		return result;
	}

}
