package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * IoByThreadByLatency generated by hbm2java
 */
public class IoByThreadByLatency implements java.io.Serializable {

	private IoByThreadByLatencyId id;

	public IoByThreadByLatency() {
	}

	public IoByThreadByLatency(IoByThreadByLatencyId id) {
		this.id = id;
	}

	public IoByThreadByLatencyId getId() {
		return this.id;
	}

	public void setId(IoByThreadByLatencyId id) {
		this.id = id;
	}

}
