package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * IoGlobalByFileByBytes generated by hbm2java
 */
public class IoGlobalByFileByBytes implements java.io.Serializable {

	private IoGlobalByFileByBytesId id;

	public IoGlobalByFileByBytes() {
	}

	public IoGlobalByFileByBytes(IoGlobalByFileByBytesId id) {
		this.id = id;
	}

	public IoGlobalByFileByBytesId getId() {
		return this.id;
	}

	public void setId(IoGlobalByFileByBytesId id) {
		this.id = id;
	}

}
