package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * IoGlobalByWaitByLatencyId generated by hbm2java
 */
public class IoGlobalByWaitByLatencyId implements java.io.Serializable {

	private String avgLatency;
	private String avgRead;
	private String avgWritten;
	private long countRead;
	private long countWrite;
	private String eventName;
	private String maxLatency;
	private String miscLatency;
	private String readLatency;
	private long total;
	private String totalLatency;
	private String totalRead;
	private String totalWritten;
	private String writeLatency;

	public IoGlobalByWaitByLatencyId() {
	}

	public IoGlobalByWaitByLatencyId(long countRead, long countWrite, long total) {
		this.countRead = countRead;
		this.countWrite = countWrite;
		this.total = total;
	}

	public IoGlobalByWaitByLatencyId(String avgLatency, String avgRead, String avgWritten, long countRead,
			long countWrite, String eventName, String maxLatency, String miscLatency, String readLatency, long total,
			String totalLatency, String totalRead, String totalWritten, String writeLatency) {
		this.avgLatency = avgLatency;
		this.avgRead = avgRead;
		this.avgWritten = avgWritten;
		this.countRead = countRead;
		this.countWrite = countWrite;
		this.eventName = eventName;
		this.maxLatency = maxLatency;
		this.miscLatency = miscLatency;
		this.readLatency = readLatency;
		this.total = total;
		this.totalLatency = totalLatency;
		this.totalRead = totalRead;
		this.totalWritten = totalWritten;
		this.writeLatency = writeLatency;
	}

	public String getAvgLatency() {
		return this.avgLatency;
	}

	public void setAvgLatency(String avgLatency) {
		this.avgLatency = avgLatency;
	}

	public String getAvgRead() {
		return this.avgRead;
	}

	public void setAvgRead(String avgRead) {
		this.avgRead = avgRead;
	}

	public String getAvgWritten() {
		return this.avgWritten;
	}

	public void setAvgWritten(String avgWritten) {
		this.avgWritten = avgWritten;
	}

	public long getCountRead() {
		return this.countRead;
	}

	public void setCountRead(long countRead) {
		this.countRead = countRead;
	}

	public long getCountWrite() {
		return this.countWrite;
	}

	public void setCountWrite(long countWrite) {
		this.countWrite = countWrite;
	}

	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	public String getMaxLatency() {
		return this.maxLatency;
	}

	public void setMaxLatency(String maxLatency) {
		this.maxLatency = maxLatency;
	}

	public String getMiscLatency() {
		return this.miscLatency;
	}

	public void setMiscLatency(String miscLatency) {
		this.miscLatency = miscLatency;
	}

	public String getReadLatency() {
		return this.readLatency;
	}

	public void setReadLatency(String readLatency) {
		this.readLatency = readLatency;
	}

	public long getTotal() {
		return this.total;
	}

	public void setTotal(long total) {
		this.total = total;
	}

	public String getTotalLatency() {
		return this.totalLatency;
	}

	public void setTotalLatency(String totalLatency) {
		this.totalLatency = totalLatency;
	}

	public String getTotalRead() {
		return this.totalRead;
	}

	public void setTotalRead(String totalRead) {
		this.totalRead = totalRead;
	}

	public String getTotalWritten() {
		return this.totalWritten;
	}

	public void setTotalWritten(String totalWritten) {
		this.totalWritten = totalWritten;
	}

	public String getWriteLatency() {
		return this.writeLatency;
	}

	public void setWriteLatency(String writeLatency) {
		this.writeLatency = writeLatency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IoGlobalByWaitByLatencyId))
			return false;
		IoGlobalByWaitByLatencyId castOther = (IoGlobalByWaitByLatencyId) other;

		return ((this.getAvgLatency() == castOther.getAvgLatency()) || (this.getAvgLatency() != null
				&& castOther.getAvgLatency() != null && this.getAvgLatency().equals(castOther.getAvgLatency())))
				&& ((this.getAvgRead() == castOther.getAvgRead()) || (this.getAvgRead() != null
						&& castOther.getAvgRead() != null && this.getAvgRead().equals(castOther.getAvgRead())))
				&& ((this.getAvgWritten() == castOther.getAvgWritten()) || (this.getAvgWritten() != null
						&& castOther.getAvgWritten() != null && this.getAvgWritten().equals(castOther.getAvgWritten())))
				&& (this.getCountRead() == castOther.getCountRead())
				&& (this.getCountWrite() == castOther.getCountWrite())
				&& ((this.getEventName() == castOther.getEventName()) || (this.getEventName() != null
						&& castOther.getEventName() != null && this.getEventName().equals(castOther.getEventName())))
				&& ((this.getMaxLatency() == castOther.getMaxLatency()) || (this.getMaxLatency() != null
						&& castOther.getMaxLatency() != null && this.getMaxLatency().equals(castOther.getMaxLatency())))
				&& ((this.getMiscLatency() == castOther.getMiscLatency())
						|| (this.getMiscLatency() != null && castOther.getMiscLatency() != null
								&& this.getMiscLatency().equals(castOther.getMiscLatency())))
				&& ((this.getReadLatency() == castOther.getReadLatency())
						|| (this.getReadLatency() != null && castOther.getReadLatency() != null
								&& this.getReadLatency().equals(castOther.getReadLatency())))
				&& (this.getTotal() == castOther.getTotal())
				&& ((this.getTotalLatency() == castOther.getTotalLatency())
						|| (this.getTotalLatency() != null && castOther.getTotalLatency() != null
								&& this.getTotalLatency().equals(castOther.getTotalLatency())))
				&& ((this.getTotalRead() == castOther.getTotalRead()) || (this.getTotalRead() != null
						&& castOther.getTotalRead() != null && this.getTotalRead().equals(castOther.getTotalRead())))
				&& ((this.getTotalWritten() == castOther.getTotalWritten())
						|| (this.getTotalWritten() != null && castOther.getTotalWritten() != null
								&& this.getTotalWritten().equals(castOther.getTotalWritten())))
				&& ((this.getWriteLatency() == castOther.getWriteLatency())
						|| (this.getWriteLatency() != null && castOther.getWriteLatency() != null
								&& this.getWriteLatency().equals(castOther.getWriteLatency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAvgLatency() == null ? 0 : this.getAvgLatency().hashCode());
		result = 37 * result + (getAvgRead() == null ? 0 : this.getAvgRead().hashCode());
		result = 37 * result + (getAvgWritten() == null ? 0 : this.getAvgWritten().hashCode());
		result = 37 * result + (int) this.getCountRead();
		result = 37 * result + (int) this.getCountWrite();
		result = 37 * result + (getEventName() == null ? 0 : this.getEventName().hashCode());
		result = 37 * result + (getMaxLatency() == null ? 0 : this.getMaxLatency().hashCode());
		result = 37 * result + (getMiscLatency() == null ? 0 : this.getMiscLatency().hashCode());
		result = 37 * result + (getReadLatency() == null ? 0 : this.getReadLatency().hashCode());
		result = 37 * result + (int) this.getTotal();
		result = 37 * result + (getTotalLatency() == null ? 0 : this.getTotalLatency().hashCode());
		result = 37 * result + (getTotalRead() == null ? 0 : this.getTotalRead().hashCode());
		result = 37 * result + (getTotalWritten() == null ? 0 : this.getTotalWritten().hashCode());
		result = 37 * result + (getWriteLatency() == null ? 0 : this.getWriteLatency().hashCode());
		return result;
	}

}
