package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

import java.math.BigDecimal;

/**
 * IoGlobalByFileByBytesId generated by hbm2java
 */
public class IoGlobalByFileByBytesId implements java.io.Serializable {

	private String avgRead;
	private String avgWrite;
	private long countRead;
	private long countWrite;
	private String file;
	private String total;
	private String totalRead;
	private String totalWritten;
	private BigDecimal writePct;

	public IoGlobalByFileByBytesId() {
	}

	public IoGlobalByFileByBytesId(long countRead, long countWrite, BigDecimal writePct) {
		this.countRead = countRead;
		this.countWrite = countWrite;
		this.writePct = writePct;
	}

	public IoGlobalByFileByBytesId(String avgRead, String avgWrite, long countRead, long countWrite, String file,
			String total, String totalRead, String totalWritten, BigDecimal writePct) {
		this.avgRead = avgRead;
		this.avgWrite = avgWrite;
		this.countRead = countRead;
		this.countWrite = countWrite;
		this.file = file;
		this.total = total;
		this.totalRead = totalRead;
		this.totalWritten = totalWritten;
		this.writePct = writePct;
	}

	public String getAvgRead() {
		return this.avgRead;
	}

	public void setAvgRead(String avgRead) {
		this.avgRead = avgRead;
	}

	public String getAvgWrite() {
		return this.avgWrite;
	}

	public void setAvgWrite(String avgWrite) {
		this.avgWrite = avgWrite;
	}

	public long getCountRead() {
		return this.countRead;
	}

	public void setCountRead(long countRead) {
		this.countRead = countRead;
	}

	public long getCountWrite() {
		return this.countWrite;
	}

	public void setCountWrite(long countWrite) {
		this.countWrite = countWrite;
	}

	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	public String getTotal() {
		return this.total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

	public String getTotalRead() {
		return this.totalRead;
	}

	public void setTotalRead(String totalRead) {
		this.totalRead = totalRead;
	}

	public String getTotalWritten() {
		return this.totalWritten;
	}

	public void setTotalWritten(String totalWritten) {
		this.totalWritten = totalWritten;
	}

	public BigDecimal getWritePct() {
		return this.writePct;
	}

	public void setWritePct(BigDecimal writePct) {
		this.writePct = writePct;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IoGlobalByFileByBytesId))
			return false;
		IoGlobalByFileByBytesId castOther = (IoGlobalByFileByBytesId) other;

		return ((this.getAvgRead() == castOther.getAvgRead()) || (this.getAvgRead() != null
				&& castOther.getAvgRead() != null && this.getAvgRead().equals(castOther.getAvgRead())))
				&& ((this.getAvgWrite() == castOther.getAvgWrite()) || (this.getAvgWrite() != null
						&& castOther.getAvgWrite() != null && this.getAvgWrite().equals(castOther.getAvgWrite())))
				&& (this.getCountRead() == castOther.getCountRead())
				&& (this.getCountWrite() == castOther.getCountWrite())
				&& ((this.getFile() == castOther.getFile()) || (this.getFile() != null && castOther.getFile() != null
						&& this.getFile().equals(castOther.getFile())))
				&& ((this.getTotal() == castOther.getTotal()) || (this.getTotal() != null
						&& castOther.getTotal() != null && this.getTotal().equals(castOther.getTotal())))
				&& ((this.getTotalRead() == castOther.getTotalRead()) || (this.getTotalRead() != null
						&& castOther.getTotalRead() != null && this.getTotalRead().equals(castOther.getTotalRead())))
				&& ((this.getTotalWritten() == castOther.getTotalWritten())
						|| (this.getTotalWritten() != null && castOther.getTotalWritten() != null
								&& this.getTotalWritten().equals(castOther.getTotalWritten())))
				&& ((this.getWritePct() == castOther.getWritePct()) || (this.getWritePct() != null
						&& castOther.getWritePct() != null && this.getWritePct().equals(castOther.getWritePct())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAvgRead() == null ? 0 : this.getAvgRead().hashCode());
		result = 37 * result + (getAvgWrite() == null ? 0 : this.getAvgWrite().hashCode());
		result = 37 * result + (int) this.getCountRead();
		result = 37 * result + (int) this.getCountWrite();
		result = 37 * result + (getFile() == null ? 0 : this.getFile().hashCode());
		result = 37 * result + (getTotal() == null ? 0 : this.getTotal().hashCode());
		result = 37 * result + (getTotalRead() == null ? 0 : this.getTotalRead().hashCode());
		result = 37 * result + (getTotalWritten() == null ? 0 : this.getTotalWritten().hashCode());
		result = 37 * result + (getWritePct() == null ? 0 : this.getWritePct().hashCode());
		return result;
	}

}
