package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * IoGlobalByFileByLatencyId generated by hbm2java
 */
public class IoGlobalByFileByLatencyId implements java.io.Serializable {

	private long countMisc;
	private long countRead;
	private long countWrite;
	private String file;
	private String miscLatency;
	private String readLatency;
	private long total;
	private String totalLatency;
	private String writeLatency;

	public IoGlobalByFileByLatencyId() {
	}

	public IoGlobalByFileByLatencyId(long countMisc, long countRead, long countWrite, long total) {
		this.countMisc = countMisc;
		this.countRead = countRead;
		this.countWrite = countWrite;
		this.total = total;
	}

	public IoGlobalByFileByLatencyId(long countMisc, long countRead, long countWrite, String file, String miscLatency,
			String readLatency, long total, String totalLatency, String writeLatency) {
		this.countMisc = countMisc;
		this.countRead = countRead;
		this.countWrite = countWrite;
		this.file = file;
		this.miscLatency = miscLatency;
		this.readLatency = readLatency;
		this.total = total;
		this.totalLatency = totalLatency;
		this.writeLatency = writeLatency;
	}

	public long getCountMisc() {
		return this.countMisc;
	}

	public void setCountMisc(long countMisc) {
		this.countMisc = countMisc;
	}

	public long getCountRead() {
		return this.countRead;
	}

	public void setCountRead(long countRead) {
		this.countRead = countRead;
	}

	public long getCountWrite() {
		return this.countWrite;
	}

	public void setCountWrite(long countWrite) {
		this.countWrite = countWrite;
	}

	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	public String getMiscLatency() {
		return this.miscLatency;
	}

	public void setMiscLatency(String miscLatency) {
		this.miscLatency = miscLatency;
	}

	public String getReadLatency() {
		return this.readLatency;
	}

	public void setReadLatency(String readLatency) {
		this.readLatency = readLatency;
	}

	public long getTotal() {
		return this.total;
	}

	public void setTotal(long total) {
		this.total = total;
	}

	public String getTotalLatency() {
		return this.totalLatency;
	}

	public void setTotalLatency(String totalLatency) {
		this.totalLatency = totalLatency;
	}

	public String getWriteLatency() {
		return this.writeLatency;
	}

	public void setWriteLatency(String writeLatency) {
		this.writeLatency = writeLatency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IoGlobalByFileByLatencyId))
			return false;
		IoGlobalByFileByLatencyId castOther = (IoGlobalByFileByLatencyId) other;

		return (this.getCountMisc() == castOther.getCountMisc()) && (this.getCountRead() == castOther.getCountRead())
				&& (this.getCountWrite() == castOther.getCountWrite())
				&& ((this.getFile() == castOther.getFile()) || (this.getFile() != null && castOther.getFile() != null
						&& this.getFile().equals(castOther.getFile())))
				&& ((this.getMiscLatency() == castOther.getMiscLatency())
						|| (this.getMiscLatency() != null && castOther.getMiscLatency() != null
								&& this.getMiscLatency().equals(castOther.getMiscLatency())))
				&& ((this.getReadLatency() == castOther.getReadLatency())
						|| (this.getReadLatency() != null && castOther.getReadLatency() != null
								&& this.getReadLatency().equals(castOther.getReadLatency())))
				&& (this.getTotal() == castOther.getTotal())
				&& ((this.getTotalLatency() == castOther.getTotalLatency())
						|| (this.getTotalLatency() != null && castOther.getTotalLatency() != null
								&& this.getTotalLatency().equals(castOther.getTotalLatency())))
				&& ((this.getWriteLatency() == castOther.getWriteLatency())
						|| (this.getWriteLatency() != null && castOther.getWriteLatency() != null
								&& this.getWriteLatency().equals(castOther.getWriteLatency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCountMisc();
		result = 37 * result + (int) this.getCountRead();
		result = 37 * result + (int) this.getCountWrite();
		result = 37 * result + (getFile() == null ? 0 : this.getFile().hashCode());
		result = 37 * result + (getMiscLatency() == null ? 0 : this.getMiscLatency().hashCode());
		result = 37 * result + (getReadLatency() == null ? 0 : this.getReadLatency().hashCode());
		result = 37 * result + (int) this.getTotal();
		result = 37 * result + (getTotalLatency() == null ? 0 : this.getTotalLatency().hashCode());
		result = 37 * result + (getWriteLatency() == null ? 0 : this.getWriteLatency().hashCode());
		return result;
	}

}
