package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * IoGlobalByWaitByLatency generated by hbm2java
 */
public class IoGlobalByWaitByLatency implements java.io.Serializable {

	private IoGlobalByWaitByLatencyId id;

	public IoGlobalByWaitByLatency() {
	}

	public IoGlobalByWaitByLatency(IoGlobalByWaitByLatencyId id) {
		this.id = id;
	}

	public IoGlobalByWaitByLatencyId getId() {
		return this.id;
	}

	public void setId(IoGlobalByWaitByLatencyId id) {
		this.id = id;
	}

}
