package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * LatestFileIo generated by hbm2java
 */
public class LatestFileIo implements java.io.Serializable {

	private LatestFileIoId id;

	public LatestFileIo() {
	}

	public LatestFileIo(LatestFileIoId id) {
		this.id = id;
	}

	public LatestFileIoId getId() {
		return this.id;
	}

	public void setId(LatestFileIoId id) {
		this.id = id;
	}

}
