package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * MemoryGlobalByCurrentBytes generated by hbm2java
 */
public class MemoryGlobalByCurrentBytes implements java.io.Serializable {

	private MemoryGlobalByCurrentBytesId id;

	public MemoryGlobalByCurrentBytes() {
	}

	public MemoryGlobalByCurrentBytes(MemoryGlobalByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryGlobalByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryGlobalByCurrentBytesId id) {
		this.id = id;
	}

}
