package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * MemoryGlobalTotal generated by hbm2java
 */
public class MemoryGlobalTotal implements java.io.Serializable {

	private String totalAllocated;

	public MemoryGlobalTotal() {
	}

	public MemoryGlobalTotal(String totalAllocated) {
		this.totalAllocated = totalAllocated;
	}

	public String getTotalAllocated() {
		return this.totalAllocated;
	}

	public void setTotalAllocated(String totalAllocated) {
		this.totalAllocated = totalAllocated;
	}

}
