package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * MemoryByThreadByCurrentBytes generated by hbm2java
 */
public class MemoryByThreadByCurrentBytes implements java.io.Serializable {

	private MemoryByThreadByCurrentBytesId id;

	public MemoryByThreadByCurrentBytes() {
	}

	public MemoryByThreadByCurrentBytes(MemoryByThreadByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryByThreadByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByThreadByCurrentBytesId id) {
		this.id = id;
	}

}
