package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * Metrics generated by hbm2java
 */
public class Metrics implements java.io.Serializable {

	private MetricsId id;

	public Metrics() {
	}

	public Metrics(MetricsId id) {
		this.id = id;
	}

	public MetricsId getId() {
		return this.id;
	}

	public void setId(MetricsId id) {
		this.id = id;
	}

}
