package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * OthertransportmodestypeItemtype generated by hbm2java
 */
public class OthertransportmodestypeItemtype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private Long otherTransportMode;
	private Long otherTransportModesTypeItemHjid;
	private Integer otherTransportModesTypeItemHjindex;

	public OthertransportmodestypeItemtype() {
	}

	public OthertransportmodestypeItemtype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public OthertransportmodestypeItemtype(long hjid, String hjtype, long hjversion, Long otherTransportMode,
			Long otherTransportModesTypeItemHjid, Integer otherTransportModesTypeItemHjindex) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.otherTransportMode = otherTransportMode;
		this.otherTransportModesTypeItemHjid = otherTransportModesTypeItemHjid;
		this.otherTransportModesTypeItemHjindex = otherTransportModesTypeItemHjindex;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public Long getOtherTransportMode() {
		return this.otherTransportMode;
	}

	public void setOtherTransportMode(Long otherTransportMode) {
		this.otherTransportMode = otherTransportMode;
	}

	public Long getOtherTransportModesTypeItemHjid() {
		return this.otherTransportModesTypeItemHjid;
	}

	public void setOtherTransportModesTypeItemHjid(Long otherTransportModesTypeItemHjid) {
		this.otherTransportModesTypeItemHjid = otherTransportModesTypeItemHjid;
	}

	public Integer getOtherTransportModesTypeItemHjindex() {
		return this.otherTransportModesTypeItemHjindex;
	}

	public void setOtherTransportModesTypeItemHjindex(Integer otherTransportModesTypeItemHjindex) {
		this.otherTransportModesTypeItemHjindex = otherTransportModesTypeItemHjindex;
	}

}
