package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * Processlist generated by hbm2java
 */
public class Processlist implements java.io.Serializable {

	private ProcesslistId id;

	public Processlist() {
	}

	public Processlist(ProcesslistId id) {
		this.id = id;
	}

	public ProcesslistId getId() {
		return this.id;
	}

	public void setId(ProcesslistId id) {
		this.id = id;
	}

}
