package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * ProtectivedevicestypeItemtype generated by hbm2java
 */
public class ProtectivedevicestypeItemtype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private Long protectiveDevice;
	private Long protectiveDevicesTypeItemHjid;
	private Integer protectiveDevicesTypeItemHjindex;

	public ProtectivedevicestypeItemtype() {
	}

	public ProtectivedevicestypeItemtype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public ProtectivedevicestypeItemtype(long hjid, String hjtype, long hjversion, Long protectiveDevice,
			Long protectiveDevicesTypeItemHjid, Integer protectiveDevicesTypeItemHjindex) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.protectiveDevice = protectiveDevice;
		this.protectiveDevicesTypeItemHjid = protectiveDevicesTypeItemHjid;
		this.protectiveDevicesTypeItemHjindex = protectiveDevicesTypeItemHjindex;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public Long getProtectiveDevice() {
		return this.protectiveDevice;
	}

	public void setProtectiveDevice(Long protectiveDevice) {
		this.protectiveDevice = protectiveDevice;
	}

	public Long getProtectiveDevicesTypeItemHjid() {
		return this.protectiveDevicesTypeItemHjid;
	}

	public void setProtectiveDevicesTypeItemHjid(Long protectiveDevicesTypeItemHjid) {
		this.protectiveDevicesTypeItemHjid = protectiveDevicesTypeItemHjid;
	}

	public Integer getProtectiveDevicesTypeItemHjindex() {
		return this.protectiveDevicesTypeItemHjindex;
	}

	public void setProtectiveDevicesTypeItemHjindex(Integer protectiveDevicesTypeItemHjindex) {
		this.protectiveDevicesTypeItemHjindex = protectiveDevicesTypeItemHjindex;
	}

}
