package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * PsCheckLostInstrumentation generated by hbm2java
 */
public class PsCheckLostInstrumentation implements java.io.Serializable {

	private PsCheckLostInstrumentationId id;

	public PsCheckLostInstrumentation() {
	}

	public PsCheckLostInstrumentation(PsCheckLostInstrumentationId id) {
		this.id = id;
	}

	public PsCheckLostInstrumentationId getId() {
		return this.id;
	}

	public void setId(PsCheckLostInstrumentationId id) {
		this.id = id;
	}

}
