package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * RacestypeItemtype generated by hbm2java
 */
public class RacestypeItemtype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private Long race;
	private Long racesTypeItemHjid;
	private Integer racesTypeItemHjindex;

	public RacestypeItemtype() {
	}

	public RacestypeItemtype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public RacestypeItemtype(long hjid, String hjtype, long hjversion, Long race, Long racesTypeItemHjid,
			Integer racesTypeItemHjindex) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.race = race;
		this.racesTypeItemHjid = racesTypeItemHjid;
		this.racesTypeItemHjindex = racesTypeItemHjindex;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public Long getRace() {
		return this.race;
	}

	public void setRace(Long race) {
		this.race = race;
	}

	public Long getRacesTypeItemHjid() {
		return this.racesTypeItemHjid;
	}

	public void setRacesTypeItemHjid(Long racesTypeItemHjid) {
		this.racesTypeItemHjid = racesTypeItemHjid;
	}

	public Integer getRacesTypeItemHjindex() {
		return this.racesTypeItemHjindex;
	}

	public void setRacesTypeItemHjindex(Integer racesTypeItemHjindex) {
		this.racesTypeItemHjindex = racesTypeItemHjindex;
	}

}
