package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * SchemaIndexStatisticsId generated by hbm2java
 */
public class SchemaIndexStatisticsId implements java.io.Serializable {

	private String deleteLatency;
	private String indexName;
	private String insertLatency;
	private long rowsDeleted;
	private long rowsInserted;
	private long rowsSelected;
	private long rowsUpdated;
	private String selectLatency;
	private String tableName;
	private String tableSchema;
	private String updateLatency;

	public SchemaIndexStatisticsId() {
	}

	public SchemaIndexStatisticsId(long rowsDeleted, long rowsInserted, long rowsSelected, long rowsUpdated) {
		this.rowsDeleted = rowsDeleted;
		this.rowsInserted = rowsInserted;
		this.rowsSelected = rowsSelected;
		this.rowsUpdated = rowsUpdated;
	}

	public SchemaIndexStatisticsId(String deleteLatency, String indexName, String insertLatency, long rowsDeleted,
			long rowsInserted, long rowsSelected, long rowsUpdated, String selectLatency, String tableName,
			String tableSchema, String updateLatency) {
		this.deleteLatency = deleteLatency;
		this.indexName = indexName;
		this.insertLatency = insertLatency;
		this.rowsDeleted = rowsDeleted;
		this.rowsInserted = rowsInserted;
		this.rowsSelected = rowsSelected;
		this.rowsUpdated = rowsUpdated;
		this.selectLatency = selectLatency;
		this.tableName = tableName;
		this.tableSchema = tableSchema;
		this.updateLatency = updateLatency;
	}

	public String getDeleteLatency() {
		return this.deleteLatency;
	}

	public void setDeleteLatency(String deleteLatency) {
		this.deleteLatency = deleteLatency;
	}

	public String getIndexName() {
		return this.indexName;
	}

	public void setIndexName(String indexName) {
		this.indexName = indexName;
	}

	public String getInsertLatency() {
		return this.insertLatency;
	}

	public void setInsertLatency(String insertLatency) {
		this.insertLatency = insertLatency;
	}

	public long getRowsDeleted() {
		return this.rowsDeleted;
	}

	public void setRowsDeleted(long rowsDeleted) {
		this.rowsDeleted = rowsDeleted;
	}

	public long getRowsInserted() {
		return this.rowsInserted;
	}

	public void setRowsInserted(long rowsInserted) {
		this.rowsInserted = rowsInserted;
	}

	public long getRowsSelected() {
		return this.rowsSelected;
	}

	public void setRowsSelected(long rowsSelected) {
		this.rowsSelected = rowsSelected;
	}

	public long getRowsUpdated() {
		return this.rowsUpdated;
	}

	public void setRowsUpdated(long rowsUpdated) {
		this.rowsUpdated = rowsUpdated;
	}

	public String getSelectLatency() {
		return this.selectLatency;
	}

	public void setSelectLatency(String selectLatency) {
		this.selectLatency = selectLatency;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getTableSchema() {
		return this.tableSchema;
	}

	public void setTableSchema(String tableSchema) {
		this.tableSchema = tableSchema;
	}

	public String getUpdateLatency() {
		return this.updateLatency;
	}

	public void setUpdateLatency(String updateLatency) {
		this.updateLatency = updateLatency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchemaIndexStatisticsId))
			return false;
		SchemaIndexStatisticsId castOther = (SchemaIndexStatisticsId) other;

		return ((this.getDeleteLatency() == castOther.getDeleteLatency())
				|| (this.getDeleteLatency() != null && castOther.getDeleteLatency() != null
						&& this.getDeleteLatency().equals(castOther.getDeleteLatency())))
				&& ((this.getIndexName() == castOther.getIndexName()) || (this.getIndexName() != null
						&& castOther.getIndexName() != null && this.getIndexName().equals(castOther.getIndexName())))
				&& ((this.getInsertLatency() == castOther.getInsertLatency())
						|| (this.getInsertLatency() != null && castOther.getInsertLatency() != null
								&& this.getInsertLatency().equals(castOther.getInsertLatency())))
				&& (this.getRowsDeleted() == castOther.getRowsDeleted())
				&& (this.getRowsInserted() == castOther.getRowsInserted())
				&& (this.getRowsSelected() == castOther.getRowsSelected())
				&& (this.getRowsUpdated() == castOther.getRowsUpdated())
				&& ((this.getSelectLatency() == castOther.getSelectLatency())
						|| (this.getSelectLatency() != null && castOther.getSelectLatency() != null
								&& this.getSelectLatency().equals(castOther.getSelectLatency())))
				&& ((this.getTableName() == castOther.getTableName()) || (this.getTableName() != null
						&& castOther.getTableName() != null && this.getTableName().equals(castOther.getTableName())))
				&& ((this.getTableSchema() == castOther.getTableSchema())
						|| (this.getTableSchema() != null && castOther.getTableSchema() != null
								&& this.getTableSchema().equals(castOther.getTableSchema())))
				&& ((this.getUpdateLatency() == castOther.getUpdateLatency())
						|| (this.getUpdateLatency() != null && castOther.getUpdateLatency() != null
								&& this.getUpdateLatency().equals(castOther.getUpdateLatency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeleteLatency() == null ? 0 : this.getDeleteLatency().hashCode());
		result = 37 * result + (getIndexName() == null ? 0 : this.getIndexName().hashCode());
		result = 37 * result + (getInsertLatency() == null ? 0 : this.getInsertLatency().hashCode());
		result = 37 * result + (int) this.getRowsDeleted();
		result = 37 * result + (int) this.getRowsInserted();
		result = 37 * result + (int) this.getRowsSelected();
		result = 37 * result + (int) this.getRowsUpdated();
		result = 37 * result + (getSelectLatency() == null ? 0 : this.getSelectLatency().hashCode());
		result = 37 * result + (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result + (getTableSchema() == null ? 0 : this.getTableSchema().hashCode());
		result = 37 * result + (getUpdateLatency() == null ? 0 : this.getUpdateLatency().hashCode());
		return result;
	}

}
