package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

import java.math.BigInteger;

/**
 * SchemaTableStatisticsId generated by hbm2java
 */
public class SchemaTableStatisticsId implements java.io.Serializable {

	private String deleteLatency;
	private String fetchLatency;
	private String insertLatency;
	private String ioMiscLatency;
	private BigInteger ioMiscRequests;
	private String ioRead;
	private String ioReadLatency;
	private BigInteger ioReadRequests;
	private String ioWrite;
	private String ioWriteLatency;
	private BigInteger ioWriteRequests;
	private long rowsDeleted;
	private long rowsFetched;
	private long rowsInserted;
	private long rowsUpdated;
	private String tableName;
	private String tableSchema;
	private String totalLatency;
	private String updateLatency;

	public SchemaTableStatisticsId() {
	}

	public SchemaTableStatisticsId(long rowsDeleted, long rowsFetched, long rowsInserted, long rowsUpdated) {
		this.rowsDeleted = rowsDeleted;
		this.rowsFetched = rowsFetched;
		this.rowsInserted = rowsInserted;
		this.rowsUpdated = rowsUpdated;
	}

	public SchemaTableStatisticsId(String deleteLatency, String fetchLatency, String insertLatency,
			String ioMiscLatency, BigInteger ioMiscRequests, String ioRead, String ioReadLatency,
			BigInteger ioReadRequests, String ioWrite, String ioWriteLatency, BigInteger ioWriteRequests,
			long rowsDeleted, long rowsFetched, long rowsInserted, long rowsUpdated, String tableName,
			String tableSchema, String totalLatency, String updateLatency) {
		this.deleteLatency = deleteLatency;
		this.fetchLatency = fetchLatency;
		this.insertLatency = insertLatency;
		this.ioMiscLatency = ioMiscLatency;
		this.ioMiscRequests = ioMiscRequests;
		this.ioRead = ioRead;
		this.ioReadLatency = ioReadLatency;
		this.ioReadRequests = ioReadRequests;
		this.ioWrite = ioWrite;
		this.ioWriteLatency = ioWriteLatency;
		this.ioWriteRequests = ioWriteRequests;
		this.rowsDeleted = rowsDeleted;
		this.rowsFetched = rowsFetched;
		this.rowsInserted = rowsInserted;
		this.rowsUpdated = rowsUpdated;
		this.tableName = tableName;
		this.tableSchema = tableSchema;
		this.totalLatency = totalLatency;
		this.updateLatency = updateLatency;
	}

	public String getDeleteLatency() {
		return this.deleteLatency;
	}

	public void setDeleteLatency(String deleteLatency) {
		this.deleteLatency = deleteLatency;
	}

	public String getFetchLatency() {
		return this.fetchLatency;
	}

	public void setFetchLatency(String fetchLatency) {
		this.fetchLatency = fetchLatency;
	}

	public String getInsertLatency() {
		return this.insertLatency;
	}

	public void setInsertLatency(String insertLatency) {
		this.insertLatency = insertLatency;
	}

	public String getIoMiscLatency() {
		return this.ioMiscLatency;
	}

	public void setIoMiscLatency(String ioMiscLatency) {
		this.ioMiscLatency = ioMiscLatency;
	}

	public BigInteger getIoMiscRequests() {
		return this.ioMiscRequests;
	}

	public void setIoMiscRequests(BigInteger ioMiscRequests) {
		this.ioMiscRequests = ioMiscRequests;
	}

	public String getIoRead() {
		return this.ioRead;
	}

	public void setIoRead(String ioRead) {
		this.ioRead = ioRead;
	}

	public String getIoReadLatency() {
		return this.ioReadLatency;
	}

	public void setIoReadLatency(String ioReadLatency) {
		this.ioReadLatency = ioReadLatency;
	}

	public BigInteger getIoReadRequests() {
		return this.ioReadRequests;
	}

	public void setIoReadRequests(BigInteger ioReadRequests) {
		this.ioReadRequests = ioReadRequests;
	}

	public String getIoWrite() {
		return this.ioWrite;
	}

	public void setIoWrite(String ioWrite) {
		this.ioWrite = ioWrite;
	}

	public String getIoWriteLatency() {
		return this.ioWriteLatency;
	}

	public void setIoWriteLatency(String ioWriteLatency) {
		this.ioWriteLatency = ioWriteLatency;
	}

	public BigInteger getIoWriteRequests() {
		return this.ioWriteRequests;
	}

	public void setIoWriteRequests(BigInteger ioWriteRequests) {
		this.ioWriteRequests = ioWriteRequests;
	}

	public long getRowsDeleted() {
		return this.rowsDeleted;
	}

	public void setRowsDeleted(long rowsDeleted) {
		this.rowsDeleted = rowsDeleted;
	}

	public long getRowsFetched() {
		return this.rowsFetched;
	}

	public void setRowsFetched(long rowsFetched) {
		this.rowsFetched = rowsFetched;
	}

	public long getRowsInserted() {
		return this.rowsInserted;
	}

	public void setRowsInserted(long rowsInserted) {
		this.rowsInserted = rowsInserted;
	}

	public long getRowsUpdated() {
		return this.rowsUpdated;
	}

	public void setRowsUpdated(long rowsUpdated) {
		this.rowsUpdated = rowsUpdated;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getTableSchema() {
		return this.tableSchema;
	}

	public void setTableSchema(String tableSchema) {
		this.tableSchema = tableSchema;
	}

	public String getTotalLatency() {
		return this.totalLatency;
	}

	public void setTotalLatency(String totalLatency) {
		this.totalLatency = totalLatency;
	}

	public String getUpdateLatency() {
		return this.updateLatency;
	}

	public void setUpdateLatency(String updateLatency) {
		this.updateLatency = updateLatency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchemaTableStatisticsId))
			return false;
		SchemaTableStatisticsId castOther = (SchemaTableStatisticsId) other;

		return ((this.getDeleteLatency() == castOther.getDeleteLatency())
				|| (this.getDeleteLatency() != null && castOther.getDeleteLatency() != null
						&& this.getDeleteLatency().equals(castOther.getDeleteLatency())))
				&& ((this.getFetchLatency() == castOther.getFetchLatency())
						|| (this.getFetchLatency() != null && castOther.getFetchLatency() != null
								&& this.getFetchLatency().equals(castOther.getFetchLatency())))
				&& ((this.getInsertLatency() == castOther.getInsertLatency())
						|| (this.getInsertLatency() != null && castOther.getInsertLatency() != null
								&& this.getInsertLatency().equals(castOther.getInsertLatency())))
				&& ((this.getIoMiscLatency() == castOther.getIoMiscLatency())
						|| (this.getIoMiscLatency() != null && castOther.getIoMiscLatency() != null
								&& this.getIoMiscLatency().equals(castOther.getIoMiscLatency())))
				&& ((this.getIoMiscRequests() == castOther.getIoMiscRequests())
						|| (this.getIoMiscRequests() != null && castOther.getIoMiscRequests() != null
								&& this.getIoMiscRequests().equals(castOther.getIoMiscRequests())))
				&& ((this.getIoRead() == castOther.getIoRead()) || (this.getIoRead() != null
						&& castOther.getIoRead() != null && this.getIoRead().equals(castOther.getIoRead())))
				&& ((this.getIoReadLatency() == castOther.getIoReadLatency())
						|| (this.getIoReadLatency() != null && castOther.getIoReadLatency() != null
								&& this.getIoReadLatency().equals(castOther.getIoReadLatency())))
				&& ((this.getIoReadRequests() == castOther.getIoReadRequests())
						|| (this.getIoReadRequests() != null && castOther.getIoReadRequests() != null
								&& this.getIoReadRequests().equals(castOther.getIoReadRequests())))
				&& ((this.getIoWrite() == castOther.getIoWrite()) || (this.getIoWrite() != null
						&& castOther.getIoWrite() != null && this.getIoWrite().equals(castOther.getIoWrite())))
				&& ((this.getIoWriteLatency() == castOther.getIoWriteLatency())
						|| (this.getIoWriteLatency() != null && castOther.getIoWriteLatency() != null
								&& this.getIoWriteLatency().equals(castOther.getIoWriteLatency())))
				&& ((this.getIoWriteRequests() == castOther.getIoWriteRequests())
						|| (this.getIoWriteRequests() != null && castOther.getIoWriteRequests() != null
								&& this.getIoWriteRequests().equals(castOther.getIoWriteRequests())))
				&& (this.getRowsDeleted() == castOther.getRowsDeleted())
				&& (this.getRowsFetched() == castOther.getRowsFetched())
				&& (this.getRowsInserted() == castOther.getRowsInserted())
				&& (this.getRowsUpdated() == castOther.getRowsUpdated())
				&& ((this.getTableName() == castOther.getTableName()) || (this.getTableName() != null
						&& castOther.getTableName() != null && this.getTableName().equals(castOther.getTableName())))
				&& ((this.getTableSchema() == castOther.getTableSchema())
						|| (this.getTableSchema() != null && castOther.getTableSchema() != null
								&& this.getTableSchema().equals(castOther.getTableSchema())))
				&& ((this.getTotalLatency() == castOther.getTotalLatency())
						|| (this.getTotalLatency() != null && castOther.getTotalLatency() != null
								&& this.getTotalLatency().equals(castOther.getTotalLatency())))
				&& ((this.getUpdateLatency() == castOther.getUpdateLatency())
						|| (this.getUpdateLatency() != null && castOther.getUpdateLatency() != null
								&& this.getUpdateLatency().equals(castOther.getUpdateLatency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeleteLatency() == null ? 0 : this.getDeleteLatency().hashCode());
		result = 37 * result + (getFetchLatency() == null ? 0 : this.getFetchLatency().hashCode());
		result = 37 * result + (getInsertLatency() == null ? 0 : this.getInsertLatency().hashCode());
		result = 37 * result + (getIoMiscLatency() == null ? 0 : this.getIoMiscLatency().hashCode());
		result = 37 * result + (getIoMiscRequests() == null ? 0 : this.getIoMiscRequests().hashCode());
		result = 37 * result + (getIoRead() == null ? 0 : this.getIoRead().hashCode());
		result = 37 * result + (getIoReadLatency() == null ? 0 : this.getIoReadLatency().hashCode());
		result = 37 * result + (getIoReadRequests() == null ? 0 : this.getIoReadRequests().hashCode());
		result = 37 * result + (getIoWrite() == null ? 0 : this.getIoWrite().hashCode());
		result = 37 * result + (getIoWriteLatency() == null ? 0 : this.getIoWriteLatency().hashCode());
		result = 37 * result + (getIoWriteRequests() == null ? 0 : this.getIoWriteRequests().hashCode());
		result = 37 * result + (int) this.getRowsDeleted();
		result = 37 * result + (int) this.getRowsFetched();
		result = 37 * result + (int) this.getRowsInserted();
		result = 37 * result + (int) this.getRowsUpdated();
		result = 37 * result + (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result + (getTableSchema() == null ? 0 : this.getTableSchema().hashCode());
		result = 37 * result + (getTotalLatency() == null ? 0 : this.getTotalLatency().hashCode());
		result = 37 * result + (getUpdateLatency() == null ? 0 : this.getUpdateLatency().hashCode());
		return result;
	}

}
