package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * SchemaObjectOverviewId generated by hbm2java
 */
public class SchemaObjectOverviewId implements java.io.Serializable {

	private long count;
	private String db;
	private String objectType;

	public SchemaObjectOverviewId() {
	}

	public SchemaObjectOverviewId(long count) {
		this.count = count;
	}

	public SchemaObjectOverviewId(long count, String db, String objectType) {
		this.count = count;
		this.db = db;
		this.objectType = objectType;
	}

	public long getCount() {
		return this.count;
	}

	public void setCount(long count) {
		this.count = count;
	}

	public String getDb() {
		return this.db;
	}

	public void setDb(String db) {
		this.db = db;
	}

	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchemaObjectOverviewId))
			return false;
		SchemaObjectOverviewId castOther = (SchemaObjectOverviewId) other;

		return (this.getCount() == castOther.getCount()) && ((this.getDb() == castOther.getDb())
				|| (this.getDb() != null && castOther.getDb() != null && this.getDb().equals(castOther.getDb())))
				&& ((this.getObjectType() == castOther.getObjectType())
						|| (this.getObjectType() != null && castOther.getObjectType() != null
								&& this.getObjectType().equals(castOther.getObjectType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCount();
		result = 37 * result + (getDb() == null ? 0 : this.getDb().hashCode());
		result = 37 * result + (getObjectType() == null ? 0 : this.getObjectType().hashCode());
		return result;
	}

}
