package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * SchemaRedundantIndexes generated by hbm2java
 */
public class SchemaRedundantIndexes implements java.io.Serializable {

	private SchemaRedundantIndexesId id;

	public SchemaRedundantIndexes() {
	}

	public SchemaRedundantIndexes(SchemaRedundantIndexesId id) {
		this.id = id;
	}

	public SchemaRedundantIndexesId getId() {
		return this.id;
	}

	public void setId(SchemaRedundantIndexesId id) {
		this.id = id;
	}

}
