package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * SchemaIndexStatistics generated by hbm2java
 */
public class SchemaIndexStatistics implements java.io.Serializable {

	private SchemaIndexStatisticsId id;

	public SchemaIndexStatistics() {
	}

	public SchemaIndexStatistics(SchemaIndexStatisticsId id) {
		this.id = id;
	}

	public SchemaIndexStatisticsId getId() {
		return this.id;
	}

	public void setId(SchemaIndexStatisticsId id) {
		this.id = id;
	}

}
