package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * SchemaRedundantIndexesId generated by hbm2java
 */
public class SchemaRedundantIndexesId implements java.io.Serializable {

	private String dominantIndexColumns;
	private String dominantIndexName;
	private Integer dominantIndexNonUnique;
	private String redundantIndexColumns;
	private String redundantIndexName;
	private Integer redundantIndexNonUnique;
	private String sqlDropIndex;
	private int subpartExists;
	private String tableName;
	private String tableSchema;

	public SchemaRedundantIndexesId() {
	}

	public SchemaRedundantIndexesId(int subpartExists) {
		this.subpartExists = subpartExists;
	}

	public SchemaRedundantIndexesId(String dominantIndexColumns, String dominantIndexName,
			Integer dominantIndexNonUnique, String redundantIndexColumns, String redundantIndexName,
			Integer redundantIndexNonUnique, String sqlDropIndex, int subpartExists, String tableName,
			String tableSchema) {
		this.dominantIndexColumns = dominantIndexColumns;
		this.dominantIndexName = dominantIndexName;
		this.dominantIndexNonUnique = dominantIndexNonUnique;
		this.redundantIndexColumns = redundantIndexColumns;
		this.redundantIndexName = redundantIndexName;
		this.redundantIndexNonUnique = redundantIndexNonUnique;
		this.sqlDropIndex = sqlDropIndex;
		this.subpartExists = subpartExists;
		this.tableName = tableName;
		this.tableSchema = tableSchema;
	}

	public String getDominantIndexColumns() {
		return this.dominantIndexColumns;
	}

	public void setDominantIndexColumns(String dominantIndexColumns) {
		this.dominantIndexColumns = dominantIndexColumns;
	}

	public String getDominantIndexName() {
		return this.dominantIndexName;
	}

	public void setDominantIndexName(String dominantIndexName) {
		this.dominantIndexName = dominantIndexName;
	}

	public Integer getDominantIndexNonUnique() {
		return this.dominantIndexNonUnique;
	}

	public void setDominantIndexNonUnique(Integer dominantIndexNonUnique) {
		this.dominantIndexNonUnique = dominantIndexNonUnique;
	}

	public String getRedundantIndexColumns() {
		return this.redundantIndexColumns;
	}

	public void setRedundantIndexColumns(String redundantIndexColumns) {
		this.redundantIndexColumns = redundantIndexColumns;
	}

	public String getRedundantIndexName() {
		return this.redundantIndexName;
	}

	public void setRedundantIndexName(String redundantIndexName) {
		this.redundantIndexName = redundantIndexName;
	}

	public Integer getRedundantIndexNonUnique() {
		return this.redundantIndexNonUnique;
	}

	public void setRedundantIndexNonUnique(Integer redundantIndexNonUnique) {
		this.redundantIndexNonUnique = redundantIndexNonUnique;
	}

	public String getSqlDropIndex() {
		return this.sqlDropIndex;
	}

	public void setSqlDropIndex(String sqlDropIndex) {
		this.sqlDropIndex = sqlDropIndex;
	}

	public int getSubpartExists() {
		return this.subpartExists;
	}

	public void setSubpartExists(int subpartExists) {
		this.subpartExists = subpartExists;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getTableSchema() {
		return this.tableSchema;
	}

	public void setTableSchema(String tableSchema) {
		this.tableSchema = tableSchema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchemaRedundantIndexesId))
			return false;
		SchemaRedundantIndexesId castOther = (SchemaRedundantIndexesId) other;

		return ((this.getDominantIndexColumns() == castOther.getDominantIndexColumns())
				|| (this.getDominantIndexColumns() != null && castOther.getDominantIndexColumns() != null
						&& this.getDominantIndexColumns().equals(castOther.getDominantIndexColumns())))
				&& ((this.getDominantIndexName() == castOther.getDominantIndexName())
						|| (this.getDominantIndexName() != null && castOther.getDominantIndexName() != null
								&& this.getDominantIndexName().equals(castOther.getDominantIndexName())))
				&& ((this.getDominantIndexNonUnique() == castOther.getDominantIndexNonUnique())
						|| (this.getDominantIndexNonUnique() != null && castOther.getDominantIndexNonUnique() != null
								&& this.getDominantIndexNonUnique().equals(castOther.getDominantIndexNonUnique())))
				&& ((this.getRedundantIndexColumns() == castOther.getRedundantIndexColumns())
						|| (this.getRedundantIndexColumns() != null && castOther.getRedundantIndexColumns() != null
								&& this.getRedundantIndexColumns().equals(castOther.getRedundantIndexColumns())))
				&& ((this.getRedundantIndexName() == castOther.getRedundantIndexName())
						|| (this.getRedundantIndexName() != null && castOther.getRedundantIndexName() != null
								&& this.getRedundantIndexName().equals(castOther.getRedundantIndexName())))
				&& ((this.getRedundantIndexNonUnique() == castOther.getRedundantIndexNonUnique())
						|| (this.getRedundantIndexNonUnique() != null && castOther.getRedundantIndexNonUnique() != null
								&& this.getRedundantIndexNonUnique().equals(castOther.getRedundantIndexNonUnique())))
				&& ((this.getSqlDropIndex() == castOther.getSqlDropIndex())
						|| (this.getSqlDropIndex() != null && castOther.getSqlDropIndex() != null
								&& this.getSqlDropIndex().equals(castOther.getSqlDropIndex())))
				&& (this.getSubpartExists() == castOther.getSubpartExists())
				&& ((this.getTableName() == castOther.getTableName()) || (this.getTableName() != null
						&& castOther.getTableName() != null && this.getTableName().equals(castOther.getTableName())))
				&& ((this.getTableSchema() == castOther.getTableSchema())
						|| (this.getTableSchema() != null && castOther.getTableSchema() != null
								&& this.getTableSchema().equals(castOther.getTableSchema())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDominantIndexColumns() == null ? 0 : this.getDominantIndexColumns().hashCode());
		result = 37 * result + (getDominantIndexName() == null ? 0 : this.getDominantIndexName().hashCode());
		result = 37 * result + (getDominantIndexNonUnique() == null ? 0 : this.getDominantIndexNonUnique().hashCode());
		result = 37 * result + (getRedundantIndexColumns() == null ? 0 : this.getRedundantIndexColumns().hashCode());
		result = 37 * result + (getRedundantIndexName() == null ? 0 : this.getRedundantIndexName().hashCode());
		result = 37 * result
				+ (getRedundantIndexNonUnique() == null ? 0 : this.getRedundantIndexNonUnique().hashCode());
		result = 37 * result + (getSqlDropIndex() == null ? 0 : this.getSqlDropIndex().hashCode());
		result = 37 * result + this.getSubpartExists();
		result = 37 * result + (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result + (getTableSchema() == null ? 0 : this.getTableSchema().hashCode());
		return result;
	}

}
