package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * SchemaUnusedIndexes generated by hbm2java
 */
public class SchemaUnusedIndexes implements java.io.Serializable {

	private SchemaUnusedIndexesId id;

	public SchemaUnusedIndexes() {
	}

	public SchemaUnusedIndexes(SchemaUnusedIndexesId id) {
		this.id = id;
	}

	public SchemaUnusedIndexesId getId() {
		return this.id;
	}

	public void setId(SchemaUnusedIndexesId id) {
		this.id = id;
	}

}
