package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * SchemaTablesWithFullTableScans generated by hbm2java
 */
public class SchemaTablesWithFullTableScans implements java.io.Serializable {

	private SchemaTablesWithFullTableScansId id;

	public SchemaTablesWithFullTableScans() {
	}

	public SchemaTablesWithFullTableScans(SchemaTablesWithFullTableScansId id) {
		this.id = id;
	}

	public SchemaTablesWithFullTableScansId getId() {
		return this.id;
	}

	public void setId(SchemaTablesWithFullTableScansId id) {
		this.id = id;
	}

}
