package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * SchemaAutoIncrementColumns generated by hbm2java
 */
public class SchemaAutoIncrementColumns implements java.io.Serializable {

	private SchemaAutoIncrementColumnsId id;

	public SchemaAutoIncrementColumns() {
	}

	public SchemaAutoIncrementColumns(SchemaAutoIncrementColumnsId id) {
		this.id = id;
	}

	public SchemaAutoIncrementColumnsId getId() {
		return this.id;
	}

	public void setId(SchemaAutoIncrementColumnsId id) {
		this.id = id;
	}

}
