package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * SchemaUnusedIndexesId generated by hbm2java
 */
public class SchemaUnusedIndexesId implements java.io.Serializable {

	private String indexName;
	private String objectName;
	private String objectSchema;

	public SchemaUnusedIndexesId() {
	}

	public SchemaUnusedIndexesId(String indexName, String objectName, String objectSchema) {
		this.indexName = indexName;
		this.objectName = objectName;
		this.objectSchema = objectSchema;
	}

	public String getIndexName() {
		return this.indexName;
	}

	public void setIndexName(String indexName) {
		this.indexName = indexName;
	}

	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	public String getObjectSchema() {
		return this.objectSchema;
	}

	public void setObjectSchema(String objectSchema) {
		this.objectSchema = objectSchema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchemaUnusedIndexesId))
			return false;
		SchemaUnusedIndexesId castOther = (SchemaUnusedIndexesId) other;

		return ((this.getIndexName() == castOther.getIndexName()) || (this.getIndexName() != null
				&& castOther.getIndexName() != null && this.getIndexName().equals(castOther.getIndexName())))
				&& ((this.getObjectName() == castOther.getObjectName()) || (this.getObjectName() != null
						&& castOther.getObjectName() != null && this.getObjectName().equals(castOther.getObjectName())))
				&& ((this.getObjectSchema() == castOther.getObjectSchema())
						|| (this.getObjectSchema() != null && castOther.getObjectSchema() != null
								&& this.getObjectSchema().equals(castOther.getObjectSchema())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIndexName() == null ? 0 : this.getIndexName().hashCode());
		result = 37 * result + (getObjectName() == null ? 0 : this.getObjectName().hashCode());
		result = 37 * result + (getObjectSchema() == null ? 0 : this.getObjectSchema().hashCode());
		return result;
	}

}
