package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * SchemaTablesWithFullTableScansId generated by hbm2java
 */
public class SchemaTablesWithFullTableScansId implements java.io.Serializable {

	private String latency;
	private String objectName;
	private String objectSchema;
	private long rowsFullScanned;

	public SchemaTablesWithFullTableScansId() {
	}

	public SchemaTablesWithFullTableScansId(long rowsFullScanned) {
		this.rowsFullScanned = rowsFullScanned;
	}

	public SchemaTablesWithFullTableScansId(String latency, String objectName, String objectSchema,
			long rowsFullScanned) {
		this.latency = latency;
		this.objectName = objectName;
		this.objectSchema = objectSchema;
		this.rowsFullScanned = rowsFullScanned;
	}

	public String getLatency() {
		return this.latency;
	}

	public void setLatency(String latency) {
		this.latency = latency;
	}

	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	public String getObjectSchema() {
		return this.objectSchema;
	}

	public void setObjectSchema(String objectSchema) {
		this.objectSchema = objectSchema;
	}

	public long getRowsFullScanned() {
		return this.rowsFullScanned;
	}

	public void setRowsFullScanned(long rowsFullScanned) {
		this.rowsFullScanned = rowsFullScanned;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchemaTablesWithFullTableScansId))
			return false;
		SchemaTablesWithFullTableScansId castOther = (SchemaTablesWithFullTableScansId) other;

		return ((this.getLatency() == castOther.getLatency()) || (this.getLatency() != null
				&& castOther.getLatency() != null && this.getLatency().equals(castOther.getLatency())))
				&& ((this.getObjectName() == castOther.getObjectName()) || (this.getObjectName() != null
						&& castOther.getObjectName() != null && this.getObjectName().equals(castOther.getObjectName())))
				&& ((this.getObjectSchema() == castOther.getObjectSchema())
						|| (this.getObjectSchema() != null && castOther.getObjectSchema() != null
								&& this.getObjectSchema().equals(castOther.getObjectSchema())))
				&& (this.getRowsFullScanned() == castOther.getRowsFullScanned());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLatency() == null ? 0 : this.getLatency().hashCode());
		result = 37 * result + (getObjectName() == null ? 0 : this.getObjectName().hashCode());
		result = 37 * result + (getObjectSchema() == null ? 0 : this.getObjectSchema().hashCode());
		result = 37 * result + (int) this.getRowsFullScanned();
		return result;
	}

}
