package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * SessionSslStatus generated by hbm2java
 */
public class SessionSslStatus implements java.io.Serializable {

	private SessionSslStatusId id;

	public SessionSslStatus() {
	}

	public SessionSslStatus(SessionSslStatusId id) {
		this.id = id;
	}

	public SessionSslStatusId getId() {
		return this.id;
	}

	public void setId(SessionSslStatusId id) {
		this.id = id;
	}

}
