package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * SessionSslStatusId generated by hbm2java
 */
public class SessionSslStatusId implements java.io.Serializable {

	private String sslCipher;
	private String sslSessionsReused;
	private String sslVersion;
	private long threadId;

	public SessionSslStatusId() {
	}

	public SessionSslStatusId(long threadId) {
		this.threadId = threadId;
	}

	public SessionSslStatusId(String sslCipher, String sslSessionsReused, String sslVersion, long threadId) {
		this.sslCipher = sslCipher;
		this.sslSessionsReused = sslSessionsReused;
		this.sslVersion = sslVersion;
		this.threadId = threadId;
	}

	public String getSslCipher() {
		return this.sslCipher;
	}

	public void setSslCipher(String sslCipher) {
		this.sslCipher = sslCipher;
	}

	public String getSslSessionsReused() {
		return this.sslSessionsReused;
	}

	public void setSslSessionsReused(String sslSessionsReused) {
		this.sslSessionsReused = sslSessionsReused;
	}

	public String getSslVersion() {
		return this.sslVersion;
	}

	public void setSslVersion(String sslVersion) {
		this.sslVersion = sslVersion;
	}

	public long getThreadId() {
		return this.threadId;
	}

	public void setThreadId(long threadId) {
		this.threadId = threadId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SessionSslStatusId))
			return false;
		SessionSslStatusId castOther = (SessionSslStatusId) other;

		return ((this.getSslCipher() == castOther.getSslCipher()) || (this.getSslCipher() != null
				&& castOther.getSslCipher() != null && this.getSslCipher().equals(castOther.getSslCipher())))
				&& ((this.getSslSessionsReused() == castOther.getSslSessionsReused())
						|| (this.getSslSessionsReused() != null && castOther.getSslSessionsReused() != null
								&& this.getSslSessionsReused().equals(castOther.getSslSessionsReused())))
				&& ((this.getSslVersion() == castOther.getSslVersion()) || (this.getSslVersion() != null
						&& castOther.getSslVersion() != null && this.getSslVersion().equals(castOther.getSslVersion())))
				&& (this.getThreadId() == castOther.getThreadId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSslCipher() == null ? 0 : this.getSslCipher().hashCode());
		result = 37 * result + (getSslSessionsReused() == null ? 0 : this.getSslSessionsReused().hashCode());
		result = 37 * result + (getSslVersion() == null ? 0 : this.getSslVersion().hashCode());
		result = 37 * result + (int) this.getThreadId();
		return result;
	}

}
