package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * StatementsWithErrorsOrWarnings generated by hbm2java
 */
public class StatementsWithErrorsOrWarnings implements java.io.Serializable {

	private StatementsWithErrorsOrWarningsId id;

	public StatementsWithErrorsOrWarnings() {
	}

	public StatementsWithErrorsOrWarnings(StatementsWithErrorsOrWarningsId id) {
		this.id = id;
	}

	public StatementsWithErrorsOrWarningsId getId() {
		return this.id;
	}

	public void setId(StatementsWithErrorsOrWarningsId id) {
		this.id = id;
	}

}
