package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

import java.math.BigInteger;
import java.sql.Timestamp;

/**
 * StatementsWithTempTablesId generated by hbm2java
 */
public class StatementsWithTempTablesId implements java.io.Serializable {

	private BigInteger avgTmpTablesPerQuery;
	private String db;
	private String digest;
	private long diskTmpTables;
	private long execCount;
	private Timestamp firstSeen;
	private Timestamp lastSeen;
	private long memoryTmpTables;
	private String query;
	private BigInteger tmpTablesToDiskPct;
	private String totalLatency;

	public StatementsWithTempTablesId() {
	}

	public StatementsWithTempTablesId(BigInteger avgTmpTablesPerQuery, long diskTmpTables, long execCount,
			Timestamp firstSeen, Timestamp lastSeen, long memoryTmpTables, BigInteger tmpTablesToDiskPct) {
		this.avgTmpTablesPerQuery = avgTmpTablesPerQuery;
		this.diskTmpTables = diskTmpTables;
		this.execCount = execCount;
		this.firstSeen = firstSeen;
		this.lastSeen = lastSeen;
		this.memoryTmpTables = memoryTmpTables;
		this.tmpTablesToDiskPct = tmpTablesToDiskPct;
	}

	public StatementsWithTempTablesId(BigInteger avgTmpTablesPerQuery, String db, String digest, long diskTmpTables,
			long execCount, Timestamp firstSeen, Timestamp lastSeen, long memoryTmpTables, String query,
			BigInteger tmpTablesToDiskPct, String totalLatency) {
		this.avgTmpTablesPerQuery = avgTmpTablesPerQuery;
		this.db = db;
		this.digest = digest;
		this.diskTmpTables = diskTmpTables;
		this.execCount = execCount;
		this.firstSeen = firstSeen;
		this.lastSeen = lastSeen;
		this.memoryTmpTables = memoryTmpTables;
		this.query = query;
		this.tmpTablesToDiskPct = tmpTablesToDiskPct;
		this.totalLatency = totalLatency;
	}

	public BigInteger getAvgTmpTablesPerQuery() {
		return this.avgTmpTablesPerQuery;
	}

	public void setAvgTmpTablesPerQuery(BigInteger avgTmpTablesPerQuery) {
		this.avgTmpTablesPerQuery = avgTmpTablesPerQuery;
	}

	public String getDb() {
		return this.db;
	}

	public void setDb(String db) {
		this.db = db;
	}

	public String getDigest() {
		return this.digest;
	}

	public void setDigest(String digest) {
		this.digest = digest;
	}

	public long getDiskTmpTables() {
		return this.diskTmpTables;
	}

	public void setDiskTmpTables(long diskTmpTables) {
		this.diskTmpTables = diskTmpTables;
	}

	public long getExecCount() {
		return this.execCount;
	}

	public void setExecCount(long execCount) {
		this.execCount = execCount;
	}

	public Timestamp getFirstSeen() {
		return this.firstSeen;
	}

	public void setFirstSeen(Timestamp firstSeen) {
		this.firstSeen = firstSeen;
	}

	public Timestamp getLastSeen() {
		return this.lastSeen;
	}

	public void setLastSeen(Timestamp lastSeen) {
		this.lastSeen = lastSeen;
	}

	public long getMemoryTmpTables() {
		return this.memoryTmpTables;
	}

	public void setMemoryTmpTables(long memoryTmpTables) {
		this.memoryTmpTables = memoryTmpTables;
	}

	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public BigInteger getTmpTablesToDiskPct() {
		return this.tmpTablesToDiskPct;
	}

	public void setTmpTablesToDiskPct(BigInteger tmpTablesToDiskPct) {
		this.tmpTablesToDiskPct = tmpTablesToDiskPct;
	}

	public String getTotalLatency() {
		return this.totalLatency;
	}

	public void setTotalLatency(String totalLatency) {
		this.totalLatency = totalLatency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StatementsWithTempTablesId))
			return false;
		StatementsWithTempTablesId castOther = (StatementsWithTempTablesId) other;

		return ((this.getAvgTmpTablesPerQuery() == castOther.getAvgTmpTablesPerQuery())
				|| (this.getAvgTmpTablesPerQuery() != null && castOther.getAvgTmpTablesPerQuery() != null
						&& this.getAvgTmpTablesPerQuery().equals(castOther.getAvgTmpTablesPerQuery())))
				&& ((this.getDb() == castOther.getDb()) || (this.getDb() != null && castOther.getDb() != null
						&& this.getDb().equals(castOther.getDb())))
				&& ((this.getDigest() == castOther.getDigest()) || (this.getDigest() != null
						&& castOther.getDigest() != null && this.getDigest().equals(castOther.getDigest())))
				&& (this.getDiskTmpTables() == castOther.getDiskTmpTables())
				&& (this.getExecCount() == castOther.getExecCount())
				&& ((this.getFirstSeen() == castOther.getFirstSeen()) || (this.getFirstSeen() != null
						&& castOther.getFirstSeen() != null && this.getFirstSeen().equals(castOther.getFirstSeen())))
				&& ((this.getLastSeen() == castOther.getLastSeen()) || (this.getLastSeen() != null
						&& castOther.getLastSeen() != null && this.getLastSeen().equals(castOther.getLastSeen())))
				&& (this.getMemoryTmpTables() == castOther.getMemoryTmpTables())
				&& ((this.getQuery() == castOther.getQuery()) || (this.getQuery() != null
						&& castOther.getQuery() != null && this.getQuery().equals(castOther.getQuery())))
				&& ((this.getTmpTablesToDiskPct() == castOther.getTmpTablesToDiskPct())
						|| (this.getTmpTablesToDiskPct() != null && castOther.getTmpTablesToDiskPct() != null
								&& this.getTmpTablesToDiskPct().equals(castOther.getTmpTablesToDiskPct())))
				&& ((this.getTotalLatency() == castOther.getTotalLatency())
						|| (this.getTotalLatency() != null && castOther.getTotalLatency() != null
								&& this.getTotalLatency().equals(castOther.getTotalLatency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAvgTmpTablesPerQuery() == null ? 0 : this.getAvgTmpTablesPerQuery().hashCode());
		result = 37 * result + (getDb() == null ? 0 : this.getDb().hashCode());
		result = 37 * result + (getDigest() == null ? 0 : this.getDigest().hashCode());
		result = 37 * result + (int) this.getDiskTmpTables();
		result = 37 * result + (int) this.getExecCount();
		result = 37 * result + (getFirstSeen() == null ? 0 : this.getFirstSeen().hashCode());
		result = 37 * result + (getLastSeen() == null ? 0 : this.getLastSeen().hashCode());
		result = 37 * result + (int) this.getMemoryTmpTables();
		result = 37 * result + (getQuery() == null ? 0 : this.getQuery().hashCode());
		result = 37 * result + (getTmpTablesToDiskPct() == null ? 0 : this.getTmpTablesToDiskPct().hashCode());
		result = 37 * result + (getTotalLatency() == null ? 0 : this.getTotalLatency().hashCode());
		return result;
	}

}
