package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * StatementAnalysis generated by hbm2java
 */
public class StatementAnalysis implements java.io.Serializable {

	private StatementAnalysisId id;

	public StatementAnalysis() {
	}

	public StatementAnalysis(StatementAnalysisId id) {
		this.id = id;
	}

	public StatementAnalysisId getId() {
		return this.id;
	}

	public void setId(StatementAnalysisId id) {
		this.id = id;
	}

}
