package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * StatementsWithFullTableScans generated by hbm2java
 */
public class StatementsWithFullTableScans implements java.io.Serializable {

	private StatementsWithFullTableScansId id;

	public StatementsWithFullTableScans() {
	}

	public StatementsWithFullTableScans(StatementsWithFullTableScansId id) {
		this.id = id;
	}

	public StatementsWithFullTableScansId getId() {
		return this.id;
	}

	public void setId(StatementsWithFullTableScansId id) {
		this.id = id;
	}

}
