package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * StatementsWithRuntimesIn95thPercentile generated by hbm2java
 */
public class StatementsWithRuntimesIn95thPercentile implements java.io.Serializable {

	private StatementsWithRuntimesIn95thPercentileId id;

	public StatementsWithRuntimesIn95thPercentile() {
	}

	public StatementsWithRuntimesIn95thPercentile(StatementsWithRuntimesIn95thPercentileId id) {
		this.id = id;
	}

	public StatementsWithRuntimesIn95thPercentileId getId() {
		return this.id;
	}

	public void setId(StatementsWithRuntimesIn95thPercentileId id) {
		this.id = id;
	}

}
