package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;

/**
 * SysConfig generated by hbm2java
 */
public class SysConfig implements java.io.Serializable {

	private String variable;
	private String value;
	private Timestamp setTime;
	private String setBy;

	public SysConfig() {
	}

	public SysConfig(String variable) {
		this.variable = variable;
	}

	public SysConfig(String variable, String value, Timestamp setTime, String setBy) {
		this.variable = variable;
		this.value = value;
		this.setTime = setTime;
		this.setBy = setBy;
	}

	public String getVariable() {
		return this.variable;
	}

	public void setVariable(String variable) {
		this.variable = variable;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Timestamp getSetTime() {
		return this.setTime;
	}

	public void setSetTime(Timestamp setTime) {
		this.setTime = setTime;
	}

	public String getSetBy() {
		return this.setBy;
	}

	public void setSetBy(String setBy) {
		this.setBy = setBy;
	}

}
