package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * TraumacentercriteriatypeItemtype generated by hbm2java
 */
public class TraumacentercriteriatypeItemtype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private Long traumaCenterCriterion;
	private Long traumaCenterCriteriaTypeItemHjid;
	private Integer traumaCenterCriteriaTypeItemHjindex;

	public TraumacentercriteriatypeItemtype() {
	}

	public TraumacentercriteriatypeItemtype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public TraumacentercriteriatypeItemtype(long hjid, String hjtype, long hjversion, Long traumaCenterCriterion,
			Long traumaCenterCriteriaTypeItemHjid, Integer traumaCenterCriteriaTypeItemHjindex) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.traumaCenterCriterion = traumaCenterCriterion;
		this.traumaCenterCriteriaTypeItemHjid = traumaCenterCriteriaTypeItemHjid;
		this.traumaCenterCriteriaTypeItemHjindex = traumaCenterCriteriaTypeItemHjindex;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public Long getTraumaCenterCriterion() {
		return this.traumaCenterCriterion;
	}

	public void setTraumaCenterCriterion(Long traumaCenterCriterion) {
		this.traumaCenterCriterion = traumaCenterCriterion;
	}

	public Long getTraumaCenterCriteriaTypeItemHjid() {
		return this.traumaCenterCriteriaTypeItemHjid;
	}

	public void setTraumaCenterCriteriaTypeItemHjid(Long traumaCenterCriteriaTypeItemHjid) {
		this.traumaCenterCriteriaTypeItemHjid = traumaCenterCriteriaTypeItemHjid;
	}

	public Integer getTraumaCenterCriteriaTypeItemHjindex() {
		return this.traumaCenterCriteriaTypeItemHjindex;
	}

	public void setTraumaCenterCriteriaTypeItemHjindex(Integer traumaCenterCriteriaTypeItemHjindex) {
		this.traumaCenterCriteriaTypeItemHjindex = traumaCenterCriteriaTypeItemHjindex;
	}

}
