package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * UserSummary generated by hbm2java
 */
public class UserSummary implements java.io.Serializable {

	private UserSummaryId id;

	public UserSummary() {
	}

	public UserSummary(UserSummaryId id) {
		this.id = id;
	}

	public UserSummaryId getId() {
		return this.id;
	}

	public void setId(UserSummaryId id) {
		this.id = id;
	}

}
