package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

import java.math.BigInteger;

/**
 * UserSummaryId generated by hbm2java
 */
public class UserSummaryId implements java.io.Serializable {

	private BigInteger currentConnections;
	private String currentMemory;
	private String fileIoLatency;
	private BigInteger fileIos;
	private String statementAvgLatency;
	private String statementLatency;
	private BigInteger statements;
	private BigInteger tableScans;
	private BigInteger totalConnections;
	private String totalMemoryAllocated;
	private long uniqueHosts;
	private String user;

	public UserSummaryId() {
	}

	public UserSummaryId(long uniqueHosts) {
		this.uniqueHosts = uniqueHosts;
	}

	public UserSummaryId(BigInteger currentConnections, String currentMemory, String fileIoLatency, BigInteger fileIos,
			String statementAvgLatency, String statementLatency, BigInteger statements, BigInteger tableScans,
			BigInteger totalConnections, String totalMemoryAllocated, long uniqueHosts, String user) {
		this.currentConnections = currentConnections;
		this.currentMemory = currentMemory;
		this.fileIoLatency = fileIoLatency;
		this.fileIos = fileIos;
		this.statementAvgLatency = statementAvgLatency;
		this.statementLatency = statementLatency;
		this.statements = statements;
		this.tableScans = tableScans;
		this.totalConnections = totalConnections;
		this.totalMemoryAllocated = totalMemoryAllocated;
		this.uniqueHosts = uniqueHosts;
		this.user = user;
	}

	public BigInteger getCurrentConnections() {
		return this.currentConnections;
	}

	public void setCurrentConnections(BigInteger currentConnections) {
		this.currentConnections = currentConnections;
	}

	public String getCurrentMemory() {
		return this.currentMemory;
	}

	public void setCurrentMemory(String currentMemory) {
		this.currentMemory = currentMemory;
	}

	public String getFileIoLatency() {
		return this.fileIoLatency;
	}

	public void setFileIoLatency(String fileIoLatency) {
		this.fileIoLatency = fileIoLatency;
	}

	public BigInteger getFileIos() {
		return this.fileIos;
	}

	public void setFileIos(BigInteger fileIos) {
		this.fileIos = fileIos;
	}

	public String getStatementAvgLatency() {
		return this.statementAvgLatency;
	}

	public void setStatementAvgLatency(String statementAvgLatency) {
		this.statementAvgLatency = statementAvgLatency;
	}

	public String getStatementLatency() {
		return this.statementLatency;
	}

	public void setStatementLatency(String statementLatency) {
		this.statementLatency = statementLatency;
	}

	public BigInteger getStatements() {
		return this.statements;
	}

	public void setStatements(BigInteger statements) {
		this.statements = statements;
	}

	public BigInteger getTableScans() {
		return this.tableScans;
	}

	public void setTableScans(BigInteger tableScans) {
		this.tableScans = tableScans;
	}

	public BigInteger getTotalConnections() {
		return this.totalConnections;
	}

	public void setTotalConnections(BigInteger totalConnections) {
		this.totalConnections = totalConnections;
	}

	public String getTotalMemoryAllocated() {
		return this.totalMemoryAllocated;
	}

	public void setTotalMemoryAllocated(String totalMemoryAllocated) {
		this.totalMemoryAllocated = totalMemoryAllocated;
	}

	public long getUniqueHosts() {
		return this.uniqueHosts;
	}

	public void setUniqueHosts(long uniqueHosts) {
		this.uniqueHosts = uniqueHosts;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserSummaryId))
			return false;
		UserSummaryId castOther = (UserSummaryId) other;

		return ((this.getCurrentConnections() == castOther.getCurrentConnections())
				|| (this.getCurrentConnections() != null && castOther.getCurrentConnections() != null
						&& this.getCurrentConnections().equals(castOther.getCurrentConnections())))
				&& ((this.getCurrentMemory() == castOther.getCurrentMemory())
						|| (this.getCurrentMemory() != null && castOther.getCurrentMemory() != null
								&& this.getCurrentMemory().equals(castOther.getCurrentMemory())))
				&& ((this.getFileIoLatency() == castOther.getFileIoLatency())
						|| (this.getFileIoLatency() != null && castOther.getFileIoLatency() != null
								&& this.getFileIoLatency().equals(castOther.getFileIoLatency())))
				&& ((this.getFileIos() == castOther.getFileIos()) || (this.getFileIos() != null
						&& castOther.getFileIos() != null && this.getFileIos().equals(castOther.getFileIos())))
				&& ((this.getStatementAvgLatency() == castOther.getStatementAvgLatency())
						|| (this.getStatementAvgLatency() != null && castOther.getStatementAvgLatency() != null
								&& this.getStatementAvgLatency().equals(castOther.getStatementAvgLatency())))
				&& ((this.getStatementLatency() == castOther.getStatementLatency())
						|| (this.getStatementLatency() != null && castOther.getStatementLatency() != null
								&& this.getStatementLatency().equals(castOther.getStatementLatency())))
				&& ((this.getStatements() == castOther.getStatements()) || (this.getStatements() != null
						&& castOther.getStatements() != null && this.getStatements().equals(castOther.getStatements())))
				&& ((this.getTableScans() == castOther.getTableScans()) || (this.getTableScans() != null
						&& castOther.getTableScans() != null && this.getTableScans().equals(castOther.getTableScans())))
				&& ((this.getTotalConnections() == castOther.getTotalConnections())
						|| (this.getTotalConnections() != null && castOther.getTotalConnections() != null
								&& this.getTotalConnections().equals(castOther.getTotalConnections())))
				&& ((this.getTotalMemoryAllocated() == castOther.getTotalMemoryAllocated())
						|| (this.getTotalMemoryAllocated() != null && castOther.getTotalMemoryAllocated() != null
								&& this.getTotalMemoryAllocated().equals(castOther.getTotalMemoryAllocated())))
				&& (this.getUniqueHosts() == castOther.getUniqueHosts())
				&& ((this.getUser() == castOther.getUser()) || (this.getUser() != null && castOther.getUser() != null
						&& this.getUser().equals(castOther.getUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCurrentConnections() == null ? 0 : this.getCurrentConnections().hashCode());
		result = 37 * result + (getCurrentMemory() == null ? 0 : this.getCurrentMemory().hashCode());
		result = 37 * result + (getFileIoLatency() == null ? 0 : this.getFileIoLatency().hashCode());
		result = 37 * result + (getFileIos() == null ? 0 : this.getFileIos().hashCode());
		result = 37 * result + (getStatementAvgLatency() == null ? 0 : this.getStatementAvgLatency().hashCode());
		result = 37 * result + (getStatementLatency() == null ? 0 : this.getStatementLatency().hashCode());
		result = 37 * result + (getStatements() == null ? 0 : this.getStatements().hashCode());
		result = 37 * result + (getTableScans() == null ? 0 : this.getTableScans().hashCode());
		result = 37 * result + (getTotalConnections() == null ? 0 : this.getTotalConnections().hashCode());
		result = 37 * result + (getTotalMemoryAllocated() == null ? 0 : this.getTotalMemoryAllocated().hashCode());
		result = 37 * result + (int) this.getUniqueHosts();
		result = 37 * result + (getUser() == null ? 0 : this.getUser().hashCode());
		return result;
	}

}
