package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

import java.math.BigInteger;

/**
 * UserSummaryByStatementLatencyId generated by hbm2java
 */
public class UserSummaryByStatementLatencyId implements java.io.Serializable {

	private String cpuLatency;
	private BigInteger fullScans;
	private String lockLatency;
	private String maxLatency;
	private BigInteger rowsAffected;
	private BigInteger rowsExamined;
	private BigInteger rowsSent;
	private BigInteger total;
	private String totalLatency;
	private String user;

	public UserSummaryByStatementLatencyId() {
	}

	public UserSummaryByStatementLatencyId(String cpuLatency, BigInteger fullScans, String lockLatency,
			String maxLatency, BigInteger rowsAffected, BigInteger rowsExamined, BigInteger rowsSent, BigInteger total,
			String totalLatency, String user) {
		this.cpuLatency = cpuLatency;
		this.fullScans = fullScans;
		this.lockLatency = lockLatency;
		this.maxLatency = maxLatency;
		this.rowsAffected = rowsAffected;
		this.rowsExamined = rowsExamined;
		this.rowsSent = rowsSent;
		this.total = total;
		this.totalLatency = totalLatency;
		this.user = user;
	}

	public String getCpuLatency() {
		return this.cpuLatency;
	}

	public void setCpuLatency(String cpuLatency) {
		this.cpuLatency = cpuLatency;
	}

	public BigInteger getFullScans() {
		return this.fullScans;
	}

	public void setFullScans(BigInteger fullScans) {
		this.fullScans = fullScans;
	}

	public String getLockLatency() {
		return this.lockLatency;
	}

	public void setLockLatency(String lockLatency) {
		this.lockLatency = lockLatency;
	}

	public String getMaxLatency() {
		return this.maxLatency;
	}

	public void setMaxLatency(String maxLatency) {
		this.maxLatency = maxLatency;
	}

	public BigInteger getRowsAffected() {
		return this.rowsAffected;
	}

	public void setRowsAffected(BigInteger rowsAffected) {
		this.rowsAffected = rowsAffected;
	}

	public BigInteger getRowsExamined() {
		return this.rowsExamined;
	}

	public void setRowsExamined(BigInteger rowsExamined) {
		this.rowsExamined = rowsExamined;
	}

	public BigInteger getRowsSent() {
		return this.rowsSent;
	}

	public void setRowsSent(BigInteger rowsSent) {
		this.rowsSent = rowsSent;
	}

	public BigInteger getTotal() {
		return this.total;
	}

	public void setTotal(BigInteger total) {
		this.total = total;
	}

	public String getTotalLatency() {
		return this.totalLatency;
	}

	public void setTotalLatency(String totalLatency) {
		this.totalLatency = totalLatency;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserSummaryByStatementLatencyId))
			return false;
		UserSummaryByStatementLatencyId castOther = (UserSummaryByStatementLatencyId) other;

		return ((this.getCpuLatency() == castOther.getCpuLatency()) || (this.getCpuLatency() != null
				&& castOther.getCpuLatency() != null && this.getCpuLatency().equals(castOther.getCpuLatency())))
				&& ((this.getFullScans() == castOther.getFullScans()) || (this.getFullScans() != null
						&& castOther.getFullScans() != null && this.getFullScans().equals(castOther.getFullScans())))
				&& ((this.getLockLatency() == castOther.getLockLatency())
						|| (this.getLockLatency() != null && castOther.getLockLatency() != null
								&& this.getLockLatency().equals(castOther.getLockLatency())))
				&& ((this.getMaxLatency() == castOther.getMaxLatency()) || (this.getMaxLatency() != null
						&& castOther.getMaxLatency() != null && this.getMaxLatency().equals(castOther.getMaxLatency())))
				&& ((this.getRowsAffected() == castOther.getRowsAffected())
						|| (this.getRowsAffected() != null && castOther.getRowsAffected() != null
								&& this.getRowsAffected().equals(castOther.getRowsAffected())))
				&& ((this.getRowsExamined() == castOther.getRowsExamined())
						|| (this.getRowsExamined() != null && castOther.getRowsExamined() != null
								&& this.getRowsExamined().equals(castOther.getRowsExamined())))
				&& ((this.getRowsSent() == castOther.getRowsSent()) || (this.getRowsSent() != null
						&& castOther.getRowsSent() != null && this.getRowsSent().equals(castOther.getRowsSent())))
				&& ((this.getTotal() == castOther.getTotal()) || (this.getTotal() != null
						&& castOther.getTotal() != null && this.getTotal().equals(castOther.getTotal())))
				&& ((this.getTotalLatency() == castOther.getTotalLatency())
						|| (this.getTotalLatency() != null && castOther.getTotalLatency() != null
								&& this.getTotalLatency().equals(castOther.getTotalLatency())))
				&& ((this.getUser() == castOther.getUser()) || (this.getUser() != null && castOther.getUser() != null
						&& this.getUser().equals(castOther.getUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCpuLatency() == null ? 0 : this.getCpuLatency().hashCode());
		result = 37 * result + (getFullScans() == null ? 0 : this.getFullScans().hashCode());
		result = 37 * result + (getLockLatency() == null ? 0 : this.getLockLatency().hashCode());
		result = 37 * result + (getMaxLatency() == null ? 0 : this.getMaxLatency().hashCode());
		result = 37 * result + (getRowsAffected() == null ? 0 : this.getRowsAffected().hashCode());
		result = 37 * result + (getRowsExamined() == null ? 0 : this.getRowsExamined().hashCode());
		result = 37 * result + (getRowsSent() == null ? 0 : this.getRowsSent().hashCode());
		result = 37 * result + (getTotal() == null ? 0 : this.getTotal().hashCode());
		result = 37 * result + (getTotalLatency() == null ? 0 : this.getTotalLatency().hashCode());
		result = 37 * result + (getUser() == null ? 0 : this.getUser().hashCode());
		return result;
	}

}
