package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * VehiclepedotherstypeItemtype generated by hbm2java
 */
public class VehiclepedotherstypeItemtype implements java.io.Serializable {

	private long hjid;
	private String hjtype;
	private long hjversion;
	private Long vehicularPedestrianOther;
	private Long vehiclePedOthersTypeItemHjid;
	private Integer vehiclePedOthersTypeItemHjindex;

	public VehiclepedotherstypeItemtype() {
	}

	public VehiclepedotherstypeItemtype(long hjid, String hjtype, long hjversion) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
	}

	public VehiclepedotherstypeItemtype(long hjid, String hjtype, long hjversion, Long vehicularPedestrianOther,
			Long vehiclePedOthersTypeItemHjid, Integer vehiclePedOthersTypeItemHjindex) {
		this.hjid = hjid;
		this.hjtype = hjtype;
		this.hjversion = hjversion;
		this.vehicularPedestrianOther = vehicularPedestrianOther;
		this.vehiclePedOthersTypeItemHjid = vehiclePedOthersTypeItemHjid;
		this.vehiclePedOthersTypeItemHjindex = vehiclePedOthersTypeItemHjindex;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getHjtype() {
		return this.hjtype;
	}

	public void setHjtype(String hjtype) {
		this.hjtype = hjtype;
	}

	public long getHjversion() {
		return this.hjversion;
	}

	public void setHjversion(long hjversion) {
		this.hjversion = hjversion;
	}

	public Long getVehicularPedestrianOther() {
		return this.vehicularPedestrianOther;
	}

	public void setVehicularPedestrianOther(Long vehicularPedestrianOther) {
		this.vehicularPedestrianOther = vehicularPedestrianOther;
	}

	public Long getVehiclePedOthersTypeItemHjid() {
		return this.vehiclePedOthersTypeItemHjid;
	}

	public void setVehiclePedOthersTypeItemHjid(Long vehiclePedOthersTypeItemHjid) {
		this.vehiclePedOthersTypeItemHjid = vehiclePedOthersTypeItemHjid;
	}

	public Integer getVehiclePedOthersTypeItemHjindex() {
		return this.vehiclePedOthersTypeItemHjindex;
	}

	public void setVehiclePedOthersTypeItemHjindex(Integer vehiclePedOthersTypeItemHjindex) {
		this.vehiclePedOthersTypeItemHjindex = vehiclePedOthersTypeItemHjindex;
	}

}
