package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * VersionId generated by hbm2java
 */
public class VersionId implements java.io.Serializable {

	private String mysqlVersion;
	private String sysVersion;

	public VersionId() {
	}

	public VersionId(String mysqlVersion, String sysVersion) {
		this.mysqlVersion = mysqlVersion;
		this.sysVersion = sysVersion;
	}

	public String getMysqlVersion() {
		return this.mysqlVersion;
	}

	public void setMysqlVersion(String mysqlVersion) {
		this.mysqlVersion = mysqlVersion;
	}

	public String getSysVersion() {
		return this.sysVersion;
	}

	public void setSysVersion(String sysVersion) {
		this.sysVersion = sysVersion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VersionId))
			return false;
		VersionId castOther = (VersionId) other;

		return ((this.getMysqlVersion() == castOther.getMysqlVersion()) || (this.getMysqlVersion() != null
				&& castOther.getMysqlVersion() != null && this.getMysqlVersion().equals(castOther.getMysqlVersion())))
				&& ((this.getSysVersion() == castOther.getSysVersion())
						|| (this.getSysVersion() != null && castOther.getSysVersion() != null
								&& this.getSysVersion().equals(castOther.getSysVersion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMysqlVersion() == null ? 0 : this.getMysqlVersion().hashCode());
		result = 37 * result + (getSysVersion() == null ? 0 : this.getSysVersion().hashCode());
		return result;
	}

}
