package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * Version generated by hbm2java
 */
public class Version implements java.io.Serializable {

	private VersionId id;

	public Version() {
	}

	public Version(VersionId id) {
		this.id = id;
	}

	public VersionId getId() {
		return this.id;
	}

	public void setId(VersionId id) {
		this.id = id;
	}

}
