package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * WaitClassesGlobalByLatency generated by hbm2java
 */
public class WaitClassesGlobalByLatency implements java.io.Serializable {

	private WaitClassesGlobalByLatencyId id;

	public WaitClassesGlobalByLatency() {
	}

	public WaitClassesGlobalByLatency(WaitClassesGlobalByLatencyId id) {
		this.id = id;
	}

	public WaitClassesGlobalByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitClassesGlobalByLatencyId id) {
		this.id = id;
	}

}
