package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * WaitsGlobalByLatency generated by hbm2java
 */
public class WaitsGlobalByLatency implements java.io.Serializable {

	private WaitsGlobalByLatencyId id;

	public WaitsGlobalByLatency() {
	}

	public WaitsGlobalByLatency(WaitsGlobalByLatencyId id) {
		this.id = id;
	}

	public WaitsGlobalByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitsGlobalByLatencyId id) {
		this.id = id;
	}

}
