package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * WaitsByUserByLatency generated by hbm2java
 */
public class WaitsByUserByLatency implements java.io.Serializable {

	private WaitsByUserByLatencyId id;

	public WaitsByUserByLatency() {
	}

	public WaitsByUserByLatency(WaitsByUserByLatencyId id) {
		this.id = id;
	}

	public WaitsByUserByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitsByUserByLatencyId id) {
		this.id = id;
	}

}
