package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

import java.math.BigInteger;

/**
 * WaitClassesGlobalByAvgLatencyId generated by hbm2java
 */
public class WaitClassesGlobalByAvgLatencyId implements java.io.Serializable {

	private String avgLatency;
	private String eventClass;
	private String maxLatency;
	private String minLatency;
	private BigInteger total;
	private String totalLatency;

	public WaitClassesGlobalByAvgLatencyId() {
	}

	public WaitClassesGlobalByAvgLatencyId(String avgLatency, String eventClass, String maxLatency, String minLatency,
			BigInteger total, String totalLatency) {
		this.avgLatency = avgLatency;
		this.eventClass = eventClass;
		this.maxLatency = maxLatency;
		this.minLatency = minLatency;
		this.total = total;
		this.totalLatency = totalLatency;
	}

	public String getAvgLatency() {
		return this.avgLatency;
	}

	public void setAvgLatency(String avgLatency) {
		this.avgLatency = avgLatency;
	}

	public String getEventClass() {
		return this.eventClass;
	}

	public void setEventClass(String eventClass) {
		this.eventClass = eventClass;
	}

	public String getMaxLatency() {
		return this.maxLatency;
	}

	public void setMaxLatency(String maxLatency) {
		this.maxLatency = maxLatency;
	}

	public String getMinLatency() {
		return this.minLatency;
	}

	public void setMinLatency(String minLatency) {
		this.minLatency = minLatency;
	}

	public BigInteger getTotal() {
		return this.total;
	}

	public void setTotal(BigInteger total) {
		this.total = total;
	}

	public String getTotalLatency() {
		return this.totalLatency;
	}

	public void setTotalLatency(String totalLatency) {
		this.totalLatency = totalLatency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WaitClassesGlobalByAvgLatencyId))
			return false;
		WaitClassesGlobalByAvgLatencyId castOther = (WaitClassesGlobalByAvgLatencyId) other;

		return ((this.getAvgLatency() == castOther.getAvgLatency()) || (this.getAvgLatency() != null
				&& castOther.getAvgLatency() != null && this.getAvgLatency().equals(castOther.getAvgLatency())))
				&& ((this.getEventClass() == castOther.getEventClass()) || (this.getEventClass() != null
						&& castOther.getEventClass() != null && this.getEventClass().equals(castOther.getEventClass())))
				&& ((this.getMaxLatency() == castOther.getMaxLatency()) || (this.getMaxLatency() != null
						&& castOther.getMaxLatency() != null && this.getMaxLatency().equals(castOther.getMaxLatency())))
				&& ((this.getMinLatency() == castOther.getMinLatency()) || (this.getMinLatency() != null
						&& castOther.getMinLatency() != null && this.getMinLatency().equals(castOther.getMinLatency())))
				&& ((this.getTotal() == castOther.getTotal()) || (this.getTotal() != null
						&& castOther.getTotal() != null && this.getTotal().equals(castOther.getTotal())))
				&& ((this.getTotalLatency() == castOther.getTotalLatency())
						|| (this.getTotalLatency() != null && castOther.getTotalLatency() != null
								&& this.getTotalLatency().equals(castOther.getTotalLatency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAvgLatency() == null ? 0 : this.getAvgLatency().hashCode());
		result = 37 * result + (getEventClass() == null ? 0 : this.getEventClass().hashCode());
		result = 37 * result + (getMaxLatency() == null ? 0 : this.getMaxLatency().hashCode());
		result = 37 * result + (getMinLatency() == null ? 0 : this.getMinLatency().hashCode());
		result = 37 * result + (getTotal() == null ? 0 : this.getTotal().hashCode());
		result = 37 * result + (getTotalLatency() == null ? 0 : this.getTotalLatency().hashCode());
		return result;
	}

}
