package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final

/**
 * WaitsGlobalByLatencyId generated by hbm2java
 */
public class WaitsGlobalByLatencyId implements java.io.Serializable {

	private String avgLatency;
	private String events;
	private String maxLatency;
	private long total;
	private String totalLatency;

	public WaitsGlobalByLatencyId() {
	}

	public WaitsGlobalByLatencyId(String events, long total) {
		this.events = events;
		this.total = total;
	}

	public WaitsGlobalByLatencyId(String avgLatency, String events, String maxLatency, long total,
			String totalLatency) {
		this.avgLatency = avgLatency;
		this.events = events;
		this.maxLatency = maxLatency;
		this.total = total;
		this.totalLatency = totalLatency;
	}

	public String getAvgLatency() {
		return this.avgLatency;
	}

	public void setAvgLatency(String avgLatency) {
		this.avgLatency = avgLatency;
	}

	public String getEvents() {
		return this.events;
	}

	public void setEvents(String events) {
		this.events = events;
	}

	public String getMaxLatency() {
		return this.maxLatency;
	}

	public void setMaxLatency(String maxLatency) {
		this.maxLatency = maxLatency;
	}

	public long getTotal() {
		return this.total;
	}

	public void setTotal(long total) {
		this.total = total;
	}

	public String getTotalLatency() {
		return this.totalLatency;
	}

	public void setTotalLatency(String totalLatency) {
		this.totalLatency = totalLatency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WaitsGlobalByLatencyId))
			return false;
		WaitsGlobalByLatencyId castOther = (WaitsGlobalByLatencyId) other;

		return ((this.getAvgLatency() == castOther.getAvgLatency()) || (this.getAvgLatency() != null
				&& castOther.getAvgLatency() != null && this.getAvgLatency().equals(castOther.getAvgLatency())))
				&& ((this.getEvents() == castOther.getEvents()) || (this.getEvents() != null
						&& castOther.getEvents() != null && this.getEvents().equals(castOther.getEvents())))
				&& ((this.getMaxLatency() == castOther.getMaxLatency()) || (this.getMaxLatency() != null
						&& castOther.getMaxLatency() != null && this.getMaxLatency().equals(castOther.getMaxLatency())))
				&& (this.getTotal() == castOther.getTotal())
				&& ((this.getTotalLatency() == castOther.getTotalLatency())
						|| (this.getTotalLatency() != null && castOther.getTotalLatency() != null
								&& this.getTotalLatency().equals(castOther.getTotalLatency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAvgLatency() == null ? 0 : this.getAvgLatency().hashCode());
		result = 37 * result + (getEvents() == null ? 0 : this.getEvents().hashCode());
		result = 37 * result + (getMaxLatency() == null ? 0 : this.getMaxLatency().hashCode());
		result = 37 * result + (int) this.getTotal();
		result = 37 * result + (getTotalLatency() == null ? 0 : this.getTotalLatency().hashCode());
		return result;
	}

}
