package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final



/**
 * X.hostSummaryByFileIoTypeId generated by hbm2java
 */
public class X.hostSummaryByFileIoTypeId  implements java.io.Serializable {


     private String eventName;
     private String host;
     private long maxLatency;
     private long total;
     private long totalLatency;

    public X.hostSummaryByFileIoTypeId() {
    }

	
    public X.hostSummaryByFileIoTypeId(String eventName, long maxLatency, long total, long totalLatency) {
        this.eventName = eventName;
        this.maxLatency = maxLatency;
        this.total = total;
        this.totalLatency = totalLatency;
    }
    public X.hostSummaryByFileIoTypeId(String eventName, String host, long maxLatency, long total, long totalLatency) {
       this.eventName = eventName;
       this.host = host;
       this.maxLatency = maxLatency;
       this.total = total;
       this.totalLatency = totalLatency;
    }
   
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public long getMaxLatency() {
        return this.maxLatency;
    }
    
    public void setMaxLatency(long maxLatency) {
        this.maxLatency = maxLatency;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }
    public long getTotalLatency() {
        return this.totalLatency;
    }
    
    public void setTotalLatency(long totalLatency) {
        this.totalLatency = totalLatency;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.hostSummaryByFileIoTypeId) ) return false;
		 X.hostSummaryByFileIoTypeId castOther = ( X.hostSummaryByFileIoTypeId ) other; 
         
		 return ( (this.getEventName()==castOther.getEventName()) || ( this.getEventName()!=null && castOther.getEventName()!=null && this.getEventName().equals(castOther.getEventName()) ) )
 && ( (this.getHost()==castOther.getHost()) || ( this.getHost()!=null && castOther.getHost()!=null && this.getHost().equals(castOther.getHost()) ) )
 && (this.getMaxLatency()==castOther.getMaxLatency())
 && (this.getTotal()==castOther.getTotal())
 && (this.getTotalLatency()==castOther.getTotalLatency());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEventName() == null ? 0 : this.getEventName().hashCode() );
         result = 37 * result + ( getHost() == null ? 0 : this.getHost().hashCode() );
         result = 37 * result + (int) this.getMaxLatency();
         result = 37 * result + (int) this.getTotal();
         result = 37 * result + (int) this.getTotalLatency();
         return result;
   }   


}


