package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final



/**
 * X.hostSummaryByStagesId generated by hbm2java
 */
public class X.hostSummaryByStagesId  implements java.io.Serializable {


     private long avgLatency;
     private String eventName;
     private String host;
     private long total;
     private long totalLatency;

    public X.hostSummaryByStagesId() {
    }

	
    public X.hostSummaryByStagesId(long avgLatency, String eventName, long total, long totalLatency) {
        this.avgLatency = avgLatency;
        this.eventName = eventName;
        this.total = total;
        this.totalLatency = totalLatency;
    }
    public X.hostSummaryByStagesId(long avgLatency, String eventName, String host, long total, long totalLatency) {
       this.avgLatency = avgLatency;
       this.eventName = eventName;
       this.host = host;
       this.total = total;
       this.totalLatency = totalLatency;
    }
   
    public long getAvgLatency() {
        return this.avgLatency;
    }
    
    public void setAvgLatency(long avgLatency) {
        this.avgLatency = avgLatency;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }
    public long getTotalLatency() {
        return this.totalLatency;
    }
    
    public void setTotalLatency(long totalLatency) {
        this.totalLatency = totalLatency;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.hostSummaryByStagesId) ) return false;
		 X.hostSummaryByStagesId castOther = ( X.hostSummaryByStagesId ) other; 
         
		 return (this.getAvgLatency()==castOther.getAvgLatency())
 && ( (this.getEventName()==castOther.getEventName()) || ( this.getEventName()!=null && castOther.getEventName()!=null && this.getEventName().equals(castOther.getEventName()) ) )
 && ( (this.getHost()==castOther.getHost()) || ( this.getHost()!=null && castOther.getHost()!=null && this.getHost().equals(castOther.getHost()) ) )
 && (this.getTotal()==castOther.getTotal())
 && (this.getTotalLatency()==castOther.getTotalLatency());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getAvgLatency();
         result = 37 * result + ( getEventName() == null ? 0 : this.getEventName().hashCode() );
         result = 37 * result + ( getHost() == null ? 0 : this.getHost().hashCode() );
         result = 37 * result + (int) this.getTotal();
         result = 37 * result + (int) this.getTotalLatency();
         return result;
   }   


}


