package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.hostSummaryByStatementTypeId;

/**
 * X.hostSummaryByStatementType generated by hbm2java
 */
public class X.hostSummaryByStatementType  implements java.io.Serializable {


     private X.hostSummaryByStatementTypeId id;

    public X.hostSummaryByStatementType() {
    }

    public X.hostSummaryByStatementType(X.hostSummaryByStatementTypeId id) {
       this.id = id;
    }
   
    public X.hostSummaryByStatementTypeId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByStatementTypeId id) {
        this.id = id;
    }




}


