package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.hostSummaryByFileIoId;

/**
 * X.hostSummaryByFileIo generated by hbm2java
 */
public class X.hostSummaryByFileIo  implements java.io.Serializable {


     private X.hostSummaryByFileIoId id;

    public X.hostSummaryByFileIo() {
    }

    public X.hostSummaryByFileIo(X.hostSummaryByFileIoId id) {
       this.id = id;
    }
   
    public X.hostSummaryByFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByFileIoId id) {
        this.id = id;
    }




}


