package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * X.hostSummaryId generated by hbm2java
 */
public class X.hostSummaryId  implements java.io.Serializable {


     private BigInteger currentConnections;
     private BigInteger currentMemory;
     private BigInteger fileIoLatency;
     private BigInteger fileIos;
     private String host;
     private BigDecimal statementAvgLatency;
     private BigInteger statementLatency;
     private BigInteger statements;
     private BigInteger tableScans;
     private BigInteger totalConnections;
     private BigInteger totalMemoryAllocated;
     private long uniqueUsers;

    public X.hostSummaryId() {
    }

	
    public X.hostSummaryId(long uniqueUsers) {
        this.uniqueUsers = uniqueUsers;
    }
    public X.hostSummaryId(BigInteger currentConnections, BigInteger currentMemory, BigInteger fileIoLatency, BigInteger fileIos, String host, BigDecimal statementAvgLatency, BigInteger statementLatency, BigInteger statements, BigInteger tableScans, BigInteger totalConnections, BigInteger totalMemoryAllocated, long uniqueUsers) {
       this.currentConnections = currentConnections;
       this.currentMemory = currentMemory;
       this.fileIoLatency = fileIoLatency;
       this.fileIos = fileIos;
       this.host = host;
       this.statementAvgLatency = statementAvgLatency;
       this.statementLatency = statementLatency;
       this.statements = statements;
       this.tableScans = tableScans;
       this.totalConnections = totalConnections;
       this.totalMemoryAllocated = totalMemoryAllocated;
       this.uniqueUsers = uniqueUsers;
    }
   
    public BigInteger getCurrentConnections() {
        return this.currentConnections;
    }
    
    public void setCurrentConnections(BigInteger currentConnections) {
        this.currentConnections = currentConnections;
    }
    public BigInteger getCurrentMemory() {
        return this.currentMemory;
    }
    
    public void setCurrentMemory(BigInteger currentMemory) {
        this.currentMemory = currentMemory;
    }
    public BigInteger getFileIoLatency() {
        return this.fileIoLatency;
    }
    
    public void setFileIoLatency(BigInteger fileIoLatency) {
        this.fileIoLatency = fileIoLatency;
    }
    public BigInteger getFileIos() {
        return this.fileIos;
    }
    
    public void setFileIos(BigInteger fileIos) {
        this.fileIos = fileIos;
    }
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public BigDecimal getStatementAvgLatency() {
        return this.statementAvgLatency;
    }
    
    public void setStatementAvgLatency(BigDecimal statementAvgLatency) {
        this.statementAvgLatency = statementAvgLatency;
    }
    public BigInteger getStatementLatency() {
        return this.statementLatency;
    }
    
    public void setStatementLatency(BigInteger statementLatency) {
        this.statementLatency = statementLatency;
    }
    public BigInteger getStatements() {
        return this.statements;
    }
    
    public void setStatements(BigInteger statements) {
        this.statements = statements;
    }
    public BigInteger getTableScans() {
        return this.tableScans;
    }
    
    public void setTableScans(BigInteger tableScans) {
        this.tableScans = tableScans;
    }
    public BigInteger getTotalConnections() {
        return this.totalConnections;
    }
    
    public void setTotalConnections(BigInteger totalConnections) {
        this.totalConnections = totalConnections;
    }
    public BigInteger getTotalMemoryAllocated() {
        return this.totalMemoryAllocated;
    }
    
    public void setTotalMemoryAllocated(BigInteger totalMemoryAllocated) {
        this.totalMemoryAllocated = totalMemoryAllocated;
    }
    public long getUniqueUsers() {
        return this.uniqueUsers;
    }
    
    public void setUniqueUsers(long uniqueUsers) {
        this.uniqueUsers = uniqueUsers;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.hostSummaryId) ) return false;
		 X.hostSummaryId castOther = ( X.hostSummaryId ) other; 
         
		 return ( (this.getCurrentConnections()==castOther.getCurrentConnections()) || ( this.getCurrentConnections()!=null && castOther.getCurrentConnections()!=null && this.getCurrentConnections().equals(castOther.getCurrentConnections()) ) )
 && ( (this.getCurrentMemory()==castOther.getCurrentMemory()) || ( this.getCurrentMemory()!=null && castOther.getCurrentMemory()!=null && this.getCurrentMemory().equals(castOther.getCurrentMemory()) ) )
 && ( (this.getFileIoLatency()==castOther.getFileIoLatency()) || ( this.getFileIoLatency()!=null && castOther.getFileIoLatency()!=null && this.getFileIoLatency().equals(castOther.getFileIoLatency()) ) )
 && ( (this.getFileIos()==castOther.getFileIos()) || ( this.getFileIos()!=null && castOther.getFileIos()!=null && this.getFileIos().equals(castOther.getFileIos()) ) )
 && ( (this.getHost()==castOther.getHost()) || ( this.getHost()!=null && castOther.getHost()!=null && this.getHost().equals(castOther.getHost()) ) )
 && ( (this.getStatementAvgLatency()==castOther.getStatementAvgLatency()) || ( this.getStatementAvgLatency()!=null && castOther.getStatementAvgLatency()!=null && this.getStatementAvgLatency().equals(castOther.getStatementAvgLatency()) ) )
 && ( (this.getStatementLatency()==castOther.getStatementLatency()) || ( this.getStatementLatency()!=null && castOther.getStatementLatency()!=null && this.getStatementLatency().equals(castOther.getStatementLatency()) ) )
 && ( (this.getStatements()==castOther.getStatements()) || ( this.getStatements()!=null && castOther.getStatements()!=null && this.getStatements().equals(castOther.getStatements()) ) )
 && ( (this.getTableScans()==castOther.getTableScans()) || ( this.getTableScans()!=null && castOther.getTableScans()!=null && this.getTableScans().equals(castOther.getTableScans()) ) )
 && ( (this.getTotalConnections()==castOther.getTotalConnections()) || ( this.getTotalConnections()!=null && castOther.getTotalConnections()!=null && this.getTotalConnections().equals(castOther.getTotalConnections()) ) )
 && ( (this.getTotalMemoryAllocated()==castOther.getTotalMemoryAllocated()) || ( this.getTotalMemoryAllocated()!=null && castOther.getTotalMemoryAllocated()!=null && this.getTotalMemoryAllocated().equals(castOther.getTotalMemoryAllocated()) ) )
 && (this.getUniqueUsers()==castOther.getUniqueUsers());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCurrentConnections() == null ? 0 : this.getCurrentConnections().hashCode() );
         result = 37 * result + ( getCurrentMemory() == null ? 0 : this.getCurrentMemory().hashCode() );
         result = 37 * result + ( getFileIoLatency() == null ? 0 : this.getFileIoLatency().hashCode() );
         result = 37 * result + ( getFileIos() == null ? 0 : this.getFileIos().hashCode() );
         result = 37 * result + ( getHost() == null ? 0 : this.getHost().hashCode() );
         result = 37 * result + ( getStatementAvgLatency() == null ? 0 : this.getStatementAvgLatency().hashCode() );
         result = 37 * result + ( getStatementLatency() == null ? 0 : this.getStatementLatency().hashCode() );
         result = 37 * result + ( getStatements() == null ? 0 : this.getStatements().hashCode() );
         result = 37 * result + ( getTableScans() == null ? 0 : this.getTableScans().hashCode() );
         result = 37 * result + ( getTotalConnections() == null ? 0 : this.getTotalConnections().hashCode() );
         result = 37 * result + ( getTotalMemoryAllocated() == null ? 0 : this.getTotalMemoryAllocated().hashCode() );
         result = 37 * result + (int) this.getUniqueUsers();
         return result;
   }   


}


