package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.hostSummaryByFileIoTypeId;

/**
 * X.hostSummaryByFileIoType generated by hbm2java
 */
public class X.hostSummaryByFileIoType  implements java.io.Serializable {


     private X.hostSummaryByFileIoTypeId id;

    public X.hostSummaryByFileIoType() {
    }

    public X.hostSummaryByFileIoType(X.hostSummaryByFileIoTypeId id) {
       this.id = id;
    }
   
    public X.hostSummaryByFileIoTypeId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByFileIoTypeId id) {
        this.id = id;
    }




}


