package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.hostSummaryByStagesId;

/**
 * X.hostSummaryByStages generated by hbm2java
 */
public class X.hostSummaryByStages  implements java.io.Serializable {


     private X.hostSummaryByStagesId id;

    public X.hostSummaryByStages() {
    }

    public X.hostSummaryByStages(X.hostSummaryByStagesId id) {
       this.id = id;
    }
   
    public X.hostSummaryByStagesId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByStagesId id) {
        this.id = id;
    }




}


