package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import java.sql.Time;
import java.sql.Timestamp;

/**
 * X.innodbLockWaitsId generated by hbm2java
 */
public class X.innodbLockWaitsId  implements java.io.Serializable {


     private String blockingLockId;
     private String blockingLockMode;
     private long blockingPid;
     private String blockingQuery;
     private Time blockingTrxAge;
     private long blockingTrxId;
     private long blockingTrxRowsLocked;
     private long blockingTrxRowsModified;
     private Timestamp blockingTrxStarted;
     private String lockedIndex;
     private String lockedTable;
     private String lockedTableName;
     private String lockedTablePartition;
     private String lockedTableSchema;
     private String lockedTableSubpartition;
     private String lockedType;
     private String sqlKillBlockingConnection;
     private String sqlKillBlockingQuery;
     private Time waitAge;
     private Long waitAgeSecs;
     private Timestamp waitStarted;
     private String waitingLockId;
     private String waitingLockMode;
     private long waitingPid;
     private String waitingQuery;
     private Time waitingTrxAge;
     private long waitingTrxId;
     private long waitingTrxRowsLocked;
     private long waitingTrxRowsModified;
     private Timestamp waitingTrxStarted;

    public X.innodbLockWaitsId() {
    }

	
    public X.innodbLockWaitsId(String blockingLockId, String blockingLockMode, long blockingPid, long blockingTrxId, long blockingTrxRowsLocked, long blockingTrxRowsModified, Timestamp blockingTrxStarted, String lockedType, String sqlKillBlockingConnection, String sqlKillBlockingQuery, String waitingLockId, String waitingLockMode, long waitingPid, long waitingTrxId, long waitingTrxRowsLocked, long waitingTrxRowsModified, Timestamp waitingTrxStarted) {
        this.blockingLockId = blockingLockId;
        this.blockingLockMode = blockingLockMode;
        this.blockingPid = blockingPid;
        this.blockingTrxId = blockingTrxId;
        this.blockingTrxRowsLocked = blockingTrxRowsLocked;
        this.blockingTrxRowsModified = blockingTrxRowsModified;
        this.blockingTrxStarted = blockingTrxStarted;
        this.lockedType = lockedType;
        this.sqlKillBlockingConnection = sqlKillBlockingConnection;
        this.sqlKillBlockingQuery = sqlKillBlockingQuery;
        this.waitingLockId = waitingLockId;
        this.waitingLockMode = waitingLockMode;
        this.waitingPid = waitingPid;
        this.waitingTrxId = waitingTrxId;
        this.waitingTrxRowsLocked = waitingTrxRowsLocked;
        this.waitingTrxRowsModified = waitingTrxRowsModified;
        this.waitingTrxStarted = waitingTrxStarted;
    }
    public X.innodbLockWaitsId(String blockingLockId, String blockingLockMode, long blockingPid, String blockingQuery, Time blockingTrxAge, long blockingTrxId, long blockingTrxRowsLocked, long blockingTrxRowsModified, Timestamp blockingTrxStarted, String lockedIndex, String lockedTable, String lockedTableName, String lockedTablePartition, String lockedTableSchema, String lockedTableSubpartition, String lockedType, String sqlKillBlockingConnection, String sqlKillBlockingQuery, Time waitAge, Long waitAgeSecs, Timestamp waitStarted, String waitingLockId, String waitingLockMode, long waitingPid, String waitingQuery, Time waitingTrxAge, long waitingTrxId, long waitingTrxRowsLocked, long waitingTrxRowsModified, Timestamp waitingTrxStarted) {
       this.blockingLockId = blockingLockId;
       this.blockingLockMode = blockingLockMode;
       this.blockingPid = blockingPid;
       this.blockingQuery = blockingQuery;
       this.blockingTrxAge = blockingTrxAge;
       this.blockingTrxId = blockingTrxId;
       this.blockingTrxRowsLocked = blockingTrxRowsLocked;
       this.blockingTrxRowsModified = blockingTrxRowsModified;
       this.blockingTrxStarted = blockingTrxStarted;
       this.lockedIndex = lockedIndex;
       this.lockedTable = lockedTable;
       this.lockedTableName = lockedTableName;
       this.lockedTablePartition = lockedTablePartition;
       this.lockedTableSchema = lockedTableSchema;
       this.lockedTableSubpartition = lockedTableSubpartition;
       this.lockedType = lockedType;
       this.sqlKillBlockingConnection = sqlKillBlockingConnection;
       this.sqlKillBlockingQuery = sqlKillBlockingQuery;
       this.waitAge = waitAge;
       this.waitAgeSecs = waitAgeSecs;
       this.waitStarted = waitStarted;
       this.waitingLockId = waitingLockId;
       this.waitingLockMode = waitingLockMode;
       this.waitingPid = waitingPid;
       this.waitingQuery = waitingQuery;
       this.waitingTrxAge = waitingTrxAge;
       this.waitingTrxId = waitingTrxId;
       this.waitingTrxRowsLocked = waitingTrxRowsLocked;
       this.waitingTrxRowsModified = waitingTrxRowsModified;
       this.waitingTrxStarted = waitingTrxStarted;
    }
   
    public String getBlockingLockId() {
        return this.blockingLockId;
    }
    
    public void setBlockingLockId(String blockingLockId) {
        this.blockingLockId = blockingLockId;
    }
    public String getBlockingLockMode() {
        return this.blockingLockMode;
    }
    
    public void setBlockingLockMode(String blockingLockMode) {
        this.blockingLockMode = blockingLockMode;
    }
    public long getBlockingPid() {
        return this.blockingPid;
    }
    
    public void setBlockingPid(long blockingPid) {
        this.blockingPid = blockingPid;
    }
    public String getBlockingQuery() {
        return this.blockingQuery;
    }
    
    public void setBlockingQuery(String blockingQuery) {
        this.blockingQuery = blockingQuery;
    }
    public Time getBlockingTrxAge() {
        return this.blockingTrxAge;
    }
    
    public void setBlockingTrxAge(Time blockingTrxAge) {
        this.blockingTrxAge = blockingTrxAge;
    }
    public long getBlockingTrxId() {
        return this.blockingTrxId;
    }
    
    public void setBlockingTrxId(long blockingTrxId) {
        this.blockingTrxId = blockingTrxId;
    }
    public long getBlockingTrxRowsLocked() {
        return this.blockingTrxRowsLocked;
    }
    
    public void setBlockingTrxRowsLocked(long blockingTrxRowsLocked) {
        this.blockingTrxRowsLocked = blockingTrxRowsLocked;
    }
    public long getBlockingTrxRowsModified() {
        return this.blockingTrxRowsModified;
    }
    
    public void setBlockingTrxRowsModified(long blockingTrxRowsModified) {
        this.blockingTrxRowsModified = blockingTrxRowsModified;
    }
    public Timestamp getBlockingTrxStarted() {
        return this.blockingTrxStarted;
    }
    
    public void setBlockingTrxStarted(Timestamp blockingTrxStarted) {
        this.blockingTrxStarted = blockingTrxStarted;
    }
    public String getLockedIndex() {
        return this.lockedIndex;
    }
    
    public void setLockedIndex(String lockedIndex) {
        this.lockedIndex = lockedIndex;
    }
    public String getLockedTable() {
        return this.lockedTable;
    }
    
    public void setLockedTable(String lockedTable) {
        this.lockedTable = lockedTable;
    }
    public String getLockedTableName() {
        return this.lockedTableName;
    }
    
    public void setLockedTableName(String lockedTableName) {
        this.lockedTableName = lockedTableName;
    }
    public String getLockedTablePartition() {
        return this.lockedTablePartition;
    }
    
    public void setLockedTablePartition(String lockedTablePartition) {
        this.lockedTablePartition = lockedTablePartition;
    }
    public String getLockedTableSchema() {
        return this.lockedTableSchema;
    }
    
    public void setLockedTableSchema(String lockedTableSchema) {
        this.lockedTableSchema = lockedTableSchema;
    }
    public String getLockedTableSubpartition() {
        return this.lockedTableSubpartition;
    }
    
    public void setLockedTableSubpartition(String lockedTableSubpartition) {
        this.lockedTableSubpartition = lockedTableSubpartition;
    }
    public String getLockedType() {
        return this.lockedType;
    }
    
    public void setLockedType(String lockedType) {
        this.lockedType = lockedType;
    }
    public String getSqlKillBlockingConnection() {
        return this.sqlKillBlockingConnection;
    }
    
    public void setSqlKillBlockingConnection(String sqlKillBlockingConnection) {
        this.sqlKillBlockingConnection = sqlKillBlockingConnection;
    }
    public String getSqlKillBlockingQuery() {
        return this.sqlKillBlockingQuery;
    }
    
    public void setSqlKillBlockingQuery(String sqlKillBlockingQuery) {
        this.sqlKillBlockingQuery = sqlKillBlockingQuery;
    }
    public Time getWaitAge() {
        return this.waitAge;
    }
    
    public void setWaitAge(Time waitAge) {
        this.waitAge = waitAge;
    }
    public Long getWaitAgeSecs() {
        return this.waitAgeSecs;
    }
    
    public void setWaitAgeSecs(Long waitAgeSecs) {
        this.waitAgeSecs = waitAgeSecs;
    }
    public Timestamp getWaitStarted() {
        return this.waitStarted;
    }
    
    public void setWaitStarted(Timestamp waitStarted) {
        this.waitStarted = waitStarted;
    }
    public String getWaitingLockId() {
        return this.waitingLockId;
    }
    
    public void setWaitingLockId(String waitingLockId) {
        this.waitingLockId = waitingLockId;
    }
    public String getWaitingLockMode() {
        return this.waitingLockMode;
    }
    
    public void setWaitingLockMode(String waitingLockMode) {
        this.waitingLockMode = waitingLockMode;
    }
    public long getWaitingPid() {
        return this.waitingPid;
    }
    
    public void setWaitingPid(long waitingPid) {
        this.waitingPid = waitingPid;
    }
    public String getWaitingQuery() {
        return this.waitingQuery;
    }
    
    public void setWaitingQuery(String waitingQuery) {
        this.waitingQuery = waitingQuery;
    }
    public Time getWaitingTrxAge() {
        return this.waitingTrxAge;
    }
    
    public void setWaitingTrxAge(Time waitingTrxAge) {
        this.waitingTrxAge = waitingTrxAge;
    }
    public long getWaitingTrxId() {
        return this.waitingTrxId;
    }
    
    public void setWaitingTrxId(long waitingTrxId) {
        this.waitingTrxId = waitingTrxId;
    }
    public long getWaitingTrxRowsLocked() {
        return this.waitingTrxRowsLocked;
    }
    
    public void setWaitingTrxRowsLocked(long waitingTrxRowsLocked) {
        this.waitingTrxRowsLocked = waitingTrxRowsLocked;
    }
    public long getWaitingTrxRowsModified() {
        return this.waitingTrxRowsModified;
    }
    
    public void setWaitingTrxRowsModified(long waitingTrxRowsModified) {
        this.waitingTrxRowsModified = waitingTrxRowsModified;
    }
    public Timestamp getWaitingTrxStarted() {
        return this.waitingTrxStarted;
    }
    
    public void setWaitingTrxStarted(Timestamp waitingTrxStarted) {
        this.waitingTrxStarted = waitingTrxStarted;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.innodbLockWaitsId) ) return false;
		 X.innodbLockWaitsId castOther = ( X.innodbLockWaitsId ) other; 
         
		 return ( (this.getBlockingLockId()==castOther.getBlockingLockId()) || ( this.getBlockingLockId()!=null && castOther.getBlockingLockId()!=null && this.getBlockingLockId().equals(castOther.getBlockingLockId()) ) )
 && ( (this.getBlockingLockMode()==castOther.getBlockingLockMode()) || ( this.getBlockingLockMode()!=null && castOther.getBlockingLockMode()!=null && this.getBlockingLockMode().equals(castOther.getBlockingLockMode()) ) )
 && (this.getBlockingPid()==castOther.getBlockingPid())
 && ( (this.getBlockingQuery()==castOther.getBlockingQuery()) || ( this.getBlockingQuery()!=null && castOther.getBlockingQuery()!=null && this.getBlockingQuery().equals(castOther.getBlockingQuery()) ) )
 && ( (this.getBlockingTrxAge()==castOther.getBlockingTrxAge()) || ( this.getBlockingTrxAge()!=null && castOther.getBlockingTrxAge()!=null && this.getBlockingTrxAge().equals(castOther.getBlockingTrxAge()) ) )
 && (this.getBlockingTrxId()==castOther.getBlockingTrxId())
 && (this.getBlockingTrxRowsLocked()==castOther.getBlockingTrxRowsLocked())
 && (this.getBlockingTrxRowsModified()==castOther.getBlockingTrxRowsModified())
 && ( (this.getBlockingTrxStarted()==castOther.getBlockingTrxStarted()) || ( this.getBlockingTrxStarted()!=null && castOther.getBlockingTrxStarted()!=null && this.getBlockingTrxStarted().equals(castOther.getBlockingTrxStarted()) ) )
 && ( (this.getLockedIndex()==castOther.getLockedIndex()) || ( this.getLockedIndex()!=null && castOther.getLockedIndex()!=null && this.getLockedIndex().equals(castOther.getLockedIndex()) ) )
 && ( (this.getLockedTable()==castOther.getLockedTable()) || ( this.getLockedTable()!=null && castOther.getLockedTable()!=null && this.getLockedTable().equals(castOther.getLockedTable()) ) )
 && ( (this.getLockedTableName()==castOther.getLockedTableName()) || ( this.getLockedTableName()!=null && castOther.getLockedTableName()!=null && this.getLockedTableName().equals(castOther.getLockedTableName()) ) )
 && ( (this.getLockedTablePartition()==castOther.getLockedTablePartition()) || ( this.getLockedTablePartition()!=null && castOther.getLockedTablePartition()!=null && this.getLockedTablePartition().equals(castOther.getLockedTablePartition()) ) )
 && ( (this.getLockedTableSchema()==castOther.getLockedTableSchema()) || ( this.getLockedTableSchema()!=null && castOther.getLockedTableSchema()!=null && this.getLockedTableSchema().equals(castOther.getLockedTableSchema()) ) )
 && ( (this.getLockedTableSubpartition()==castOther.getLockedTableSubpartition()) || ( this.getLockedTableSubpartition()!=null && castOther.getLockedTableSubpartition()!=null && this.getLockedTableSubpartition().equals(castOther.getLockedTableSubpartition()) ) )
 && ( (this.getLockedType()==castOther.getLockedType()) || ( this.getLockedType()!=null && castOther.getLockedType()!=null && this.getLockedType().equals(castOther.getLockedType()) ) )
 && ( (this.getSqlKillBlockingConnection()==castOther.getSqlKillBlockingConnection()) || ( this.getSqlKillBlockingConnection()!=null && castOther.getSqlKillBlockingConnection()!=null && this.getSqlKillBlockingConnection().equals(castOther.getSqlKillBlockingConnection()) ) )
 && ( (this.getSqlKillBlockingQuery()==castOther.getSqlKillBlockingQuery()) || ( this.getSqlKillBlockingQuery()!=null && castOther.getSqlKillBlockingQuery()!=null && this.getSqlKillBlockingQuery().equals(castOther.getSqlKillBlockingQuery()) ) )
 && ( (this.getWaitAge()==castOther.getWaitAge()) || ( this.getWaitAge()!=null && castOther.getWaitAge()!=null && this.getWaitAge().equals(castOther.getWaitAge()) ) )
 && ( (this.getWaitAgeSecs()==castOther.getWaitAgeSecs()) || ( this.getWaitAgeSecs()!=null && castOther.getWaitAgeSecs()!=null && this.getWaitAgeSecs().equals(castOther.getWaitAgeSecs()) ) )
 && ( (this.getWaitStarted()==castOther.getWaitStarted()) || ( this.getWaitStarted()!=null && castOther.getWaitStarted()!=null && this.getWaitStarted().equals(castOther.getWaitStarted()) ) )
 && ( (this.getWaitingLockId()==castOther.getWaitingLockId()) || ( this.getWaitingLockId()!=null && castOther.getWaitingLockId()!=null && this.getWaitingLockId().equals(castOther.getWaitingLockId()) ) )
 && ( (this.getWaitingLockMode()==castOther.getWaitingLockMode()) || ( this.getWaitingLockMode()!=null && castOther.getWaitingLockMode()!=null && this.getWaitingLockMode().equals(castOther.getWaitingLockMode()) ) )
 && (this.getWaitingPid()==castOther.getWaitingPid())
 && ( (this.getWaitingQuery()==castOther.getWaitingQuery()) || ( this.getWaitingQuery()!=null && castOther.getWaitingQuery()!=null && this.getWaitingQuery().equals(castOther.getWaitingQuery()) ) )
 && ( (this.getWaitingTrxAge()==castOther.getWaitingTrxAge()) || ( this.getWaitingTrxAge()!=null && castOther.getWaitingTrxAge()!=null && this.getWaitingTrxAge().equals(castOther.getWaitingTrxAge()) ) )
 && (this.getWaitingTrxId()==castOther.getWaitingTrxId())
 && (this.getWaitingTrxRowsLocked()==castOther.getWaitingTrxRowsLocked())
 && (this.getWaitingTrxRowsModified()==castOther.getWaitingTrxRowsModified())
 && ( (this.getWaitingTrxStarted()==castOther.getWaitingTrxStarted()) || ( this.getWaitingTrxStarted()!=null && castOther.getWaitingTrxStarted()!=null && this.getWaitingTrxStarted().equals(castOther.getWaitingTrxStarted()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBlockingLockId() == null ? 0 : this.getBlockingLockId().hashCode() );
         result = 37 * result + ( getBlockingLockMode() == null ? 0 : this.getBlockingLockMode().hashCode() );
         result = 37 * result + (int) this.getBlockingPid();
         result = 37 * result + ( getBlockingQuery() == null ? 0 : this.getBlockingQuery().hashCode() );
         result = 37 * result + ( getBlockingTrxAge() == null ? 0 : this.getBlockingTrxAge().hashCode() );
         result = 37 * result + (int) this.getBlockingTrxId();
         result = 37 * result + (int) this.getBlockingTrxRowsLocked();
         result = 37 * result + (int) this.getBlockingTrxRowsModified();
         result = 37 * result + ( getBlockingTrxStarted() == null ? 0 : this.getBlockingTrxStarted().hashCode() );
         result = 37 * result + ( getLockedIndex() == null ? 0 : this.getLockedIndex().hashCode() );
         result = 37 * result + ( getLockedTable() == null ? 0 : this.getLockedTable().hashCode() );
         result = 37 * result + ( getLockedTableName() == null ? 0 : this.getLockedTableName().hashCode() );
         result = 37 * result + ( getLockedTablePartition() == null ? 0 : this.getLockedTablePartition().hashCode() );
         result = 37 * result + ( getLockedTableSchema() == null ? 0 : this.getLockedTableSchema().hashCode() );
         result = 37 * result + ( getLockedTableSubpartition() == null ? 0 : this.getLockedTableSubpartition().hashCode() );
         result = 37 * result + ( getLockedType() == null ? 0 : this.getLockedType().hashCode() );
         result = 37 * result + ( getSqlKillBlockingConnection() == null ? 0 : this.getSqlKillBlockingConnection().hashCode() );
         result = 37 * result + ( getSqlKillBlockingQuery() == null ? 0 : this.getSqlKillBlockingQuery().hashCode() );
         result = 37 * result + ( getWaitAge() == null ? 0 : this.getWaitAge().hashCode() );
         result = 37 * result + ( getWaitAgeSecs() == null ? 0 : this.getWaitAgeSecs().hashCode() );
         result = 37 * result + ( getWaitStarted() == null ? 0 : this.getWaitStarted().hashCode() );
         result = 37 * result + ( getWaitingLockId() == null ? 0 : this.getWaitingLockId().hashCode() );
         result = 37 * result + ( getWaitingLockMode() == null ? 0 : this.getWaitingLockMode().hashCode() );
         result = 37 * result + (int) this.getWaitingPid();
         result = 37 * result + ( getWaitingQuery() == null ? 0 : this.getWaitingQuery().hashCode() );
         result = 37 * result + ( getWaitingTrxAge() == null ? 0 : this.getWaitingTrxAge().hashCode() );
         result = 37 * result + (int) this.getWaitingTrxId();
         result = 37 * result + (int) this.getWaitingTrxRowsLocked();
         result = 37 * result + (int) this.getWaitingTrxRowsModified();
         result = 37 * result + ( getWaitingTrxStarted() == null ? 0 : this.getWaitingTrxStarted().hashCode() );
         return result;
   }   


}


