package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.innodbBufferStatsBySchemaId;

/**
 * X.innodbBufferStatsBySchema generated by hbm2java
 */
public class X.innodbBufferStatsBySchema  implements java.io.Serializable {


     private X.innodbBufferStatsBySchemaId id;

    public X.innodbBufferStatsBySchema() {
    }

    public X.innodbBufferStatsBySchema(X.innodbBufferStatsBySchemaId id) {
       this.id = id;
    }
   
    public X.innodbBufferStatsBySchemaId getId() {
        return this.id;
    }
    
    public void setId(X.innodbBufferStatsBySchemaId id) {
        this.id = id;
    }




}


