package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.ioGlobalByWaitByBytesId;

/**
 * X.ioGlobalByWaitByBytes generated by hbm2java
 */
public class X.ioGlobalByWaitByBytes  implements java.io.Serializable {


     private X.ioGlobalByWaitByBytesId id;

    public X.ioGlobalByWaitByBytes() {
    }

    public X.ioGlobalByWaitByBytes(X.ioGlobalByWaitByBytesId id) {
       this.id = id;
    }
   
    public X.ioGlobalByWaitByBytesId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByWaitByBytesId id) {
        this.id = id;
    }




}


