package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import java.math.BigDecimal;

/**
 * X.ioGlobalByWaitByLatencyId generated by hbm2java
 */
public class X.ioGlobalByWaitByLatencyId  implements java.io.Serializable {


     private long avgLatency;
     private BigDecimal avgRead;
     private BigDecimal avgWritten;
     private long countRead;
     private long countWrite;
     private String eventName;
     private long maxLatency;
     private long miscLatency;
     private long readLatency;
     private long total;
     private long totalLatency;
     private long totalRead;
     private long totalWritten;
     private long writeLatency;

    public X.ioGlobalByWaitByLatencyId() {
    }

	
    public X.ioGlobalByWaitByLatencyId(long avgLatency, BigDecimal avgRead, BigDecimal avgWritten, long countRead, long countWrite, long maxLatency, long miscLatency, long readLatency, long total, long totalLatency, long totalRead, long totalWritten, long writeLatency) {
        this.avgLatency = avgLatency;
        this.avgRead = avgRead;
        this.avgWritten = avgWritten;
        this.countRead = countRead;
        this.countWrite = countWrite;
        this.maxLatency = maxLatency;
        this.miscLatency = miscLatency;
        this.readLatency = readLatency;
        this.total = total;
        this.totalLatency = totalLatency;
        this.totalRead = totalRead;
        this.totalWritten = totalWritten;
        this.writeLatency = writeLatency;
    }
    public X.ioGlobalByWaitByLatencyId(long avgLatency, BigDecimal avgRead, BigDecimal avgWritten, long countRead, long countWrite, String eventName, long maxLatency, long miscLatency, long readLatency, long total, long totalLatency, long totalRead, long totalWritten, long writeLatency) {
       this.avgLatency = avgLatency;
       this.avgRead = avgRead;
       this.avgWritten = avgWritten;
       this.countRead = countRead;
       this.countWrite = countWrite;
       this.eventName = eventName;
       this.maxLatency = maxLatency;
       this.miscLatency = miscLatency;
       this.readLatency = readLatency;
       this.total = total;
       this.totalLatency = totalLatency;
       this.totalRead = totalRead;
       this.totalWritten = totalWritten;
       this.writeLatency = writeLatency;
    }
   
    public long getAvgLatency() {
        return this.avgLatency;
    }
    
    public void setAvgLatency(long avgLatency) {
        this.avgLatency = avgLatency;
    }
    public BigDecimal getAvgRead() {
        return this.avgRead;
    }
    
    public void setAvgRead(BigDecimal avgRead) {
        this.avgRead = avgRead;
    }
    public BigDecimal getAvgWritten() {
        return this.avgWritten;
    }
    
    public void setAvgWritten(BigDecimal avgWritten) {
        this.avgWritten = avgWritten;
    }
    public long getCountRead() {
        return this.countRead;
    }
    
    public void setCountRead(long countRead) {
        this.countRead = countRead;
    }
    public long getCountWrite() {
        return this.countWrite;
    }
    
    public void setCountWrite(long countWrite) {
        this.countWrite = countWrite;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public long getMaxLatency() {
        return this.maxLatency;
    }
    
    public void setMaxLatency(long maxLatency) {
        this.maxLatency = maxLatency;
    }
    public long getMiscLatency() {
        return this.miscLatency;
    }
    
    public void setMiscLatency(long miscLatency) {
        this.miscLatency = miscLatency;
    }
    public long getReadLatency() {
        return this.readLatency;
    }
    
    public void setReadLatency(long readLatency) {
        this.readLatency = readLatency;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }
    public long getTotalLatency() {
        return this.totalLatency;
    }
    
    public void setTotalLatency(long totalLatency) {
        this.totalLatency = totalLatency;
    }
    public long getTotalRead() {
        return this.totalRead;
    }
    
    public void setTotalRead(long totalRead) {
        this.totalRead = totalRead;
    }
    public long getTotalWritten() {
        return this.totalWritten;
    }
    
    public void setTotalWritten(long totalWritten) {
        this.totalWritten = totalWritten;
    }
    public long getWriteLatency() {
        return this.writeLatency;
    }
    
    public void setWriteLatency(long writeLatency) {
        this.writeLatency = writeLatency;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.ioGlobalByWaitByLatencyId) ) return false;
		 X.ioGlobalByWaitByLatencyId castOther = ( X.ioGlobalByWaitByLatencyId ) other; 
         
		 return (this.getAvgLatency()==castOther.getAvgLatency())
 && ( (this.getAvgRead()==castOther.getAvgRead()) || ( this.getAvgRead()!=null && castOther.getAvgRead()!=null && this.getAvgRead().equals(castOther.getAvgRead()) ) )
 && ( (this.getAvgWritten()==castOther.getAvgWritten()) || ( this.getAvgWritten()!=null && castOther.getAvgWritten()!=null && this.getAvgWritten().equals(castOther.getAvgWritten()) ) )
 && (this.getCountRead()==castOther.getCountRead())
 && (this.getCountWrite()==castOther.getCountWrite())
 && ( (this.getEventName()==castOther.getEventName()) || ( this.getEventName()!=null && castOther.getEventName()!=null && this.getEventName().equals(castOther.getEventName()) ) )
 && (this.getMaxLatency()==castOther.getMaxLatency())
 && (this.getMiscLatency()==castOther.getMiscLatency())
 && (this.getReadLatency()==castOther.getReadLatency())
 && (this.getTotal()==castOther.getTotal())
 && (this.getTotalLatency()==castOther.getTotalLatency())
 && (this.getTotalRead()==castOther.getTotalRead())
 && (this.getTotalWritten()==castOther.getTotalWritten())
 && (this.getWriteLatency()==castOther.getWriteLatency());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getAvgLatency();
         result = 37 * result + ( getAvgRead() == null ? 0 : this.getAvgRead().hashCode() );
         result = 37 * result + ( getAvgWritten() == null ? 0 : this.getAvgWritten().hashCode() );
         result = 37 * result + (int) this.getCountRead();
         result = 37 * result + (int) this.getCountWrite();
         result = 37 * result + ( getEventName() == null ? 0 : this.getEventName().hashCode() );
         result = 37 * result + (int) this.getMaxLatency();
         result = 37 * result + (int) this.getMiscLatency();
         result = 37 * result + (int) this.getReadLatency();
         result = 37 * result + (int) this.getTotal();
         result = 37 * result + (int) this.getTotalLatency();
         result = 37 * result + (int) this.getTotalRead();
         result = 37 * result + (int) this.getTotalWritten();
         result = 37 * result + (int) this.getWriteLatency();
         return result;
   }   


}


