package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.ioByThreadByLatencyId;

/**
 * X.ioByThreadByLatency generated by hbm2java
 */
public class X.ioByThreadByLatency  implements java.io.Serializable {


     private X.ioByThreadByLatencyId id;

    public X.ioByThreadByLatency() {
    }

    public X.ioByThreadByLatency(X.ioByThreadByLatencyId id) {
       this.id = id;
    }
   
    public X.ioByThreadByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioByThreadByLatencyId id) {
        this.id = id;
    }




}


