package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.ioGlobalByFileByBytesId;

/**
 * X.ioGlobalByFileByBytes generated by hbm2java
 */
public class X.ioGlobalByFileByBytes  implements java.io.Serializable {


     private X.ioGlobalByFileByBytesId id;

    public X.ioGlobalByFileByBytes() {
    }

    public X.ioGlobalByFileByBytes(X.ioGlobalByFileByBytesId id) {
       this.id = id;
    }
   
    public X.ioGlobalByFileByBytesId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByFileByBytesId id) {
        this.id = id;
    }




}


