package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.ioGlobalByFileByLatencyId;

/**
 * X.ioGlobalByFileByLatency generated by hbm2java
 */
public class X.ioGlobalByFileByLatency  implements java.io.Serializable {


     private X.ioGlobalByFileByLatencyId id;

    public X.ioGlobalByFileByLatency() {
    }

    public X.ioGlobalByFileByLatency(X.ioGlobalByFileByLatencyId id) {
       this.id = id;
    }
   
    public X.ioGlobalByFileByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByFileByLatencyId id) {
        this.id = id;
    }




}


