package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.ioGlobalByWaitByLatencyId;

/**
 * X.ioGlobalByWaitByLatency generated by hbm2java
 */
public class X.ioGlobalByWaitByLatency  implements java.io.Serializable {


     private X.ioGlobalByWaitByLatencyId id;

    public X.ioGlobalByWaitByLatency() {
    }

    public X.ioGlobalByWaitByLatency(X.ioGlobalByWaitByLatencyId id) {
       this.id = id;
    }
   
    public X.ioGlobalByWaitByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByWaitByLatencyId id) {
        this.id = id;
    }




}


