package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import java.math.BigDecimal;

/**
 * X.ioGlobalByFileByBytesId generated by hbm2java
 */
public class X.ioGlobalByFileByBytesId  implements java.io.Serializable {


     private BigDecimal avgRead;
     private BigDecimal avgWrite;
     private long countRead;
     private long countWrite;
     private String file;
     private long total;
     private long totalRead;
     private long totalWritten;
     private BigDecimal writePct;

    public X.ioGlobalByFileByBytesId() {
    }

    public X.ioGlobalByFileByBytesId(BigDecimal avgRead, BigDecimal avgWrite, long countRead, long countWrite, String file, long total, long totalRead, long totalWritten, BigDecimal writePct) {
       this.avgRead = avgRead;
       this.avgWrite = avgWrite;
       this.countRead = countRead;
       this.countWrite = countWrite;
       this.file = file;
       this.total = total;
       this.totalRead = totalRead;
       this.totalWritten = totalWritten;
       this.writePct = writePct;
    }
   
    public BigDecimal getAvgRead() {
        return this.avgRead;
    }
    
    public void setAvgRead(BigDecimal avgRead) {
        this.avgRead = avgRead;
    }
    public BigDecimal getAvgWrite() {
        return this.avgWrite;
    }
    
    public void setAvgWrite(BigDecimal avgWrite) {
        this.avgWrite = avgWrite;
    }
    public long getCountRead() {
        return this.countRead;
    }
    
    public void setCountRead(long countRead) {
        this.countRead = countRead;
    }
    public long getCountWrite() {
        return this.countWrite;
    }
    
    public void setCountWrite(long countWrite) {
        this.countWrite = countWrite;
    }
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }
    public long getTotalRead() {
        return this.totalRead;
    }
    
    public void setTotalRead(long totalRead) {
        this.totalRead = totalRead;
    }
    public long getTotalWritten() {
        return this.totalWritten;
    }
    
    public void setTotalWritten(long totalWritten) {
        this.totalWritten = totalWritten;
    }
    public BigDecimal getWritePct() {
        return this.writePct;
    }
    
    public void setWritePct(BigDecimal writePct) {
        this.writePct = writePct;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.ioGlobalByFileByBytesId) ) return false;
		 X.ioGlobalByFileByBytesId castOther = ( X.ioGlobalByFileByBytesId ) other; 
         
		 return ( (this.getAvgRead()==castOther.getAvgRead()) || ( this.getAvgRead()!=null && castOther.getAvgRead()!=null && this.getAvgRead().equals(castOther.getAvgRead()) ) )
 && ( (this.getAvgWrite()==castOther.getAvgWrite()) || ( this.getAvgWrite()!=null && castOther.getAvgWrite()!=null && this.getAvgWrite().equals(castOther.getAvgWrite()) ) )
 && (this.getCountRead()==castOther.getCountRead())
 && (this.getCountWrite()==castOther.getCountWrite())
 && ( (this.getFile()==castOther.getFile()) || ( this.getFile()!=null && castOther.getFile()!=null && this.getFile().equals(castOther.getFile()) ) )
 && (this.getTotal()==castOther.getTotal())
 && (this.getTotalRead()==castOther.getTotalRead())
 && (this.getTotalWritten()==castOther.getTotalWritten())
 && ( (this.getWritePct()==castOther.getWritePct()) || ( this.getWritePct()!=null && castOther.getWritePct()!=null && this.getWritePct().equals(castOther.getWritePct()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAvgRead() == null ? 0 : this.getAvgRead().hashCode() );
         result = 37 * result + ( getAvgWrite() == null ? 0 : this.getAvgWrite().hashCode() );
         result = 37 * result + (int) this.getCountRead();
         result = 37 * result + (int) this.getCountWrite();
         result = 37 * result + ( getFile() == null ? 0 : this.getFile().hashCode() );
         result = 37 * result + (int) this.getTotal();
         result = 37 * result + (int) this.getTotalRead();
         result = 37 * result + (int) this.getTotalWritten();
         result = 37 * result + ( getWritePct() == null ? 0 : this.getWritePct().hashCode() );
         return result;
   }   


}


