package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final



/**
 * X.latestFileIoId generated by hbm2java
 */
public class X.latestFileIoId  implements java.io.Serializable {


     private String file;
     private Long latency;
     private String operation;
     private Long requested;
     private String thread;

    public X.latestFileIoId() {
    }

	
    public X.latestFileIoId(String operation) {
        this.operation = operation;
    }
    public X.latestFileIoId(String file, Long latency, String operation, Long requested, String thread) {
       this.file = file;
       this.latency = latency;
       this.operation = operation;
       this.requested = requested;
       this.thread = thread;
    }
   
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    public Long getLatency() {
        return this.latency;
    }
    
    public void setLatency(Long latency) {
        this.latency = latency;
    }
    public String getOperation() {
        return this.operation;
    }
    
    public void setOperation(String operation) {
        this.operation = operation;
    }
    public Long getRequested() {
        return this.requested;
    }
    
    public void setRequested(Long requested) {
        this.requested = requested;
    }
    public String getThread() {
        return this.thread;
    }
    
    public void setThread(String thread) {
        this.thread = thread;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.latestFileIoId) ) return false;
		 X.latestFileIoId castOther = ( X.latestFileIoId ) other; 
         
		 return ( (this.getFile()==castOther.getFile()) || ( this.getFile()!=null && castOther.getFile()!=null && this.getFile().equals(castOther.getFile()) ) )
 && ( (this.getLatency()==castOther.getLatency()) || ( this.getLatency()!=null && castOther.getLatency()!=null && this.getLatency().equals(castOther.getLatency()) ) )
 && ( (this.getOperation()==castOther.getOperation()) || ( this.getOperation()!=null && castOther.getOperation()!=null && this.getOperation().equals(castOther.getOperation()) ) )
 && ( (this.getRequested()==castOther.getRequested()) || ( this.getRequested()!=null && castOther.getRequested()!=null && this.getRequested().equals(castOther.getRequested()) ) )
 && ( (this.getThread()==castOther.getThread()) || ( this.getThread()!=null && castOther.getThread()!=null && this.getThread().equals(castOther.getThread()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFile() == null ? 0 : this.getFile().hashCode() );
         result = 37 * result + ( getLatency() == null ? 0 : this.getLatency().hashCode() );
         result = 37 * result + ( getOperation() == null ? 0 : this.getOperation().hashCode() );
         result = 37 * result + ( getRequested() == null ? 0 : this.getRequested().hashCode() );
         result = 37 * result + ( getThread() == null ? 0 : this.getThread().hashCode() );
         return result;
   }   


}


