package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.latestFileIoId;

/**
 * X.latestFileIo generated by hbm2java
 */
public class X.latestFileIo  implements java.io.Serializable {


     private X.latestFileIoId id;

    public X.latestFileIo() {
    }

    public X.latestFileIo(X.latestFileIoId id) {
       this.id = id;
    }
   
    public X.latestFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.latestFileIoId id) {
        this.id = id;
    }




}


