package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.memoryByThreadByCurrentBytesId;

/**
 * X.memoryByThreadByCurrentBytes generated by hbm2java
 */
public class X.memoryByThreadByCurrentBytes  implements java.io.Serializable {


     private X.memoryByThreadByCurrentBytesId id;

    public X.memoryByThreadByCurrentBytes() {
    }

    public X.memoryByThreadByCurrentBytes(X.memoryByThreadByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryByThreadByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryByThreadByCurrentBytesId id) {
        this.id = id;
    }




}


