package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import java.math.BigDecimal;

/**
 * X.memoryGlobalByCurrentBytesId generated by hbm2java
 */
public class X.memoryGlobalByCurrentBytesId  implements java.io.Serializable {


     private long currentAlloc;
     private BigDecimal currentAvgAlloc;
     private long currentCount;
     private String eventName;
     private long highAlloc;
     private BigDecimal highAvgAlloc;
     private long highCount;

    public X.memoryGlobalByCurrentBytesId() {
    }

    public X.memoryGlobalByCurrentBytesId(long currentAlloc, BigDecimal currentAvgAlloc, long currentCount, String eventName, long highAlloc, BigDecimal highAvgAlloc, long highCount) {
       this.currentAlloc = currentAlloc;
       this.currentAvgAlloc = currentAvgAlloc;
       this.currentCount = currentCount;
       this.eventName = eventName;
       this.highAlloc = highAlloc;
       this.highAvgAlloc = highAvgAlloc;
       this.highCount = highCount;
    }
   
    public long getCurrentAlloc() {
        return this.currentAlloc;
    }
    
    public void setCurrentAlloc(long currentAlloc) {
        this.currentAlloc = currentAlloc;
    }
    public BigDecimal getCurrentAvgAlloc() {
        return this.currentAvgAlloc;
    }
    
    public void setCurrentAvgAlloc(BigDecimal currentAvgAlloc) {
        this.currentAvgAlloc = currentAvgAlloc;
    }
    public long getCurrentCount() {
        return this.currentCount;
    }
    
    public void setCurrentCount(long currentCount) {
        this.currentCount = currentCount;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public long getHighAlloc() {
        return this.highAlloc;
    }
    
    public void setHighAlloc(long highAlloc) {
        this.highAlloc = highAlloc;
    }
    public BigDecimal getHighAvgAlloc() {
        return this.highAvgAlloc;
    }
    
    public void setHighAvgAlloc(BigDecimal highAvgAlloc) {
        this.highAvgAlloc = highAvgAlloc;
    }
    public long getHighCount() {
        return this.highCount;
    }
    
    public void setHighCount(long highCount) {
        this.highCount = highCount;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.memoryGlobalByCurrentBytesId) ) return false;
		 X.memoryGlobalByCurrentBytesId castOther = ( X.memoryGlobalByCurrentBytesId ) other; 
         
		 return (this.getCurrentAlloc()==castOther.getCurrentAlloc())
 && ( (this.getCurrentAvgAlloc()==castOther.getCurrentAvgAlloc()) || ( this.getCurrentAvgAlloc()!=null && castOther.getCurrentAvgAlloc()!=null && this.getCurrentAvgAlloc().equals(castOther.getCurrentAvgAlloc()) ) )
 && (this.getCurrentCount()==castOther.getCurrentCount())
 && ( (this.getEventName()==castOther.getEventName()) || ( this.getEventName()!=null && castOther.getEventName()!=null && this.getEventName().equals(castOther.getEventName()) ) )
 && (this.getHighAlloc()==castOther.getHighAlloc())
 && ( (this.getHighAvgAlloc()==castOther.getHighAvgAlloc()) || ( this.getHighAvgAlloc()!=null && castOther.getHighAvgAlloc()!=null && this.getHighAvgAlloc().equals(castOther.getHighAvgAlloc()) ) )
 && (this.getHighCount()==castOther.getHighCount());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCurrentAlloc();
         result = 37 * result + ( getCurrentAvgAlloc() == null ? 0 : this.getCurrentAvgAlloc().hashCode() );
         result = 37 * result + (int) this.getCurrentCount();
         result = 37 * result + ( getEventName() == null ? 0 : this.getEventName().hashCode() );
         result = 37 * result + (int) this.getHighAlloc();
         result = 37 * result + ( getHighAvgAlloc() == null ? 0 : this.getHighAvgAlloc().hashCode() );
         result = 37 * result + (int) this.getHighCount();
         return result;
   }   


}


