package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.memoryGlobalByCurrentBytesId;

/**
 * X.memoryGlobalByCurrentBytes generated by hbm2java
 */
public class X.memoryGlobalByCurrentBytes  implements java.io.Serializable {


     private X.memoryGlobalByCurrentBytesId id;

    public X.memoryGlobalByCurrentBytes() {
    }

    public X.memoryGlobalByCurrentBytes(X.memoryGlobalByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryGlobalByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryGlobalByCurrentBytesId id) {
        this.id = id;
    }




}


