package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import java.math.BigInteger;

/**
 * X.memoryGlobalTotal generated by hbm2java
 */
public class X.memoryGlobalTotal  implements java.io.Serializable {


     private BigInteger totalAllocated;

    public X.memoryGlobalTotal() {
    }

    public X.memoryGlobalTotal(BigInteger totalAllocated) {
       this.totalAllocated = totalAllocated;
    }
   
    public BigInteger getTotalAllocated() {
        return this.totalAllocated;
    }
    
    public void setTotalAllocated(BigInteger totalAllocated) {
        this.totalAllocated = totalAllocated;
    }




}


