package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.memoryByHostByCurrentBytesId;

/**
 * X.memoryByHostByCurrentBytes generated by hbm2java
 */
public class X.memoryByHostByCurrentBytes  implements java.io.Serializable {


     private X.memoryByHostByCurrentBytesId id;

    public X.memoryByHostByCurrentBytes() {
    }

    public X.memoryByHostByCurrentBytes(X.memoryByHostByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryByHostByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryByHostByCurrentBytesId id) {
        this.id = id;
    }




}


