package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.processlistId;

/**
 * X.processlist generated by hbm2java
 */
public class X.processlist  implements java.io.Serializable {


     private X.processlistId id;

    public X.processlist() {
    }

    public X.processlist(X.processlistId id) {
       this.id = id;
    }
   
    public X.processlistId getId() {
        return this.id;
    }
    
    public void setId(X.processlistId id) {
        this.id = id;
    }




}


