package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.psDigest95thPercentileByAvgUsId;

/**
 * X.psDigest95thPercentileByAvgUs generated by hbm2java
 */
public class X.psDigest95thPercentileByAvgUs  implements java.io.Serializable {


     private X.psDigest95thPercentileByAvgUsId id;

    public X.psDigest95thPercentileByAvgUs() {
    }

    public X.psDigest95thPercentileByAvgUs(X.psDigest95thPercentileByAvgUsId id) {
       this.id = id;
    }
   
    public X.psDigest95thPercentileByAvgUsId getId() {
        return this.id;
    }
    
    public void setId(X.psDigest95thPercentileByAvgUsId id) {
        this.id = id;
    }




}


