package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import java.math.BigInteger;

/**
 * X.psDigestAvgLatencyDistributionId generated by hbm2java
 */
public class X.psDigestAvgLatencyDistributionId  implements java.io.Serializable {


     private BigInteger avgUs;
     private long cnt;

    public X.psDigestAvgLatencyDistributionId() {
    }

	
    public X.psDigestAvgLatencyDistributionId(long cnt) {
        this.cnt = cnt;
    }
    public X.psDigestAvgLatencyDistributionId(BigInteger avgUs, long cnt) {
       this.avgUs = avgUs;
       this.cnt = cnt;
    }
   
    public BigInteger getAvgUs() {
        return this.avgUs;
    }
    
    public void setAvgUs(BigInteger avgUs) {
        this.avgUs = avgUs;
    }
    public long getCnt() {
        return this.cnt;
    }
    
    public void setCnt(long cnt) {
        this.cnt = cnt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.psDigestAvgLatencyDistributionId) ) return false;
		 X.psDigestAvgLatencyDistributionId castOther = ( X.psDigestAvgLatencyDistributionId ) other; 
         
		 return ( (this.getAvgUs()==castOther.getAvgUs()) || ( this.getAvgUs()!=null && castOther.getAvgUs()!=null && this.getAvgUs().equals(castOther.getAvgUs()) ) )
 && (this.getCnt()==castOther.getCnt());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAvgUs() == null ? 0 : this.getAvgUs().hashCode() );
         result = 37 * result + (int) this.getCnt();
         return result;
   }   


}


