package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.psSchemaTableStatisticsIoId;

/**
 * X.psSchemaTableStatisticsIo generated by hbm2java
 */
public class X.psSchemaTableStatisticsIo  implements java.io.Serializable {


     private X.psSchemaTableStatisticsIoId id;

    public X.psSchemaTableStatisticsIo() {
    }

    public X.psSchemaTableStatisticsIo(X.psSchemaTableStatisticsIoId id) {
       this.id = id;
    }
   
    public X.psSchemaTableStatisticsIoId getId() {
        return this.id;
    }
    
    public void setId(X.psSchemaTableStatisticsIoId id) {
        this.id = id;
    }




}


