package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.schemaTableStatisticsId;

/**
 * X.schemaTableStatistics generated by hbm2java
 */
public class X.schemaTableStatistics  implements java.io.Serializable {


     private X.schemaTableStatisticsId id;

    public X.schemaTableStatistics() {
    }

    public X.schemaTableStatistics(X.schemaTableStatisticsId id) {
       this.id = id;
    }
   
    public X.schemaTableStatisticsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableStatisticsId id) {
        this.id = id;
    }




}


