package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.schemaTableStatisticsWithBufferId;

/**
 * X.schemaTableStatisticsWithBuffer generated by hbm2java
 */
public class X.schemaTableStatisticsWithBuffer  implements java.io.Serializable {


     private X.schemaTableStatisticsWithBufferId id;

    public X.schemaTableStatisticsWithBuffer() {
    }

    public X.schemaTableStatisticsWithBuffer(X.schemaTableStatisticsWithBufferId id) {
       this.id = id;
    }
   
    public X.schemaTableStatisticsWithBufferId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableStatisticsWithBufferId id) {
        this.id = id;
    }




}


