package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final



/**
 * X.schemaFlattenedKeysId generated by hbm2java
 */
public class X.schemaFlattenedKeysId  implements java.io.Serializable {


     private String indexColumns;
     private String indexName;
     private Integer nonUnique;
     private Long subpartExists;
     private String tableName;
     private String tableSchema;

    public X.schemaFlattenedKeysId() {
    }

    public X.schemaFlattenedKeysId(String indexColumns, String indexName, Integer nonUnique, Long subpartExists, String tableName, String tableSchema) {
       this.indexColumns = indexColumns;
       this.indexName = indexName;
       this.nonUnique = nonUnique;
       this.subpartExists = subpartExists;
       this.tableName = tableName;
       this.tableSchema = tableSchema;
    }
   
    public String getIndexColumns() {
        return this.indexColumns;
    }
    
    public void setIndexColumns(String indexColumns) {
        this.indexColumns = indexColumns;
    }
    public String getIndexName() {
        return this.indexName;
    }
    
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }
    public Integer getNonUnique() {
        return this.nonUnique;
    }
    
    public void setNonUnique(Integer nonUnique) {
        this.nonUnique = nonUnique;
    }
    public Long getSubpartExists() {
        return this.subpartExists;
    }
    
    public void setSubpartExists(Long subpartExists) {
        this.subpartExists = subpartExists;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.schemaFlattenedKeysId) ) return false;
		 X.schemaFlattenedKeysId castOther = ( X.schemaFlattenedKeysId ) other; 
         
		 return ( (this.getIndexColumns()==castOther.getIndexColumns()) || ( this.getIndexColumns()!=null && castOther.getIndexColumns()!=null && this.getIndexColumns().equals(castOther.getIndexColumns()) ) )
 && ( (this.getIndexName()==castOther.getIndexName()) || ( this.getIndexName()!=null && castOther.getIndexName()!=null && this.getIndexName().equals(castOther.getIndexName()) ) )
 && ( (this.getNonUnique()==castOther.getNonUnique()) || ( this.getNonUnique()!=null && castOther.getNonUnique()!=null && this.getNonUnique().equals(castOther.getNonUnique()) ) )
 && ( (this.getSubpartExists()==castOther.getSubpartExists()) || ( this.getSubpartExists()!=null && castOther.getSubpartExists()!=null && this.getSubpartExists().equals(castOther.getSubpartExists()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIndexColumns() == null ? 0 : this.getIndexColumns().hashCode() );
         result = 37 * result + ( getIndexName() == null ? 0 : this.getIndexName().hashCode() );
         result = 37 * result + ( getNonUnique() == null ? 0 : this.getNonUnique().hashCode() );
         result = 37 * result + ( getSubpartExists() == null ? 0 : this.getSubpartExists().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
         return result;
   }   


}


