package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.schemaTablesWithFullTableScansId;

/**
 * X.schemaTablesWithFullTableScans generated by hbm2java
 */
public class X.schemaTablesWithFullTableScans  implements java.io.Serializable {


     private X.schemaTablesWithFullTableScansId id;

    public X.schemaTablesWithFullTableScans() {
    }

    public X.schemaTablesWithFullTableScans(X.schemaTablesWithFullTableScansId id) {
       this.id = id;
    }
   
    public X.schemaTablesWithFullTableScansId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTablesWithFullTableScansId id) {
        this.id = id;
    }




}


