package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final



/**
 * X.schemaTableLockWaitsId generated by hbm2java
 */
public class X.schemaTableLockWaitsId  implements java.io.Serializable {


     private String blockingAccount;
     private String blockingLockDuration;
     private String blockingLockType;
     private Long blockingPid;
     private long blockingThreadId;
     private String objectName;
     private String objectSchema;
     private String sqlKillBlockingConnection;
     private String sqlKillBlockingQuery;
     private String waitingAccount;
     private String waitingLockDuration;
     private String waitingLockType;
     private Long waitingPid;
     private String waitingQuery;
     private Long waitingQueryRowsAffected;
     private Long waitingQueryRowsExamined;
     private Long waitingQuerySecs;
     private long waitingThreadId;

    public X.schemaTableLockWaitsId() {
    }

	
    public X.schemaTableLockWaitsId(String blockingLockDuration, String blockingLockType, long blockingThreadId, String waitingLockDuration, String waitingLockType, long waitingThreadId) {
        this.blockingLockDuration = blockingLockDuration;
        this.blockingLockType = blockingLockType;
        this.blockingThreadId = blockingThreadId;
        this.waitingLockDuration = waitingLockDuration;
        this.waitingLockType = waitingLockType;
        this.waitingThreadId = waitingThreadId;
    }
    public X.schemaTableLockWaitsId(String blockingAccount, String blockingLockDuration, String blockingLockType, Long blockingPid, long blockingThreadId, String objectName, String objectSchema, String sqlKillBlockingConnection, String sqlKillBlockingQuery, String waitingAccount, String waitingLockDuration, String waitingLockType, Long waitingPid, String waitingQuery, Long waitingQueryRowsAffected, Long waitingQueryRowsExamined, Long waitingQuerySecs, long waitingThreadId) {
       this.blockingAccount = blockingAccount;
       this.blockingLockDuration = blockingLockDuration;
       this.blockingLockType = blockingLockType;
       this.blockingPid = blockingPid;
       this.blockingThreadId = blockingThreadId;
       this.objectName = objectName;
       this.objectSchema = objectSchema;
       this.sqlKillBlockingConnection = sqlKillBlockingConnection;
       this.sqlKillBlockingQuery = sqlKillBlockingQuery;
       this.waitingAccount = waitingAccount;
       this.waitingLockDuration = waitingLockDuration;
       this.waitingLockType = waitingLockType;
       this.waitingPid = waitingPid;
       this.waitingQuery = waitingQuery;
       this.waitingQueryRowsAffected = waitingQueryRowsAffected;
       this.waitingQueryRowsExamined = waitingQueryRowsExamined;
       this.waitingQuerySecs = waitingQuerySecs;
       this.waitingThreadId = waitingThreadId;
    }
   
    public String getBlockingAccount() {
        return this.blockingAccount;
    }
    
    public void setBlockingAccount(String blockingAccount) {
        this.blockingAccount = blockingAccount;
    }
    public String getBlockingLockDuration() {
        return this.blockingLockDuration;
    }
    
    public void setBlockingLockDuration(String blockingLockDuration) {
        this.blockingLockDuration = blockingLockDuration;
    }
    public String getBlockingLockType() {
        return this.blockingLockType;
    }
    
    public void setBlockingLockType(String blockingLockType) {
        this.blockingLockType = blockingLockType;
    }
    public Long getBlockingPid() {
        return this.blockingPid;
    }
    
    public void setBlockingPid(Long blockingPid) {
        this.blockingPid = blockingPid;
    }
    public long getBlockingThreadId() {
        return this.blockingThreadId;
    }
    
    public void setBlockingThreadId(long blockingThreadId) {
        this.blockingThreadId = blockingThreadId;
    }
    public String getObjectName() {
        return this.objectName;
    }
    
    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }
    public String getObjectSchema() {
        return this.objectSchema;
    }
    
    public void setObjectSchema(String objectSchema) {
        this.objectSchema = objectSchema;
    }
    public String getSqlKillBlockingConnection() {
        return this.sqlKillBlockingConnection;
    }
    
    public void setSqlKillBlockingConnection(String sqlKillBlockingConnection) {
        this.sqlKillBlockingConnection = sqlKillBlockingConnection;
    }
    public String getSqlKillBlockingQuery() {
        return this.sqlKillBlockingQuery;
    }
    
    public void setSqlKillBlockingQuery(String sqlKillBlockingQuery) {
        this.sqlKillBlockingQuery = sqlKillBlockingQuery;
    }
    public String getWaitingAccount() {
        return this.waitingAccount;
    }
    
    public void setWaitingAccount(String waitingAccount) {
        this.waitingAccount = waitingAccount;
    }
    public String getWaitingLockDuration() {
        return this.waitingLockDuration;
    }
    
    public void setWaitingLockDuration(String waitingLockDuration) {
        this.waitingLockDuration = waitingLockDuration;
    }
    public String getWaitingLockType() {
        return this.waitingLockType;
    }
    
    public void setWaitingLockType(String waitingLockType) {
        this.waitingLockType = waitingLockType;
    }
    public Long getWaitingPid() {
        return this.waitingPid;
    }
    
    public void setWaitingPid(Long waitingPid) {
        this.waitingPid = waitingPid;
    }
    public String getWaitingQuery() {
        return this.waitingQuery;
    }
    
    public void setWaitingQuery(String waitingQuery) {
        this.waitingQuery = waitingQuery;
    }
    public Long getWaitingQueryRowsAffected() {
        return this.waitingQueryRowsAffected;
    }
    
    public void setWaitingQueryRowsAffected(Long waitingQueryRowsAffected) {
        this.waitingQueryRowsAffected = waitingQueryRowsAffected;
    }
    public Long getWaitingQueryRowsExamined() {
        return this.waitingQueryRowsExamined;
    }
    
    public void setWaitingQueryRowsExamined(Long waitingQueryRowsExamined) {
        this.waitingQueryRowsExamined = waitingQueryRowsExamined;
    }
    public Long getWaitingQuerySecs() {
        return this.waitingQuerySecs;
    }
    
    public void setWaitingQuerySecs(Long waitingQuerySecs) {
        this.waitingQuerySecs = waitingQuerySecs;
    }
    public long getWaitingThreadId() {
        return this.waitingThreadId;
    }
    
    public void setWaitingThreadId(long waitingThreadId) {
        this.waitingThreadId = waitingThreadId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.schemaTableLockWaitsId) ) return false;
		 X.schemaTableLockWaitsId castOther = ( X.schemaTableLockWaitsId ) other; 
         
		 return ( (this.getBlockingAccount()==castOther.getBlockingAccount()) || ( this.getBlockingAccount()!=null && castOther.getBlockingAccount()!=null && this.getBlockingAccount().equals(castOther.getBlockingAccount()) ) )
 && ( (this.getBlockingLockDuration()==castOther.getBlockingLockDuration()) || ( this.getBlockingLockDuration()!=null && castOther.getBlockingLockDuration()!=null && this.getBlockingLockDuration().equals(castOther.getBlockingLockDuration()) ) )
 && ( (this.getBlockingLockType()==castOther.getBlockingLockType()) || ( this.getBlockingLockType()!=null && castOther.getBlockingLockType()!=null && this.getBlockingLockType().equals(castOther.getBlockingLockType()) ) )
 && ( (this.getBlockingPid()==castOther.getBlockingPid()) || ( this.getBlockingPid()!=null && castOther.getBlockingPid()!=null && this.getBlockingPid().equals(castOther.getBlockingPid()) ) )
 && (this.getBlockingThreadId()==castOther.getBlockingThreadId())
 && ( (this.getObjectName()==castOther.getObjectName()) || ( this.getObjectName()!=null && castOther.getObjectName()!=null && this.getObjectName().equals(castOther.getObjectName()) ) )
 && ( (this.getObjectSchema()==castOther.getObjectSchema()) || ( this.getObjectSchema()!=null && castOther.getObjectSchema()!=null && this.getObjectSchema().equals(castOther.getObjectSchema()) ) )
 && ( (this.getSqlKillBlockingConnection()==castOther.getSqlKillBlockingConnection()) || ( this.getSqlKillBlockingConnection()!=null && castOther.getSqlKillBlockingConnection()!=null && this.getSqlKillBlockingConnection().equals(castOther.getSqlKillBlockingConnection()) ) )
 && ( (this.getSqlKillBlockingQuery()==castOther.getSqlKillBlockingQuery()) || ( this.getSqlKillBlockingQuery()!=null && castOther.getSqlKillBlockingQuery()!=null && this.getSqlKillBlockingQuery().equals(castOther.getSqlKillBlockingQuery()) ) )
 && ( (this.getWaitingAccount()==castOther.getWaitingAccount()) || ( this.getWaitingAccount()!=null && castOther.getWaitingAccount()!=null && this.getWaitingAccount().equals(castOther.getWaitingAccount()) ) )
 && ( (this.getWaitingLockDuration()==castOther.getWaitingLockDuration()) || ( this.getWaitingLockDuration()!=null && castOther.getWaitingLockDuration()!=null && this.getWaitingLockDuration().equals(castOther.getWaitingLockDuration()) ) )
 && ( (this.getWaitingLockType()==castOther.getWaitingLockType()) || ( this.getWaitingLockType()!=null && castOther.getWaitingLockType()!=null && this.getWaitingLockType().equals(castOther.getWaitingLockType()) ) )
 && ( (this.getWaitingPid()==castOther.getWaitingPid()) || ( this.getWaitingPid()!=null && castOther.getWaitingPid()!=null && this.getWaitingPid().equals(castOther.getWaitingPid()) ) )
 && ( (this.getWaitingQuery()==castOther.getWaitingQuery()) || ( this.getWaitingQuery()!=null && castOther.getWaitingQuery()!=null && this.getWaitingQuery().equals(castOther.getWaitingQuery()) ) )
 && ( (this.getWaitingQueryRowsAffected()==castOther.getWaitingQueryRowsAffected()) || ( this.getWaitingQueryRowsAffected()!=null && castOther.getWaitingQueryRowsAffected()!=null && this.getWaitingQueryRowsAffected().equals(castOther.getWaitingQueryRowsAffected()) ) )
 && ( (this.getWaitingQueryRowsExamined()==castOther.getWaitingQueryRowsExamined()) || ( this.getWaitingQueryRowsExamined()!=null && castOther.getWaitingQueryRowsExamined()!=null && this.getWaitingQueryRowsExamined().equals(castOther.getWaitingQueryRowsExamined()) ) )
 && ( (this.getWaitingQuerySecs()==castOther.getWaitingQuerySecs()) || ( this.getWaitingQuerySecs()!=null && castOther.getWaitingQuerySecs()!=null && this.getWaitingQuerySecs().equals(castOther.getWaitingQuerySecs()) ) )
 && (this.getWaitingThreadId()==castOther.getWaitingThreadId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBlockingAccount() == null ? 0 : this.getBlockingAccount().hashCode() );
         result = 37 * result + ( getBlockingLockDuration() == null ? 0 : this.getBlockingLockDuration().hashCode() );
         result = 37 * result + ( getBlockingLockType() == null ? 0 : this.getBlockingLockType().hashCode() );
         result = 37 * result + ( getBlockingPid() == null ? 0 : this.getBlockingPid().hashCode() );
         result = 37 * result + (int) this.getBlockingThreadId();
         result = 37 * result + ( getObjectName() == null ? 0 : this.getObjectName().hashCode() );
         result = 37 * result + ( getObjectSchema() == null ? 0 : this.getObjectSchema().hashCode() );
         result = 37 * result + ( getSqlKillBlockingConnection() == null ? 0 : this.getSqlKillBlockingConnection().hashCode() );
         result = 37 * result + ( getSqlKillBlockingQuery() == null ? 0 : this.getSqlKillBlockingQuery().hashCode() );
         result = 37 * result + ( getWaitingAccount() == null ? 0 : this.getWaitingAccount().hashCode() );
         result = 37 * result + ( getWaitingLockDuration() == null ? 0 : this.getWaitingLockDuration().hashCode() );
         result = 37 * result + ( getWaitingLockType() == null ? 0 : this.getWaitingLockType().hashCode() );
         result = 37 * result + ( getWaitingPid() == null ? 0 : this.getWaitingPid().hashCode() );
         result = 37 * result + ( getWaitingQuery() == null ? 0 : this.getWaitingQuery().hashCode() );
         result = 37 * result + ( getWaitingQueryRowsAffected() == null ? 0 : this.getWaitingQueryRowsAffected().hashCode() );
         result = 37 * result + ( getWaitingQueryRowsExamined() == null ? 0 : this.getWaitingQueryRowsExamined().hashCode() );
         result = 37 * result + ( getWaitingQuerySecs() == null ? 0 : this.getWaitingQuerySecs().hashCode() );
         result = 37 * result + (int) this.getWaitingThreadId();
         return result;
   }   


}


