package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.schemaIndexStatisticsId;

/**
 * X.schemaIndexStatistics generated by hbm2java
 */
public class X.schemaIndexStatistics  implements java.io.Serializable {


     private X.schemaIndexStatisticsId id;

    public X.schemaIndexStatistics() {
    }

    public X.schemaIndexStatistics(X.schemaIndexStatisticsId id) {
       this.id = id;
    }
   
    public X.schemaIndexStatisticsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaIndexStatisticsId id) {
        this.id = id;
    }




}


