package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import java.math.BigInteger;

/**
 * X.schemaTableStatisticsId generated by hbm2java
 */
public class X.schemaTableStatisticsId  implements java.io.Serializable {


     private long deleteLatency;
     private long fetchLatency;
     private long insertLatency;
     private BigInteger ioMiscLatency;
     private BigInteger ioMiscRequests;
     private BigInteger ioRead;
     private BigInteger ioReadLatency;
     private BigInteger ioReadRequests;
     private BigInteger ioWrite;
     private BigInteger ioWriteLatency;
     private BigInteger ioWriteRequests;
     private long rowsDeleted;
     private long rowsFetched;
     private long rowsInserted;
     private long rowsUpdated;
     private String tableName;
     private String tableSchema;
     private long totalLatency;
     private long updateLatency;

    public X.schemaTableStatisticsId() {
    }

	
    public X.schemaTableStatisticsId(long deleteLatency, long fetchLatency, long insertLatency, long rowsDeleted, long rowsFetched, long rowsInserted, long rowsUpdated, long totalLatency, long updateLatency) {
        this.deleteLatency = deleteLatency;
        this.fetchLatency = fetchLatency;
        this.insertLatency = insertLatency;
        this.rowsDeleted = rowsDeleted;
        this.rowsFetched = rowsFetched;
        this.rowsInserted = rowsInserted;
        this.rowsUpdated = rowsUpdated;
        this.totalLatency = totalLatency;
        this.updateLatency = updateLatency;
    }
    public X.schemaTableStatisticsId(long deleteLatency, long fetchLatency, long insertLatency, BigInteger ioMiscLatency, BigInteger ioMiscRequests, BigInteger ioRead, BigInteger ioReadLatency, BigInteger ioReadRequests, BigInteger ioWrite, BigInteger ioWriteLatency, BigInteger ioWriteRequests, long rowsDeleted, long rowsFetched, long rowsInserted, long rowsUpdated, String tableName, String tableSchema, long totalLatency, long updateLatency) {
       this.deleteLatency = deleteLatency;
       this.fetchLatency = fetchLatency;
       this.insertLatency = insertLatency;
       this.ioMiscLatency = ioMiscLatency;
       this.ioMiscRequests = ioMiscRequests;
       this.ioRead = ioRead;
       this.ioReadLatency = ioReadLatency;
       this.ioReadRequests = ioReadRequests;
       this.ioWrite = ioWrite;
       this.ioWriteLatency = ioWriteLatency;
       this.ioWriteRequests = ioWriteRequests;
       this.rowsDeleted = rowsDeleted;
       this.rowsFetched = rowsFetched;
       this.rowsInserted = rowsInserted;
       this.rowsUpdated = rowsUpdated;
       this.tableName = tableName;
       this.tableSchema = tableSchema;
       this.totalLatency = totalLatency;
       this.updateLatency = updateLatency;
    }
   
    public long getDeleteLatency() {
        return this.deleteLatency;
    }
    
    public void setDeleteLatency(long deleteLatency) {
        this.deleteLatency = deleteLatency;
    }
    public long getFetchLatency() {
        return this.fetchLatency;
    }
    
    public void setFetchLatency(long fetchLatency) {
        this.fetchLatency = fetchLatency;
    }
    public long getInsertLatency() {
        return this.insertLatency;
    }
    
    public void setInsertLatency(long insertLatency) {
        this.insertLatency = insertLatency;
    }
    public BigInteger getIoMiscLatency() {
        return this.ioMiscLatency;
    }
    
    public void setIoMiscLatency(BigInteger ioMiscLatency) {
        this.ioMiscLatency = ioMiscLatency;
    }
    public BigInteger getIoMiscRequests() {
        return this.ioMiscRequests;
    }
    
    public void setIoMiscRequests(BigInteger ioMiscRequests) {
        this.ioMiscRequests = ioMiscRequests;
    }
    public BigInteger getIoRead() {
        return this.ioRead;
    }
    
    public void setIoRead(BigInteger ioRead) {
        this.ioRead = ioRead;
    }
    public BigInteger getIoReadLatency() {
        return this.ioReadLatency;
    }
    
    public void setIoReadLatency(BigInteger ioReadLatency) {
        this.ioReadLatency = ioReadLatency;
    }
    public BigInteger getIoReadRequests() {
        return this.ioReadRequests;
    }
    
    public void setIoReadRequests(BigInteger ioReadRequests) {
        this.ioReadRequests = ioReadRequests;
    }
    public BigInteger getIoWrite() {
        return this.ioWrite;
    }
    
    public void setIoWrite(BigInteger ioWrite) {
        this.ioWrite = ioWrite;
    }
    public BigInteger getIoWriteLatency() {
        return this.ioWriteLatency;
    }
    
    public void setIoWriteLatency(BigInteger ioWriteLatency) {
        this.ioWriteLatency = ioWriteLatency;
    }
    public BigInteger getIoWriteRequests() {
        return this.ioWriteRequests;
    }
    
    public void setIoWriteRequests(BigInteger ioWriteRequests) {
        this.ioWriteRequests = ioWriteRequests;
    }
    public long getRowsDeleted() {
        return this.rowsDeleted;
    }
    
    public void setRowsDeleted(long rowsDeleted) {
        this.rowsDeleted = rowsDeleted;
    }
    public long getRowsFetched() {
        return this.rowsFetched;
    }
    
    public void setRowsFetched(long rowsFetched) {
        this.rowsFetched = rowsFetched;
    }
    public long getRowsInserted() {
        return this.rowsInserted;
    }
    
    public void setRowsInserted(long rowsInserted) {
        this.rowsInserted = rowsInserted;
    }
    public long getRowsUpdated() {
        return this.rowsUpdated;
    }
    
    public void setRowsUpdated(long rowsUpdated) {
        this.rowsUpdated = rowsUpdated;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }
    public long getTotalLatency() {
        return this.totalLatency;
    }
    
    public void setTotalLatency(long totalLatency) {
        this.totalLatency = totalLatency;
    }
    public long getUpdateLatency() {
        return this.updateLatency;
    }
    
    public void setUpdateLatency(long updateLatency) {
        this.updateLatency = updateLatency;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.schemaTableStatisticsId) ) return false;
		 X.schemaTableStatisticsId castOther = ( X.schemaTableStatisticsId ) other; 
         
		 return (this.getDeleteLatency()==castOther.getDeleteLatency())
 && (this.getFetchLatency()==castOther.getFetchLatency())
 && (this.getInsertLatency()==castOther.getInsertLatency())
 && ( (this.getIoMiscLatency()==castOther.getIoMiscLatency()) || ( this.getIoMiscLatency()!=null && castOther.getIoMiscLatency()!=null && this.getIoMiscLatency().equals(castOther.getIoMiscLatency()) ) )
 && ( (this.getIoMiscRequests()==castOther.getIoMiscRequests()) || ( this.getIoMiscRequests()!=null && castOther.getIoMiscRequests()!=null && this.getIoMiscRequests().equals(castOther.getIoMiscRequests()) ) )
 && ( (this.getIoRead()==castOther.getIoRead()) || ( this.getIoRead()!=null && castOther.getIoRead()!=null && this.getIoRead().equals(castOther.getIoRead()) ) )
 && ( (this.getIoReadLatency()==castOther.getIoReadLatency()) || ( this.getIoReadLatency()!=null && castOther.getIoReadLatency()!=null && this.getIoReadLatency().equals(castOther.getIoReadLatency()) ) )
 && ( (this.getIoReadRequests()==castOther.getIoReadRequests()) || ( this.getIoReadRequests()!=null && castOther.getIoReadRequests()!=null && this.getIoReadRequests().equals(castOther.getIoReadRequests()) ) )
 && ( (this.getIoWrite()==castOther.getIoWrite()) || ( this.getIoWrite()!=null && castOther.getIoWrite()!=null && this.getIoWrite().equals(castOther.getIoWrite()) ) )
 && ( (this.getIoWriteLatency()==castOther.getIoWriteLatency()) || ( this.getIoWriteLatency()!=null && castOther.getIoWriteLatency()!=null && this.getIoWriteLatency().equals(castOther.getIoWriteLatency()) ) )
 && ( (this.getIoWriteRequests()==castOther.getIoWriteRequests()) || ( this.getIoWriteRequests()!=null && castOther.getIoWriteRequests()!=null && this.getIoWriteRequests().equals(castOther.getIoWriteRequests()) ) )
 && (this.getRowsDeleted()==castOther.getRowsDeleted())
 && (this.getRowsFetched()==castOther.getRowsFetched())
 && (this.getRowsInserted()==castOther.getRowsInserted())
 && (this.getRowsUpdated()==castOther.getRowsUpdated())
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) )
 && (this.getTotalLatency()==castOther.getTotalLatency())
 && (this.getUpdateLatency()==castOther.getUpdateLatency());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getDeleteLatency();
         result = 37 * result + (int) this.getFetchLatency();
         result = 37 * result + (int) this.getInsertLatency();
         result = 37 * result + ( getIoMiscLatency() == null ? 0 : this.getIoMiscLatency().hashCode() );
         result = 37 * result + ( getIoMiscRequests() == null ? 0 : this.getIoMiscRequests().hashCode() );
         result = 37 * result + ( getIoRead() == null ? 0 : this.getIoRead().hashCode() );
         result = 37 * result + ( getIoReadLatency() == null ? 0 : this.getIoReadLatency().hashCode() );
         result = 37 * result + ( getIoReadRequests() == null ? 0 : this.getIoReadRequests().hashCode() );
         result = 37 * result + ( getIoWrite() == null ? 0 : this.getIoWrite().hashCode() );
         result = 37 * result + ( getIoWriteLatency() == null ? 0 : this.getIoWriteLatency().hashCode() );
         result = 37 * result + ( getIoWriteRequests() == null ? 0 : this.getIoWriteRequests().hashCode() );
         result = 37 * result + (int) this.getRowsDeleted();
         result = 37 * result + (int) this.getRowsFetched();
         result = 37 * result + (int) this.getRowsInserted();
         result = 37 * result + (int) this.getRowsUpdated();
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
         result = 37 * result + (int) this.getTotalLatency();
         result = 37 * result + (int) this.getUpdateLatency();
         return result;
   }   


}


