package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.statementsWithFullTableScansId;

/**
 * X.statementsWithFullTableScans generated by hbm2java
 */
public class X.statementsWithFullTableScans  implements java.io.Serializable {


     private X.statementsWithFullTableScansId id;

    public X.statementsWithFullTableScans() {
    }

    public X.statementsWithFullTableScans(X.statementsWithFullTableScansId id) {
       this.id = id;
    }
   
    public X.statementsWithFullTableScansId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithFullTableScansId id) {
        this.id = id;
    }




}


