package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.statementsWithSortingId;

/**
 * X.statementsWithSorting generated by hbm2java
 */
public class X.statementsWithSorting  implements java.io.Serializable {


     private X.statementsWithSortingId id;

    public X.statementsWithSorting() {
    }

    public X.statementsWithSorting(X.statementsWithSortingId id) {
       this.id = id;
    }
   
    public X.statementsWithSortingId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithSortingId id) {
        this.id = id;
    }




}


