package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.statementsWithErrorsOrWarningsId;

/**
 * X.statementsWithErrorsOrWarnings generated by hbm2java
 */
public class X.statementsWithErrorsOrWarnings  implements java.io.Serializable {


     private X.statementsWithErrorsOrWarningsId id;

    public X.statementsWithErrorsOrWarnings() {
    }

    public X.statementsWithErrorsOrWarnings(X.statementsWithErrorsOrWarningsId id) {
       this.id = id;
    }
   
    public X.statementsWithErrorsOrWarningsId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithErrorsOrWarningsId id) {
        this.id = id;
    }




}


