package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.statementsWithRuntimesIn95thPercentileId;

/**
 * X.statementsWithRuntimesIn95thPercentile generated by hbm2java
 */
public class X.statementsWithRuntimesIn95thPercentile  implements java.io.Serializable {


     private X.statementsWithRuntimesIn95thPercentileId id;

    public X.statementsWithRuntimesIn95thPercentile() {
    }

    public X.statementsWithRuntimesIn95thPercentile(X.statementsWithRuntimesIn95thPercentileId id) {
       this.id = id;
    }
   
    public X.statementsWithRuntimesIn95thPercentileId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithRuntimesIn95thPercentileId id) {
        this.id = id;
    }




}


