package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * X.statementsWithErrorsOrWarningsId generated by hbm2java
 */
public class X.statementsWithErrorsOrWarningsId  implements java.io.Serializable {


     private String db;
     private String digest;
     private BigDecimal errorPct;
     private long errors;
     private long execCount;
     private Timestamp firstSeen;
     private Timestamp lastSeen;
     private String query;
     private BigDecimal warningPct;
     private long warnings;

    public X.statementsWithErrorsOrWarningsId() {
    }

	
    public X.statementsWithErrorsOrWarningsId(BigDecimal errorPct, long errors, long execCount, Timestamp firstSeen, Timestamp lastSeen, BigDecimal warningPct, long warnings) {
        this.errorPct = errorPct;
        this.errors = errors;
        this.execCount = execCount;
        this.firstSeen = firstSeen;
        this.lastSeen = lastSeen;
        this.warningPct = warningPct;
        this.warnings = warnings;
    }
    public X.statementsWithErrorsOrWarningsId(String db, String digest, BigDecimal errorPct, long errors, long execCount, Timestamp firstSeen, Timestamp lastSeen, String query, BigDecimal warningPct, long warnings) {
       this.db = db;
       this.digest = digest;
       this.errorPct = errorPct;
       this.errors = errors;
       this.execCount = execCount;
       this.firstSeen = firstSeen;
       this.lastSeen = lastSeen;
       this.query = query;
       this.warningPct = warningPct;
       this.warnings = warnings;
    }
   
    public String getDb() {
        return this.db;
    }
    
    public void setDb(String db) {
        this.db = db;
    }
    public String getDigest() {
        return this.digest;
    }
    
    public void setDigest(String digest) {
        this.digest = digest;
    }
    public BigDecimal getErrorPct() {
        return this.errorPct;
    }
    
    public void setErrorPct(BigDecimal errorPct) {
        this.errorPct = errorPct;
    }
    public long getErrors() {
        return this.errors;
    }
    
    public void setErrors(long errors) {
        this.errors = errors;
    }
    public long getExecCount() {
        return this.execCount;
    }
    
    public void setExecCount(long execCount) {
        this.execCount = execCount;
    }
    public Timestamp getFirstSeen() {
        return this.firstSeen;
    }
    
    public void setFirstSeen(Timestamp firstSeen) {
        this.firstSeen = firstSeen;
    }
    public Timestamp getLastSeen() {
        return this.lastSeen;
    }
    
    public void setLastSeen(Timestamp lastSeen) {
        this.lastSeen = lastSeen;
    }
    public String getQuery() {
        return this.query;
    }
    
    public void setQuery(String query) {
        this.query = query;
    }
    public BigDecimal getWarningPct() {
        return this.warningPct;
    }
    
    public void setWarningPct(BigDecimal warningPct) {
        this.warningPct = warningPct;
    }
    public long getWarnings() {
        return this.warnings;
    }
    
    public void setWarnings(long warnings) {
        this.warnings = warnings;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.statementsWithErrorsOrWarningsId) ) return false;
		 X.statementsWithErrorsOrWarningsId castOther = ( X.statementsWithErrorsOrWarningsId ) other; 
         
		 return ( (this.getDb()==castOther.getDb()) || ( this.getDb()!=null && castOther.getDb()!=null && this.getDb().equals(castOther.getDb()) ) )
 && ( (this.getDigest()==castOther.getDigest()) || ( this.getDigest()!=null && castOther.getDigest()!=null && this.getDigest().equals(castOther.getDigest()) ) )
 && ( (this.getErrorPct()==castOther.getErrorPct()) || ( this.getErrorPct()!=null && castOther.getErrorPct()!=null && this.getErrorPct().equals(castOther.getErrorPct()) ) )
 && (this.getErrors()==castOther.getErrors())
 && (this.getExecCount()==castOther.getExecCount())
 && ( (this.getFirstSeen()==castOther.getFirstSeen()) || ( this.getFirstSeen()!=null && castOther.getFirstSeen()!=null && this.getFirstSeen().equals(castOther.getFirstSeen()) ) )
 && ( (this.getLastSeen()==castOther.getLastSeen()) || ( this.getLastSeen()!=null && castOther.getLastSeen()!=null && this.getLastSeen().equals(castOther.getLastSeen()) ) )
 && ( (this.getQuery()==castOther.getQuery()) || ( this.getQuery()!=null && castOther.getQuery()!=null && this.getQuery().equals(castOther.getQuery()) ) )
 && ( (this.getWarningPct()==castOther.getWarningPct()) || ( this.getWarningPct()!=null && castOther.getWarningPct()!=null && this.getWarningPct().equals(castOther.getWarningPct()) ) )
 && (this.getWarnings()==castOther.getWarnings());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDb() == null ? 0 : this.getDb().hashCode() );
         result = 37 * result + ( getDigest() == null ? 0 : this.getDigest().hashCode() );
         result = 37 * result + ( getErrorPct() == null ? 0 : this.getErrorPct().hashCode() );
         result = 37 * result + (int) this.getErrors();
         result = 37 * result + (int) this.getExecCount();
         result = 37 * result + ( getFirstSeen() == null ? 0 : this.getFirstSeen().hashCode() );
         result = 37 * result + ( getLastSeen() == null ? 0 : this.getLastSeen().hashCode() );
         result = 37 * result + ( getQuery() == null ? 0 : this.getQuery().hashCode() );
         result = 37 * result + ( getWarningPct() == null ? 0 : this.getWarningPct().hashCode() );
         result = 37 * result + (int) this.getWarnings();
         return result;
   }   


}


