package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.statementsWithTempTablesId;

/**
 * X.statementsWithTempTables generated by hbm2java
 */
public class X.statementsWithTempTables  implements java.io.Serializable {


     private X.statementsWithTempTablesId id;

    public X.statementsWithTempTables() {
    }

    public X.statementsWithTempTables(X.statementsWithTempTablesId id) {
       this.id = id;
    }
   
    public X.statementsWithTempTablesId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithTempTablesId id) {
        this.id = id;
    }




}


