package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import java.math.BigInteger;
import java.sql.Timestamp;

/**
 * X.statementAnalysisId generated by hbm2java
 */
public class X.statementAnalysisId  implements java.io.Serializable {


     private long avgLatency;
     private long cpuLatency;
     private String db;
     private String digest;
     private long errCount;
     private long execCount;
     private long execSecondaryCount;
     private Timestamp firstSeen;
     private String fullScan;
     private Timestamp lastSeen;
     private long lockLatency;
     private long maxControlledMemory;
     private long maxLatency;
     private long maxTotalMemory;
     private String query;
     private long rowsAffected;
     private BigInteger rowsAffectedAvg;
     private long rowsExamined;
     private BigInteger rowsExaminedAvg;
     private long rowsSent;
     private BigInteger rowsSentAvg;
     private long rowsSorted;
     private long sortMergePasses;
     private long tmpDiskTables;
     private long tmpTables;
     private long totalLatency;
     private long warnCount;

    public X.statementAnalysisId() {
    }

	
    public X.statementAnalysisId(long avgLatency, long cpuLatency, long errCount, long execCount, long execSecondaryCount, Timestamp firstSeen, String fullScan, Timestamp lastSeen, long lockLatency, long maxControlledMemory, long maxLatency, long maxTotalMemory, long rowsAffected, BigInteger rowsAffectedAvg, long rowsExamined, BigInteger rowsExaminedAvg, long rowsSent, BigInteger rowsSentAvg, long rowsSorted, long sortMergePasses, long tmpDiskTables, long tmpTables, long totalLatency, long warnCount) {
        this.avgLatency = avgLatency;
        this.cpuLatency = cpuLatency;
        this.errCount = errCount;
        this.execCount = execCount;
        this.execSecondaryCount = execSecondaryCount;
        this.firstSeen = firstSeen;
        this.fullScan = fullScan;
        this.lastSeen = lastSeen;
        this.lockLatency = lockLatency;
        this.maxControlledMemory = maxControlledMemory;
        this.maxLatency = maxLatency;
        this.maxTotalMemory = maxTotalMemory;
        this.rowsAffected = rowsAffected;
        this.rowsAffectedAvg = rowsAffectedAvg;
        this.rowsExamined = rowsExamined;
        this.rowsExaminedAvg = rowsExaminedAvg;
        this.rowsSent = rowsSent;
        this.rowsSentAvg = rowsSentAvg;
        this.rowsSorted = rowsSorted;
        this.sortMergePasses = sortMergePasses;
        this.tmpDiskTables = tmpDiskTables;
        this.tmpTables = tmpTables;
        this.totalLatency = totalLatency;
        this.warnCount = warnCount;
    }
    public X.statementAnalysisId(long avgLatency, long cpuLatency, String db, String digest, long errCount, long execCount, long execSecondaryCount, Timestamp firstSeen, String fullScan, Timestamp lastSeen, long lockLatency, long maxControlledMemory, long maxLatency, long maxTotalMemory, String query, long rowsAffected, BigInteger rowsAffectedAvg, long rowsExamined, BigInteger rowsExaminedAvg, long rowsSent, BigInteger rowsSentAvg, long rowsSorted, long sortMergePasses, long tmpDiskTables, long tmpTables, long totalLatency, long warnCount) {
       this.avgLatency = avgLatency;
       this.cpuLatency = cpuLatency;
       this.db = db;
       this.digest = digest;
       this.errCount = errCount;
       this.execCount = execCount;
       this.execSecondaryCount = execSecondaryCount;
       this.firstSeen = firstSeen;
       this.fullScan = fullScan;
       this.lastSeen = lastSeen;
       this.lockLatency = lockLatency;
       this.maxControlledMemory = maxControlledMemory;
       this.maxLatency = maxLatency;
       this.maxTotalMemory = maxTotalMemory;
       this.query = query;
       this.rowsAffected = rowsAffected;
       this.rowsAffectedAvg = rowsAffectedAvg;
       this.rowsExamined = rowsExamined;
       this.rowsExaminedAvg = rowsExaminedAvg;
       this.rowsSent = rowsSent;
       this.rowsSentAvg = rowsSentAvg;
       this.rowsSorted = rowsSorted;
       this.sortMergePasses = sortMergePasses;
       this.tmpDiskTables = tmpDiskTables;
       this.tmpTables = tmpTables;
       this.totalLatency = totalLatency;
       this.warnCount = warnCount;
    }
   
    public long getAvgLatency() {
        return this.avgLatency;
    }
    
    public void setAvgLatency(long avgLatency) {
        this.avgLatency = avgLatency;
    }
    public long getCpuLatency() {
        return this.cpuLatency;
    }
    
    public void setCpuLatency(long cpuLatency) {
        this.cpuLatency = cpuLatency;
    }
    public String getDb() {
        return this.db;
    }
    
    public void setDb(String db) {
        this.db = db;
    }
    public String getDigest() {
        return this.digest;
    }
    
    public void setDigest(String digest) {
        this.digest = digest;
    }
    public long getErrCount() {
        return this.errCount;
    }
    
    public void setErrCount(long errCount) {
        this.errCount = errCount;
    }
    public long getExecCount() {
        return this.execCount;
    }
    
    public void setExecCount(long execCount) {
        this.execCount = execCount;
    }
    public long getExecSecondaryCount() {
        return this.execSecondaryCount;
    }
    
    public void setExecSecondaryCount(long execSecondaryCount) {
        this.execSecondaryCount = execSecondaryCount;
    }
    public Timestamp getFirstSeen() {
        return this.firstSeen;
    }
    
    public void setFirstSeen(Timestamp firstSeen) {
        this.firstSeen = firstSeen;
    }
    public String getFullScan() {
        return this.fullScan;
    }
    
    public void setFullScan(String fullScan) {
        this.fullScan = fullScan;
    }
    public Timestamp getLastSeen() {
        return this.lastSeen;
    }
    
    public void setLastSeen(Timestamp lastSeen) {
        this.lastSeen = lastSeen;
    }
    public long getLockLatency() {
        return this.lockLatency;
    }
    
    public void setLockLatency(long lockLatency) {
        this.lockLatency = lockLatency;
    }
    public long getMaxControlledMemory() {
        return this.maxControlledMemory;
    }
    
    public void setMaxControlledMemory(long maxControlledMemory) {
        this.maxControlledMemory = maxControlledMemory;
    }
    public long getMaxLatency() {
        return this.maxLatency;
    }
    
    public void setMaxLatency(long maxLatency) {
        this.maxLatency = maxLatency;
    }
    public long getMaxTotalMemory() {
        return this.maxTotalMemory;
    }
    
    public void setMaxTotalMemory(long maxTotalMemory) {
        this.maxTotalMemory = maxTotalMemory;
    }
    public String getQuery() {
        return this.query;
    }
    
    public void setQuery(String query) {
        this.query = query;
    }
    public long getRowsAffected() {
        return this.rowsAffected;
    }
    
    public void setRowsAffected(long rowsAffected) {
        this.rowsAffected = rowsAffected;
    }
    public BigInteger getRowsAffectedAvg() {
        return this.rowsAffectedAvg;
    }
    
    public void setRowsAffectedAvg(BigInteger rowsAffectedAvg) {
        this.rowsAffectedAvg = rowsAffectedAvg;
    }
    public long getRowsExamined() {
        return this.rowsExamined;
    }
    
    public void setRowsExamined(long rowsExamined) {
        this.rowsExamined = rowsExamined;
    }
    public BigInteger getRowsExaminedAvg() {
        return this.rowsExaminedAvg;
    }
    
    public void setRowsExaminedAvg(BigInteger rowsExaminedAvg) {
        this.rowsExaminedAvg = rowsExaminedAvg;
    }
    public long getRowsSent() {
        return this.rowsSent;
    }
    
    public void setRowsSent(long rowsSent) {
        this.rowsSent = rowsSent;
    }
    public BigInteger getRowsSentAvg() {
        return this.rowsSentAvg;
    }
    
    public void setRowsSentAvg(BigInteger rowsSentAvg) {
        this.rowsSentAvg = rowsSentAvg;
    }
    public long getRowsSorted() {
        return this.rowsSorted;
    }
    
    public void setRowsSorted(long rowsSorted) {
        this.rowsSorted = rowsSorted;
    }
    public long getSortMergePasses() {
        return this.sortMergePasses;
    }
    
    public void setSortMergePasses(long sortMergePasses) {
        this.sortMergePasses = sortMergePasses;
    }
    public long getTmpDiskTables() {
        return this.tmpDiskTables;
    }
    
    public void setTmpDiskTables(long tmpDiskTables) {
        this.tmpDiskTables = tmpDiskTables;
    }
    public long getTmpTables() {
        return this.tmpTables;
    }
    
    public void setTmpTables(long tmpTables) {
        this.tmpTables = tmpTables;
    }
    public long getTotalLatency() {
        return this.totalLatency;
    }
    
    public void setTotalLatency(long totalLatency) {
        this.totalLatency = totalLatency;
    }
    public long getWarnCount() {
        return this.warnCount;
    }
    
    public void setWarnCount(long warnCount) {
        this.warnCount = warnCount;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.statementAnalysisId) ) return false;
		 X.statementAnalysisId castOther = ( X.statementAnalysisId ) other; 
         
		 return (this.getAvgLatency()==castOther.getAvgLatency())
 && (this.getCpuLatency()==castOther.getCpuLatency())
 && ( (this.getDb()==castOther.getDb()) || ( this.getDb()!=null && castOther.getDb()!=null && this.getDb().equals(castOther.getDb()) ) )
 && ( (this.getDigest()==castOther.getDigest()) || ( this.getDigest()!=null && castOther.getDigest()!=null && this.getDigest().equals(castOther.getDigest()) ) )
 && (this.getErrCount()==castOther.getErrCount())
 && (this.getExecCount()==castOther.getExecCount())
 && (this.getExecSecondaryCount()==castOther.getExecSecondaryCount())
 && ( (this.getFirstSeen()==castOther.getFirstSeen()) || ( this.getFirstSeen()!=null && castOther.getFirstSeen()!=null && this.getFirstSeen().equals(castOther.getFirstSeen()) ) )
 && ( (this.getFullScan()==castOther.getFullScan()) || ( this.getFullScan()!=null && castOther.getFullScan()!=null && this.getFullScan().equals(castOther.getFullScan()) ) )
 && ( (this.getLastSeen()==castOther.getLastSeen()) || ( this.getLastSeen()!=null && castOther.getLastSeen()!=null && this.getLastSeen().equals(castOther.getLastSeen()) ) )
 && (this.getLockLatency()==castOther.getLockLatency())
 && (this.getMaxControlledMemory()==castOther.getMaxControlledMemory())
 && (this.getMaxLatency()==castOther.getMaxLatency())
 && (this.getMaxTotalMemory()==castOther.getMaxTotalMemory())
 && ( (this.getQuery()==castOther.getQuery()) || ( this.getQuery()!=null && castOther.getQuery()!=null && this.getQuery().equals(castOther.getQuery()) ) )
 && (this.getRowsAffected()==castOther.getRowsAffected())
 && ( (this.getRowsAffectedAvg()==castOther.getRowsAffectedAvg()) || ( this.getRowsAffectedAvg()!=null && castOther.getRowsAffectedAvg()!=null && this.getRowsAffectedAvg().equals(castOther.getRowsAffectedAvg()) ) )
 && (this.getRowsExamined()==castOther.getRowsExamined())
 && ( (this.getRowsExaminedAvg()==castOther.getRowsExaminedAvg()) || ( this.getRowsExaminedAvg()!=null && castOther.getRowsExaminedAvg()!=null && this.getRowsExaminedAvg().equals(castOther.getRowsExaminedAvg()) ) )
 && (this.getRowsSent()==castOther.getRowsSent())
 && ( (this.getRowsSentAvg()==castOther.getRowsSentAvg()) || ( this.getRowsSentAvg()!=null && castOther.getRowsSentAvg()!=null && this.getRowsSentAvg().equals(castOther.getRowsSentAvg()) ) )
 && (this.getRowsSorted()==castOther.getRowsSorted())
 && (this.getSortMergePasses()==castOther.getSortMergePasses())
 && (this.getTmpDiskTables()==castOther.getTmpDiskTables())
 && (this.getTmpTables()==castOther.getTmpTables())
 && (this.getTotalLatency()==castOther.getTotalLatency())
 && (this.getWarnCount()==castOther.getWarnCount());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getAvgLatency();
         result = 37 * result + (int) this.getCpuLatency();
         result = 37 * result + ( getDb() == null ? 0 : this.getDb().hashCode() );
         result = 37 * result + ( getDigest() == null ? 0 : this.getDigest().hashCode() );
         result = 37 * result + (int) this.getErrCount();
         result = 37 * result + (int) this.getExecCount();
         result = 37 * result + (int) this.getExecSecondaryCount();
         result = 37 * result + ( getFirstSeen() == null ? 0 : this.getFirstSeen().hashCode() );
         result = 37 * result + ( getFullScan() == null ? 0 : this.getFullScan().hashCode() );
         result = 37 * result + ( getLastSeen() == null ? 0 : this.getLastSeen().hashCode() );
         result = 37 * result + (int) this.getLockLatency();
         result = 37 * result + (int) this.getMaxControlledMemory();
         result = 37 * result + (int) this.getMaxLatency();
         result = 37 * result + (int) this.getMaxTotalMemory();
         result = 37 * result + ( getQuery() == null ? 0 : this.getQuery().hashCode() );
         result = 37 * result + (int) this.getRowsAffected();
         result = 37 * result + ( getRowsAffectedAvg() == null ? 0 : this.getRowsAffectedAvg().hashCode() );
         result = 37 * result + (int) this.getRowsExamined();
         result = 37 * result + ( getRowsExaminedAvg() == null ? 0 : this.getRowsExaminedAvg().hashCode() );
         result = 37 * result + (int) this.getRowsSent();
         result = 37 * result + ( getRowsSentAvg() == null ? 0 : this.getRowsSentAvg().hashCode() );
         result = 37 * result + (int) this.getRowsSorted();
         result = 37 * result + (int) this.getSortMergePasses();
         result = 37 * result + (int) this.getTmpDiskTables();
         result = 37 * result + (int) this.getTmpTables();
         result = 37 * result + (int) this.getTotalLatency();
         result = 37 * result + (int) this.getWarnCount();
         return result;
   }   


}


