package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import java.math.BigInteger;
import java.sql.Timestamp;

/**
 * X.statementsWithRuntimesIn95thPercentileId generated by hbm2java
 */
public class X.statementsWithRuntimesIn95thPercentileId  implements java.io.Serializable {


     private long avgLatency;
     private String db;
     private String digest;
     private long errCount;
     private long execCount;
     private Timestamp firstSeen;
     private String fullScan;
     private Timestamp lastSeen;
     private long maxLatency;
     private String query;
     private long rowsExamined;
     private BigInteger rowsExaminedAvg;
     private long rowsSent;
     private BigInteger rowsSentAvg;
     private long totalLatency;
     private long warnCount;

    public X.statementsWithRuntimesIn95thPercentileId() {
    }

	
    public X.statementsWithRuntimesIn95thPercentileId(long avgLatency, long errCount, long execCount, Timestamp firstSeen, String fullScan, Timestamp lastSeen, long maxLatency, long rowsExamined, BigInteger rowsExaminedAvg, long rowsSent, BigInteger rowsSentAvg, long totalLatency, long warnCount) {
        this.avgLatency = avgLatency;
        this.errCount = errCount;
        this.execCount = execCount;
        this.firstSeen = firstSeen;
        this.fullScan = fullScan;
        this.lastSeen = lastSeen;
        this.maxLatency = maxLatency;
        this.rowsExamined = rowsExamined;
        this.rowsExaminedAvg = rowsExaminedAvg;
        this.rowsSent = rowsSent;
        this.rowsSentAvg = rowsSentAvg;
        this.totalLatency = totalLatency;
        this.warnCount = warnCount;
    }
    public X.statementsWithRuntimesIn95thPercentileId(long avgLatency, String db, String digest, long errCount, long execCount, Timestamp firstSeen, String fullScan, Timestamp lastSeen, long maxLatency, String query, long rowsExamined, BigInteger rowsExaminedAvg, long rowsSent, BigInteger rowsSentAvg, long totalLatency, long warnCount) {
       this.avgLatency = avgLatency;
       this.db = db;
       this.digest = digest;
       this.errCount = errCount;
       this.execCount = execCount;
       this.firstSeen = firstSeen;
       this.fullScan = fullScan;
       this.lastSeen = lastSeen;
       this.maxLatency = maxLatency;
       this.query = query;
       this.rowsExamined = rowsExamined;
       this.rowsExaminedAvg = rowsExaminedAvg;
       this.rowsSent = rowsSent;
       this.rowsSentAvg = rowsSentAvg;
       this.totalLatency = totalLatency;
       this.warnCount = warnCount;
    }
   
    public long getAvgLatency() {
        return this.avgLatency;
    }
    
    public void setAvgLatency(long avgLatency) {
        this.avgLatency = avgLatency;
    }
    public String getDb() {
        return this.db;
    }
    
    public void setDb(String db) {
        this.db = db;
    }
    public String getDigest() {
        return this.digest;
    }
    
    public void setDigest(String digest) {
        this.digest = digest;
    }
    public long getErrCount() {
        return this.errCount;
    }
    
    public void setErrCount(long errCount) {
        this.errCount = errCount;
    }
    public long getExecCount() {
        return this.execCount;
    }
    
    public void setExecCount(long execCount) {
        this.execCount = execCount;
    }
    public Timestamp getFirstSeen() {
        return this.firstSeen;
    }
    
    public void setFirstSeen(Timestamp firstSeen) {
        this.firstSeen = firstSeen;
    }
    public String getFullScan() {
        return this.fullScan;
    }
    
    public void setFullScan(String fullScan) {
        this.fullScan = fullScan;
    }
    public Timestamp getLastSeen() {
        return this.lastSeen;
    }
    
    public void setLastSeen(Timestamp lastSeen) {
        this.lastSeen = lastSeen;
    }
    public long getMaxLatency() {
        return this.maxLatency;
    }
    
    public void setMaxLatency(long maxLatency) {
        this.maxLatency = maxLatency;
    }
    public String getQuery() {
        return this.query;
    }
    
    public void setQuery(String query) {
        this.query = query;
    }
    public long getRowsExamined() {
        return this.rowsExamined;
    }
    
    public void setRowsExamined(long rowsExamined) {
        this.rowsExamined = rowsExamined;
    }
    public BigInteger getRowsExaminedAvg() {
        return this.rowsExaminedAvg;
    }
    
    public void setRowsExaminedAvg(BigInteger rowsExaminedAvg) {
        this.rowsExaminedAvg = rowsExaminedAvg;
    }
    public long getRowsSent() {
        return this.rowsSent;
    }
    
    public void setRowsSent(long rowsSent) {
        this.rowsSent = rowsSent;
    }
    public BigInteger getRowsSentAvg() {
        return this.rowsSentAvg;
    }
    
    public void setRowsSentAvg(BigInteger rowsSentAvg) {
        this.rowsSentAvg = rowsSentAvg;
    }
    public long getTotalLatency() {
        return this.totalLatency;
    }
    
    public void setTotalLatency(long totalLatency) {
        this.totalLatency = totalLatency;
    }
    public long getWarnCount() {
        return this.warnCount;
    }
    
    public void setWarnCount(long warnCount) {
        this.warnCount = warnCount;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.statementsWithRuntimesIn95thPercentileId) ) return false;
		 X.statementsWithRuntimesIn95thPercentileId castOther = ( X.statementsWithRuntimesIn95thPercentileId ) other; 
         
		 return (this.getAvgLatency()==castOther.getAvgLatency())
 && ( (this.getDb()==castOther.getDb()) || ( this.getDb()!=null && castOther.getDb()!=null && this.getDb().equals(castOther.getDb()) ) )
 && ( (this.getDigest()==castOther.getDigest()) || ( this.getDigest()!=null && castOther.getDigest()!=null && this.getDigest().equals(castOther.getDigest()) ) )
 && (this.getErrCount()==castOther.getErrCount())
 && (this.getExecCount()==castOther.getExecCount())
 && ( (this.getFirstSeen()==castOther.getFirstSeen()) || ( this.getFirstSeen()!=null && castOther.getFirstSeen()!=null && this.getFirstSeen().equals(castOther.getFirstSeen()) ) )
 && ( (this.getFullScan()==castOther.getFullScan()) || ( this.getFullScan()!=null && castOther.getFullScan()!=null && this.getFullScan().equals(castOther.getFullScan()) ) )
 && ( (this.getLastSeen()==castOther.getLastSeen()) || ( this.getLastSeen()!=null && castOther.getLastSeen()!=null && this.getLastSeen().equals(castOther.getLastSeen()) ) )
 && (this.getMaxLatency()==castOther.getMaxLatency())
 && ( (this.getQuery()==castOther.getQuery()) || ( this.getQuery()!=null && castOther.getQuery()!=null && this.getQuery().equals(castOther.getQuery()) ) )
 && (this.getRowsExamined()==castOther.getRowsExamined())
 && ( (this.getRowsExaminedAvg()==castOther.getRowsExaminedAvg()) || ( this.getRowsExaminedAvg()!=null && castOther.getRowsExaminedAvg()!=null && this.getRowsExaminedAvg().equals(castOther.getRowsExaminedAvg()) ) )
 && (this.getRowsSent()==castOther.getRowsSent())
 && ( (this.getRowsSentAvg()==castOther.getRowsSentAvg()) || ( this.getRowsSentAvg()!=null && castOther.getRowsSentAvg()!=null && this.getRowsSentAvg().equals(castOther.getRowsSentAvg()) ) )
 && (this.getTotalLatency()==castOther.getTotalLatency())
 && (this.getWarnCount()==castOther.getWarnCount());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getAvgLatency();
         result = 37 * result + ( getDb() == null ? 0 : this.getDb().hashCode() );
         result = 37 * result + ( getDigest() == null ? 0 : this.getDigest().hashCode() );
         result = 37 * result + (int) this.getErrCount();
         result = 37 * result + (int) this.getExecCount();
         result = 37 * result + ( getFirstSeen() == null ? 0 : this.getFirstSeen().hashCode() );
         result = 37 * result + ( getFullScan() == null ? 0 : this.getFullScan().hashCode() );
         result = 37 * result + ( getLastSeen() == null ? 0 : this.getLastSeen().hashCode() );
         result = 37 * result + (int) this.getMaxLatency();
         result = 37 * result + ( getQuery() == null ? 0 : this.getQuery().hashCode() );
         result = 37 * result + (int) this.getRowsExamined();
         result = 37 * result + ( getRowsExaminedAvg() == null ? 0 : this.getRowsExaminedAvg().hashCode() );
         result = 37 * result + (int) this.getRowsSent();
         result = 37 * result + ( getRowsSentAvg() == null ? 0 : this.getRowsSentAvg().hashCode() );
         result = 37 * result + (int) this.getTotalLatency();
         result = 37 * result + (int) this.getWarnCount();
         return result;
   }   


}


