package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.userSummaryByFileIoId;

/**
 * X.userSummaryByFileIo generated by hbm2java
 */
public class X.userSummaryByFileIo  implements java.io.Serializable {


     private X.userSummaryByFileIoId id;

    public X.userSummaryByFileIo() {
    }

    public X.userSummaryByFileIo(X.userSummaryByFileIoId id) {
       this.id = id;
    }
   
    public X.userSummaryByFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByFileIoId id) {
        this.id = id;
    }




}


