package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.userSummaryByStatementLatencyId;

/**
 * X.userSummaryByStatementLatency generated by hbm2java
 */
public class X.userSummaryByStatementLatency  implements java.io.Serializable {


     private X.userSummaryByStatementLatencyId id;

    public X.userSummaryByStatementLatency() {
    }

    public X.userSummaryByStatementLatency(X.userSummaryByStatementLatencyId id) {
       this.id = id;
    }
   
    public X.userSummaryByStatementLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStatementLatencyId id) {
        this.id = id;
    }




}


