package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.userSummaryByStatementTypeId;

/**
 * X.userSummaryByStatementType generated by hbm2java
 */
public class X.userSummaryByStatementType  implements java.io.Serializable {


     private X.userSummaryByStatementTypeId id;

    public X.userSummaryByStatementType() {
    }

    public X.userSummaryByStatementType(X.userSummaryByStatementTypeId id) {
       this.id = id;
    }
   
    public X.userSummaryByStatementTypeId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStatementTypeId id) {
        this.id = id;
    }




}


