package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import java.math.BigInteger;

/**
 * X.userSummaryByFileIoId generated by hbm2java
 */
public class X.userSummaryByFileIoId  implements java.io.Serializable {


     private BigInteger ioLatency;
     private BigInteger ios;
     private String user;

    public X.userSummaryByFileIoId() {
    }

    public X.userSummaryByFileIoId(BigInteger ioLatency, BigInteger ios, String user) {
       this.ioLatency = ioLatency;
       this.ios = ios;
       this.user = user;
    }
   
    public BigInteger getIoLatency() {
        return this.ioLatency;
    }
    
    public void setIoLatency(BigInteger ioLatency) {
        this.ioLatency = ioLatency;
    }
    public BigInteger getIos() {
        return this.ios;
    }
    
    public void setIos(BigInteger ios) {
        this.ios = ios;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.userSummaryByFileIoId) ) return false;
		 X.userSummaryByFileIoId castOther = ( X.userSummaryByFileIoId ) other; 
         
		 return ( (this.getIoLatency()==castOther.getIoLatency()) || ( this.getIoLatency()!=null && castOther.getIoLatency()!=null && this.getIoLatency().equals(castOther.getIoLatency()) ) )
 && ( (this.getIos()==castOther.getIos()) || ( this.getIos()!=null && castOther.getIos()!=null && this.getIos().equals(castOther.getIos()) ) )
 && ( (this.getUser()==castOther.getUser()) || ( this.getUser()!=null && castOther.getUser()!=null && this.getUser().equals(castOther.getUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIoLatency() == null ? 0 : this.getIoLatency().hashCode() );
         result = 37 * result + ( getIos() == null ? 0 : this.getIos().hashCode() );
         result = 37 * result + ( getUser() == null ? 0 : this.getUser().hashCode() );
         return result;
   }   


}


