package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.waitsGlobalByLatencyId;

/**
 * X.waitsGlobalByLatency generated by hbm2java
 */
public class X.waitsGlobalByLatency  implements java.io.Serializable {


     private X.waitsGlobalByLatencyId id;

    public X.waitsGlobalByLatency() {
    }

    public X.waitsGlobalByLatency(X.waitsGlobalByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsGlobalByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsGlobalByLatencyId id) {
        this.id = id;
    }




}


