package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.waitsByUserByLatencyId;

/**
 * X.waitsByUserByLatency generated by hbm2java
 */
public class X.waitsByUserByLatency  implements java.io.Serializable {


     private X.waitsByUserByLatencyId id;

    public X.waitsByUserByLatency() {
    }

    public X.waitsByUserByLatency(X.waitsByUserByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsByUserByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsByUserByLatencyId id) {
        this.id = id;
    }




}


