package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final


import com.softorx.ntdb.X.waitsByHostByLatencyId;

/**
 * X.waitsByHostByLatency generated by hbm2java
 */
public class X.waitsByHostByLatency  implements java.io.Serializable {


     private X.waitsByHostByLatencyId id;

    public X.waitsByHostByLatency() {
    }

    public X.waitsByHostByLatency(X.waitsByHostByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsByHostByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsByHostByLatencyId id) {
        this.id = id;
    }




}


