package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final



/**
 * X.waitsByHostByLatencyId generated by hbm2java
 */
public class X.waitsByHostByLatencyId  implements java.io.Serializable {


     private long avgLatency;
     private String event;
     private String host;
     private long maxLatency;
     private long total;
     private long totalLatency;

    public X.waitsByHostByLatencyId() {
    }

	
    public X.waitsByHostByLatencyId(long avgLatency, String event, long maxLatency, long total, long totalLatency) {
        this.avgLatency = avgLatency;
        this.event = event;
        this.maxLatency = maxLatency;
        this.total = total;
        this.totalLatency = totalLatency;
    }
    public X.waitsByHostByLatencyId(long avgLatency, String event, String host, long maxLatency, long total, long totalLatency) {
       this.avgLatency = avgLatency;
       this.event = event;
       this.host = host;
       this.maxLatency = maxLatency;
       this.total = total;
       this.totalLatency = totalLatency;
    }
   
    public long getAvgLatency() {
        return this.avgLatency;
    }
    
    public void setAvgLatency(long avgLatency) {
        this.avgLatency = avgLatency;
    }
    public String getEvent() {
        return this.event;
    }
    
    public void setEvent(String event) {
        this.event = event;
    }
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public long getMaxLatency() {
        return this.maxLatency;
    }
    
    public void setMaxLatency(long maxLatency) {
        this.maxLatency = maxLatency;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }
    public long getTotalLatency() {
        return this.totalLatency;
    }
    
    public void setTotalLatency(long totalLatency) {
        this.totalLatency = totalLatency;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.waitsByHostByLatencyId) ) return false;
		 X.waitsByHostByLatencyId castOther = ( X.waitsByHostByLatencyId ) other; 
         
		 return (this.getAvgLatency()==castOther.getAvgLatency())
 && ( (this.getEvent()==castOther.getEvent()) || ( this.getEvent()!=null && castOther.getEvent()!=null && this.getEvent().equals(castOther.getEvent()) ) )
 && ( (this.getHost()==castOther.getHost()) || ( this.getHost()!=null && castOther.getHost()!=null && this.getHost().equals(castOther.getHost()) ) )
 && (this.getMaxLatency()==castOther.getMaxLatency())
 && (this.getTotal()==castOther.getTotal())
 && (this.getTotalLatency()==castOther.getTotalLatency());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getAvgLatency();
         result = 37 * result + ( getEvent() == null ? 0 : this.getEvent().hashCode() );
         result = 37 * result + ( getHost() == null ? 0 : this.getHost().hashCode() );
         result = 37 * result + (int) this.getMaxLatency();
         result = 37 * result + (int) this.getTotal();
         result = 37 * result + (int) this.getTotalLatency();
         return result;
   }   


}


