package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final



/**
 * X.waitsByUserByLatencyId generated by hbm2java
 */
public class X.waitsByUserByLatencyId  implements java.io.Serializable {


     private long avgLatency;
     private String event;
     private long maxLatency;
     private long total;
     private long totalLatency;
     private String user;

    public X.waitsByUserByLatencyId() {
    }

	
    public X.waitsByUserByLatencyId(long avgLatency, String event, long maxLatency, long total, long totalLatency) {
        this.avgLatency = avgLatency;
        this.event = event;
        this.maxLatency = maxLatency;
        this.total = total;
        this.totalLatency = totalLatency;
    }
    public X.waitsByUserByLatencyId(long avgLatency, String event, long maxLatency, long total, long totalLatency, String user) {
       this.avgLatency = avgLatency;
       this.event = event;
       this.maxLatency = maxLatency;
       this.total = total;
       this.totalLatency = totalLatency;
       this.user = user;
    }
   
    public long getAvgLatency() {
        return this.avgLatency;
    }
    
    public void setAvgLatency(long avgLatency) {
        this.avgLatency = avgLatency;
    }
    public String getEvent() {
        return this.event;
    }
    
    public void setEvent(String event) {
        this.event = event;
    }
    public long getMaxLatency() {
        return this.maxLatency;
    }
    
    public void setMaxLatency(long maxLatency) {
        this.maxLatency = maxLatency;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }
    public long getTotalLatency() {
        return this.totalLatency;
    }
    
    public void setTotalLatency(long totalLatency) {
        this.totalLatency = totalLatency;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.waitsByUserByLatencyId) ) return false;
		 X.waitsByUserByLatencyId castOther = ( X.waitsByUserByLatencyId ) other; 
         
		 return (this.getAvgLatency()==castOther.getAvgLatency())
 && ( (this.getEvent()==castOther.getEvent()) || ( this.getEvent()!=null && castOther.getEvent()!=null && this.getEvent().equals(castOther.getEvent()) ) )
 && (this.getMaxLatency()==castOther.getMaxLatency())
 && (this.getTotal()==castOther.getTotal())
 && (this.getTotalLatency()==castOther.getTotalLatency())
 && ( (this.getUser()==castOther.getUser()) || ( this.getUser()!=null && castOther.getUser()!=null && this.getUser().equals(castOther.getUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getAvgLatency();
         result = 37 * result + ( getEvent() == null ? 0 : this.getEvent().hashCode() );
         result = 37 * result + (int) this.getMaxLatency();
         result = 37 * result + (int) this.getTotal();
         result = 37 * result + (int) this.getTotalLatency();
         result = 37 * result + ( getUser() == null ? 0 : this.getUser().hashCode() );
         return result;
   }   


}


