package com.softorx.ntdb;
// Generated Jun 1, 2023, 12:59:21 AM by Hibernate Tools 6.1.7.Final



/**
 * X.waitsGlobalByLatencyId generated by hbm2java
 */
public class X.waitsGlobalByLatencyId  implements java.io.Serializable {


     private long avgLatency;
     private String events;
     private long maxLatency;
     private long total;
     private long totalLatency;

    public X.waitsGlobalByLatencyId() {
    }

    public X.waitsGlobalByLatencyId(long avgLatency, String events, long maxLatency, long total, long totalLatency) {
       this.avgLatency = avgLatency;
       this.events = events;
       this.maxLatency = maxLatency;
       this.total = total;
       this.totalLatency = totalLatency;
    }
   
    public long getAvgLatency() {
        return this.avgLatency;
    }
    
    public void setAvgLatency(long avgLatency) {
        this.avgLatency = avgLatency;
    }
    public String getEvents() {
        return this.events;
    }
    
    public void setEvents(String events) {
        this.events = events;
    }
    public long getMaxLatency() {
        return this.maxLatency;
    }
    
    public void setMaxLatency(long maxLatency) {
        this.maxLatency = maxLatency;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }
    public long getTotalLatency() {
        return this.totalLatency;
    }
    
    public void setTotalLatency(long totalLatency) {
        this.totalLatency = totalLatency;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.waitsGlobalByLatencyId) ) return false;
		 X.waitsGlobalByLatencyId castOther = ( X.waitsGlobalByLatencyId ) other; 
         
		 return (this.getAvgLatency()==castOther.getAvgLatency())
 && ( (this.getEvents()==castOther.getEvents()) || ( this.getEvents()!=null && castOther.getEvents()!=null && this.getEvents().equals(castOther.getEvents()) ) )
 && (this.getMaxLatency()==castOther.getMaxLatency())
 && (this.getTotal()==castOther.getTotal())
 && (this.getTotalLatency()==castOther.getTotalLatency());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getAvgLatency();
         result = 37 * result + ( getEvents() == null ? 0 : this.getEvents().hashCode() );
         result = 37 * result + (int) this.getMaxLatency();
         result = 37 * result + (int) this.getTotal();
         result = 37 * result + (int) this.getTotalLatency();
         return result;
   }   


}


